### ISSUE TITLE
Trouble setting up Ruby debugging

### ISSUE THREAD

**Issue by idmyn** [emacs-lsp/dap-mode#100]
I think I've followed all of the instructions correctly, but when running ```dap-debug``` and selecting ```Ruby Run Configuration``` I get this message: ```Debug session process exited with status: killed: 9```.

How should I go about troubleshooting this?

Cheers

**Comment by yyoncho** [comment]
Please check stderr buffer that is attached to that session.

**Comment by idmyn** [comment]
Do I need to actively open the stderr? If so, how would I do that? A second buffer does appear when I run the command, but it’s empty.

**Comment by yyoncho** [comment]
There should be buffer named like that: `(concat "*" session-name " stderr*")`

**Comment by idmyn** [comment]
Hmm. I can only see ```*ruby-ls::stderr*``` and ```*Ruby::Run stderr*```. Neither appear to have any useful debug info.

<img width="1417" alt="Screenshot 2019-07-02 at 21 20 25" src="https://user-images.githubusercontent.com/4623769/60543828-3a517d00-9d0f-11e9-9b27-25735ad4c603.png">

**Comment by yyoncho** [comment]
Can you execute in terminal command generated from: `(s-join  " " dap-ruby-debug-program )`? It should block and wait for input. 

Also, can you set dap-print-io to t and monitor the Messages buffer for the client/server communication?

**Comment by yyoncho** [comment]
I tested it locally and I got this result when there were no breakpoints and the program exited gracefully. Can you make sure that you have breakpoints or something that prevents the program from exiting?

**Comment by idmyn** [comment]
Ahh, yes, I've found the culprit. It seems to run happily now that I've commented out everything ```pry```-related. Thank you for your help!
