### ISSUE TITLE
One key debugging

### ISSUE THREAD

**Issue by prittjam** [emacs-lsp/dap-mode#103]
I am writing code in Python. I would like to bind a key to dap-debug so that a default template is chosen. That way I can just hit one key to start debugging a buffer. Is there a way to do this? e.g., I tried a lambda expression, but it did not work. Regards.

**Comment by yyoncho** [comment]
You could call dap-debug directly with the template that you want to debug. FTR I use `dap-debug-last`.

```
(defun my/debug-directly ()
  (interactive)
  (dap-debug    (list :type "python"
                      :args ""
                      :cwd nil
                      :target-module nil
                      :request "launch"
                      :name "Python :: Run Configuration")))
```
