### ISSUE TITLE
Promote `dap-utils` to `lsp-mode`?

### ISSUE THREAD

**Issue by kiennq** [emacs-lsp/dap-mode#104]
Hi, I've seen some `lsp-mode` language server is using similar script to download binary from artifact server.
Should we promote `dap-utils` to `lsp-mode` so the code between `dap-mode` and `lsp-mode` can further being shared?

Also it can help provide helper for new language server (even existing one) to work out-of-box.

**Comment by yyoncho** [comment]
IMO this is the way to go. Reusing the language servers that are bundled with vscode extension is probably the easiest way to achieve automatic installation.

**Comment by yyoncho** [comment]
Closing, because the question and there already is an issue on lsp-mode side tracking the automatic installation.
