### ISSUE TITLE
VScode equivalent of debug test

### ISSUE THREAD

**Issue by vn-ki** [emacs-lsp/dap-mode#106]
Is it possible to debug tests in go or python?

**Comment by yyoncho** [comment]
It is possible by creating the corresponding configurations. I have created them for java but I do not have the knowledge/time to do that for all debug adapters. We pretty much rely on language users to help with that(like https://github.com/emacs-lsp/dap-mode/pull/53 and https://github.com/emacs-lsp/dap-mode/pull/60) .

**Comment by yyoncho** [comment]
There are already test templates for go and python.
