### ISSUE TITLE
Show variable value inline or when mouse over in java mode?

### ISSUE THREAD

**Issue by nedijahij** [emacs-lsp/dap-mode#107]
Currently, dap-java is working but it still missing one of the most import feature. The feature that it should be is showing variable value when we put mouse over or inline. Using REPL is possible but it is not good enough and it waste lot of time. Please consider this.

**Comment by yyoncho** [comment]
This is planned, for the time being, you may use `dap-eval-thing-at-point`.

**Comment by nedijahij** [comment]
how about expand Object value inside REPL? I have tried it but it is not yet working. For example, if you have person object and then write it into REPL, it will show only the word person and i cannot click to view its property/field.

**Comment by yyoncho** [comment]
That is planned too, and maybe it will happen sooner since it is easier to implement. FTR I usually eval `person.toString()`.

**Comment by sereymongkol** [comment]
I am looking for this feature too. Please consider update this one. Thanks

**Comment by yyoncho** [comment]
I am looking into the issue.

**Comment by yyoncho** [comment]
Use 
```
     (dap-tooltip-mode 1)
     (tooltip-mode 1)
```

to enable it.

**Comment by nedijahij** [comment]
Wow, it's working great with mouse over but can we show it inline too like intellij does? I saw in intellij, it is showing on the right side of the line. doing so would save lot of time because we don't have to put mouse over the variable just to see each one of them. But, if it is not possible or because some people don't prefer this, how about when we put cursor between or on the variable name and then showing its value? this is also good because as an emacs user most people prefer keyboard rather than mouse. I believe these three options would make life easier when debug code.

**Comment by yyoncho** [comment]
>  Wow, it's working great with mouse over but can we show it inline too like intellij does? 

vscode is doing that I will have to read the implementation because it is not clear to me how vscode has implemented it using the current lsp/dap APIs. But generally, should be possible.

>  how about when we put cursor between or on the variable name and then showing its value?

You could do that via `dap-eval-thing-at-point` . Also, there is also `dap-ui-inspect-thing-at-point`.

**Comment by yyoncho** [comment]
It looks like the DAP API is not adjusted for implementing the inlining of the values, and it uses some heuristics to show the inline values (which often does not work), e. g:

![Screenshot](https://user-images.githubusercontent.com/13259670/63595646-22390400-c5c2-11e9-8316-141e43853b01.png)
 
@weinand are there any plans regarding exposing more precise API for displaying the values inline?
