### ISSUE TITLE
[dap-node] Attribute 'program' is not absolute

### ISSUE THREAD

**Issue by tomaskallup** [emacs-lsp/dap-mode#108]
I'm having trouble getting node debug running.
My config:
```elisp
(use-package dap-mode
  :ensure t
  :config
  (dap-mode 1)
  (dap-ui-mode 1))
(require 'dap-python)
(require 'dap-node)
(dap-node-setup)
```
When I open a js file, run `dap-debug`, select `Node run configuration` I get the following error:
![image](https://user-images.githubusercontent.com/26621166/61625429-023cba80-ac7b-11e9-8238-1bca7af6b137.png)

`dap-node-debug-program` has this value:
```
dap-node-debug-program is a variable defined in ‘dap-node.el’.
Its value is
("node" "/home/armeeh/.emacs.d/.extension/vscode/ms-vscode.node-debug2/extension/out/src/nodeDebug.js")
```
Which to me seems right, so what `program` value is the message referring to?

**Comment by yyoncho** [comment]
"program" is part of the debug spec(the template). I think that the error means that the file path to the :program argument should be relative to the workspace root.

**Comment by tomaskallup** [comment]
I was prompted for that and selected my current file, which resulted in the absolute path `/home/armeeh/Projects/Reas/reas-services/packages/pipedrive/test.js`.

Also the workspace root is one thing I'm confused about, how does dap-mode determine the workspace root? Can it work with projectile or does it need some file?
Couldn't find info about that in readme.

Thanks!

**Comment by yyoncho** [comment]
> Also the workspace root is one thing I'm confused about, how does dap-mode determine the workspace root?

It depends on the template, node template uses default directory:

```
      (dap--put-if-absent :dap-server-path dap-node-debug-program)
      (dap--put-if-absent :type "node")
      (dap--put-if-absent :cwd default-directory)
      (dap--put-if-absent :program (read-file-name "Select the file to run:" nil (buffer-file-name) t))
      (dap--put-if-absent :name "Node Debug")))
```

> Can it work with projectile or does it need some file?

You could register a template that does that.

Can you try to do - dap-debug-edit-template and then modify the cwd and program accordingly, then you could eval the block and the corresponding template will be present via dap-debug? The node integration was implemented by a contributor so I am not very familiar with the details of the node adapter.

**Comment by tomaskallup** [comment]
> > Also the workspace root is one thing I'm confused about, how does dap-mode determine the workspace root?
> 
> It depends on the template, node template uses default directory:

That's actually sufficient, so I can setup projectile to change the default directory.

> Can you try to do - dap-debug-edit-template and then modify the cwd and program accordingly, then you could eval the block and the corresponding template will be present via dap-debug? The node integration was implemented by a contributor so I am not very familiar with the details of the node adapter.
Like this?
![image](https://user-images.githubusercontent.com/26621166/61627266-990b7600-ac7f-11e9-8bd7-2bbc636516f6.png)
Still the same output :worried:

**Comment by yyoncho** [comment]
Can you change :program to be the full path to the file, it looks like it is asking for that? If this does not fix the issue I will create a full end to end example and ping you back.

**Comment by tomaskallup** [comment]
> Can you change :program to be the full path to the file, it looks like it is asking for that?
Ah, that worked, so does this mean the expansion of `${workspaceRoot}` doesn't work?

**Comment by yyoncho** [comment]
@tomaskallup yes, I haven't implemented the expansion since you could do that in the template via elisp code which is ultimately more powerful than the simple string replacement offered by vscode. FTR at some point we will support it because we want to support vscode templates to easy the transition vscode -> emacs.

**Comment by tomaskallup** [comment]
> @tomaskallup yes, I haven't implemented the expansion since you could do that in the template via elisp code which is ultimately more powerful than the simple string replacement offered by vscode. FTR at some point we will support it because we want to support vscode templates to easy the transition vscode -> emacs.

That's something I was hoping would be already supported, I'm glad that will at some point be awailable. For now I guess I'll setup some autoload and define my dap configurations in project directories.

Thanks a lot for the help!
