### ISSUE TITLE
[dap-python] Symbol’s value as variable is void: python-executable

### ISSUE THREAD

**Issue by tomaskallup** [emacs-lsp/dap-mode#109]
Hi, I'm not able to get python debugging working, I receive the above mentioned message when running just the default `Python :: Run Configuration`.
I have python on my system & I also tried installing pyenv, as I saw that's used if possible to determine the executable.
Outputs of `which python` & `pyenv which python`:
![image](https://user-images.githubusercontent.com/26621166/61658573-e6aad180-acc5-11e9-88df-1e24b392a57b.png)

My configuration for dap-mode:
```elisp
(use-package dap-mode
  :ensure t
  :config
  (dap-mode 1)
  (dap-ui-mode 1))
(require 'dap-python)
(require 'dap-node)
(dap-node-setup)
```

**Comment by yyoncho** [comment]
fixed with https://github.com/emacs-lsp/dap-mode/commit/7d22cf541d7a23d6366a36b33bc8a36d4b583d66

**Comment by tomaskallup** [comment]
Perfect, thanks for the quick response!
