### ISSUE TITLE
How to config go debug

### ISSUE THREAD

**Issue by taigacute** [emacs-lsp/dap-mode#110]
hi  i am new come to emacs. i have config this
```
  ;;Debug
  (use-package dap-mode
    :diminish
    :functions dap-hydra/nil
    :bind (:map lsp-mode-map
                ("<f5>" . dap-debug)
                ("M-<f5>" . dap-hydra))
    :hook ((after-init . dap-mode)
          (dap-mode . dap-ui-mode)
          (dap-session-created . (lambda (&_rest) (dap-hydra)))
          (dap-terminated . (lambda (&_rest) (dap-hydra/nil)))
          (go-mode . (lambda () (require 'dap-go)))
          ((js-mode js2-mode) . (lambda () (require 'dap-chrome))))
    )
```
but when i run debug . i got error
```
Debug session process exited with status: exited abnormally with code 1
```
seems like should installed vscode-go? i download the vscode-go from github. i installed node...need help  what should i do

**Comment by yyoncho** [comment]
When the session ends up like that there is stderr buffer with an error message.

**Comment by taigacute** [comment]
ok,so . what should i do on my config?

**Comment by yyoncho** [comment]
The issue is outside emacs, what do you have in the error buffer?

**Comment by taigacute** [comment]
i  do like this open a go file then trigger debug
![git](https://user-images.githubusercontent.com/41671631/62102234-c6cd6c00-b2ca-11e9-9ff8-76a2685711ba.gif)

**Comment by yyoncho** [comment]
Yes, but what do you have in the buffer named like that: `(concat "*" session-name " stderr*")`

**Comment by taigacute** [comment]
hmm  dont know what is this `(concat "*" session-name " stderr*")`, sorry new come to emacs.. input it in commandline i got this
![image](https://user-images.githubusercontent.com/41671631/62102814-ecf40b80-b2cc-11e9-8d80-04912e12d872.png)

**Comment by yyoncho** [comment]
So if you look at the buffer list there should be buffer which name ends with `stderr*`, can you paste the content of that buffer?

**Comment by taigacute** [comment]
the content of this buffer? only some code about go ,but these code can  work, not bad code.
```go
// Package main provides ...
package main

import (
	"fmt"
	"sync"
	"time"
)

func main() {
	worker := func(strings <-chan string) <-chan interface{} {
		a := make(chan interface{})
		go func() {
			defer fmt.Println("worker exited.")
			defer close(a)
			for s := range strings {
				fmt.Println(s)
			}
		}(
)
		return a
	}
	worker(nil)
	fmt.Println("Done.")
}
func counter(name string) {
	for n := 0; n < 20; {
		n++
		fmt.Printf("%v is %v\n", name, n)
	}
}

func hungry() {
	var wg sync.WaitGroup
	var sharedLock sync.Mutex
	const runtime = 1 * time.Second
	greedyWorker := func() {
		defer wg.Done()
		var count int
		for begin := time.Now(); time.Since(begin) <= runtime; {
			sharedLock.Lock()
			time.Sleep(3 * time.Nanosecond)
			sharedLock.Unlock()
			count++
		}
		fmt.Printf("Greedy worker was able to execute %v work loops\n", count)
	}
	politeWorker := func() {
		defer wg.Done()
		var count int
		for begin := time.Now(); time.Since(begin) <= runtime; {
			sharedLock.Lock()
			time.Sleep(1 * time.Nanosecond)
			sharedLock.Unlock()

			sharedLock.Lock()
			time.Sleep(1 * time.Nanosecond)
			sharedLock.Unlock()

			sharedLock.Lock()
			time.Sleep(1 * time.Nanosecond)
			sharedLock.Unlock()
			count++
		}
		fmt.Printf("Polite worker was able to execute %v work loops\n", count)
	}
	wg.Add(2)
	go greedyWorker()
	go politeWorker()
	wg.Wait()
	b := time.Now()
	fmt.Println(time.Since(b))
}
```

**Comment by yyoncho** [comment]
Not the source buffer. When dap mode starts it creates several new buffers and one of them is named like that:

`*<session-name>-stderr*`

So can you do:

`M-x ibuffer` - this will list all buffers currently opened. Then look for the buffer that corresponds to the session that has just failed and check what the content of that buffer is?

**Comment by taigacute** [comment]
big thanks for your friendly reply with a new emacser . well i got this 
![image](https://user-images.githubusercontent.com/41671631/62104945-a05ffe80-b2d3-11e9-9ea3-9ef16409e2e8.png)

**Comment by yyoncho** [comment]
So, for the go debug session the buffer should be named something like `*Launch Debug Package stderr*` and you have 2 buffers named like that in this list - what is the content of these buffers?

**Comment by yyoncho** [comment]
To be more specific - the first one and the last one. Go to each one of them as press Enter.

**Comment by taigacute** [comment]
![image](https://user-images.githubusercontent.com/41671631/62105709-b79feb80-b2d5-11e9-9e9b-8c191aa30ce3.png)
because  in this floder dont have vscode-go extensions . i download the vscode-go form github .but the structure is different , i dont see the out folder
![image](https://user-images.githubusercontent.com/41671631/62105795-02216800-b2d6-11e9-89e2-065ed520cdde.png)

**Comment by yyoncho** [comment]
You should download the extension from the market place, not the content of github repo. Can you delete the content of .emacs.d/.extension and then do M-x dap-go-setup and try to debug the go package once again?

**Comment by taigacute** [comment]
i download it from market. but its `ms-vscode.Go-0.11.4.vsix`. i download a wrong one? its `.vsix`.

**Comment by yyoncho** [comment]
vsix is zip file.

**Comment by yyoncho** [comment]
Did you try to run dap-go-setup and then try to debug the go file?

**Comment by taigacute** [comment]
no  i didnt run it.  cant find it
![image](https://user-images.githubusercontent.com/41671631/62108432-9e4e6d80-b2dc-11e9-9eb2-1a7cf340c904.png)

**Comment by taigacute** [comment]
its work thanks!!!

**Comment by taigacute** [comment]
see your pic it has these things. how to do these
![image](https://user-images.githubusercontent.com/41671631/62110894-fc318400-b2e1-11e9-99db-b346fabc87df.png)

**Comment by yyoncho** [comment]
Refer to readme page.

**Comment by arvydasg** [comment]
> Refer to readme page.

you are surprisingly patient!
