### ISSUE TITLE
dap-chrome unable to debug to React app

### ISSUE THREAD

**Issue by darioceccoli** [emacs-lsp/dap-mode#116]
I'm trying to setup `dap-mode` for React apps using `dap-chrome`.

I can set and hit breakpoints correctly using a new app using `npx create-react-app my-react-app`.

When trying on the apps I'm working on using `dap-debug`, Chrome launches correctly, I see the Chrome session on `dap-ui-sessions`and  I see the out window which correctly mirrors Chrome's `console`, but breakpoints remain in inactive state and they don't get hit.

My configuration is pretty straightforward:

```elisp
(require 'dap-chrome)

(dap-register-debug-template "Chrome Browse my-project"
  (list :type "chrome"
        :cwd nil
        :mode "url"
        :request "launch"
        :webRoot "~/Developer/my-project"
        :url "http://localhost:3002"
        :name "Chrome Browse my-project"))
```

The same project can be debugged correctly on vscode using the equivalent configuration:

```json
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:3002",
      "webRoot": "${workspaceFolder}"
    },
```

Debug also works on Chrome using Chrome devtools.

Any suggestions on what the issue could be, or how can troubleshoot it would be highly appreciated!

**Comment by yyoncho** [comment]
Before me digging into that I think that the webRoot should be fullpath(without ~).

**Comment by darioceccoli** [comment]
That was it 🎉! Thank you very much for the quick reply and the awesome work on `emacs-lsp` and `dap-mode` @yyoncho!

Confusingly enough, setting up a new project via `npx create-react-app` and using the path containing `~` works correctly. Probably it depends on`WebpackDevServer`'s configuration 🤷‍♂️

**Comment by yyoncho** [comment]
Great! FTR in the future we will support directly the vscode debug configurations which.
