### ISSUE TITLE
Where's the documentation?

### ISSUE THREAD

**Issue by Osram-Gru** [emacs-lsp/dap-mode#121]
Where can I find the description of the templates?
How do I create my own templates?

After googling some time I found nothing about that. Only https://github.com/emacs-lsp/dap-mode#usage which is not really helpful.

To be more concrete: I want to create a template for `dlv connect 127.0.0.1:8819` . I came up with

```
(dap-register-debug-template "Connect to headless dlv"
  (list :type "go"
        :request "launch"
        :name "Connect to headless dlv"
        :mode "connect"
        :program nil
        :args "connect 127.0.0.1:8819"
        :env nil
        :envFile nil))
```
But that's just guesswork because I found no documentation. Of course it doesn't work:

'Debug session process exited with status: exited abnormally with code 1'

That's really not a good start for me :/

**Comment by yyoncho** [comment]
You can create your templates by calling `dap-register-debug-template` as per readme. The best place to find the documentation is at the vscode extension documentation. 

In your case: https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code . The vscode templates are in the package json file, e. g. https://github.com/microsoft/vscode-go/blob/master/package.json#L324 . 

In the future, we will add support for the vscode configurations so it will be possible to follow their howto's. 

Note that the vscode placeholders are not supported in dap-mode ATM (e. g. `${workspaceRoot}`). 

Please, let me know if you have more questions.
