### ISSUE TITLE
Please help with PHP remote debug config 

### ISSUE THREAD

**Issue by quan-na** [emacs-lsp/dap-mode#123]
I can not get PHP remote debug to work. It can get the thread to stop but there's no source mapped.

I found that there's a pathMappings config in vscode, is this the right way to use it?
<pre><code>
(require 'dap-php)
(dap-php-setup)
(dap-register-debug-template "My Php Debug"
  (list :type "php"
        :cwd nil
        :request "launch"
        :name "Php Debug"
        :args '("--server=4711")
        :stopOnEntry t
        :pathMappings '(("/my/local/folder/src/" "/var/www/html/"))
        :sourceMaps t))
</code></pre>

**Comment by yyoncho** [comment]
Based on the package.json in the debug adapter repo, the mappings are object which on our side is equivalent to hashtable. So you could use it to build one. Let me know if it helps.

**Comment by quan-na** [comment]
Still no result. Is this the right way to use ht hashtable?
<pre>
(require 'dap-php)
(dap-php-setup)
(dap-register-debug-template "My Php Debug"
  (list :type "php"
        :cwd nil
        :request "launch"
        :name "Php Debug"
        :args '("--server=4711")
        :pathMappings (ht ("/my/local/src/" "/var/www/html/"))
        :sourceMaps t))
</pre>

**Comment by yyoncho** [comment]
> Still no result. Is this the right way to use ht hashtable?

Yes. If it doesn't work it might be better to ask in the debug adapter repo providing the full emacs/debug adapter communication. You may collect it after setting `lsp-print-io` to `t`.

cc @tomterl  who may have a clue since he is the author of the php integration.

**Comment by tomterl** [comment]
I don't need path-mapping in my setup (a symbolic link makes sure paths are identical remote and locally); but I'll take a look tomorrow, today I'm out of office -- maybe I spot something

**Comment by tomterl** [comment]
If I interpret the code correctly, it's the other way around:
````
:pathMappings (ht ("/var/www/html" "/my/local/src"))
```` 
base on this line of code:
````
pathMappings[args.serverSourceRoot] = args.localSourceRoot;
````
So it seems that you can, if the hashtable does not work, try to set
````
:serverSourceRoot "/var/www/html"
:localSourceRoot "/my/local/src"
````

**Comment by tomterl** [comment]
Hi @quan-na - is this still something you could use some help on?  Than just holler and I take a deeper look into things.  Or do you have a working setup? Than a hint what works would be nice to have to adjust the documentation. regards, Tom

**Comment by quan-na** [comment]
@tomterl @yyoncho 
This config worked.
> `:pathMappings (ht ("/var/www/html" "/my/local/src"))`
Thank you.
