### ISSUE TITLE
Adding support for C# via netcoredbg or clrdbg

### ISSUE THREAD

**Issue by sebasmonia** [emacs-lsp/dap-mode#125]
Trying to setup netcoredbg to attach to a running process. I have this so far:

```
(defun dap-csharp-populate-netcoredbg (conf)
  "Populate CONF with the required arguments."
  (-> conf
      (dap--put-if-absent :dap-server-path "netcoredbg")
      (dap--put-if-absent :args '("--interpreter=vscode" "--attach "))
      (dap--put-if-absent :type "c-sharp")
      (dap--put-if-absent :cwd default-directory)
      (dap--put-if-absent :target (read-string "Process ID: "))
      (dap--put-if-absent :name "C# Debug")))

(dap-register-debug-provider "c-sharp" 'dap-csharp-populate-netcoredbg)
(dap-register-debug-template "C#::Launch"
                             (list :type "c-sharp"
                                   :request "launch"
                                   :name "C#::Launch"))
```
But get an error on dap-debug. Tried to debug it but couldn't find the problem so far, I'm sure I did something wrong in the config.
The process should be started like this: `netcoredbg --interpreter=vscode --attach ####`

Thank you!

**Comment by yyoncho** [comment]
Not sure whether it is all that you need to fix but the `:dap-server-path` should contain the args, 
check the python adapter: https://github.com/emacs-lsp/dap-mode/blob/master/dap-python.el#L74

**Comment by yyoncho** [comment]
Actually, this one is a better example: https://github.com/emacs-lsp/dap-mode/blob/master/dap-chrome.el#L52

**Comment by yyoncho** [comment]
And one more thing - `:dap-server-path` should be a list of strings.

**Comment by sebasmonia** [comment]
```
(defun dap-csharp-populate-netcoredbg (conf)
  "Populate CONF with the required arguments."
  (-> conf
      (dap--put-if-absent :dap-server-path '("c:/netcoredbg/netcoredbg.exe" "--interpreter=vscode" "--attach "))
      (dap--put-if-absent :type "c-sharp")
      (dap--put-if-absent :cwd default-directory)
      (dap--put-if-absent :target (read-string "Process ID: "))
      (dap--put-if-absent :name "C# Debug")))

(dap-register-debug-provider "c-sharp" 'dap-csharp-populate-netcoredbg)
(dap-register-debug-template "C#::Launch"
                             (list :type "c-sharp"
                                   :request "attach"
                                   :name "C#::Launch"))
```
That works, but the debugger exits with an error. Is this going to pass the ProcessId correctly? trying to figure out if there's a log buffer or something for dap-mode to see the invocation :)

**Comment by sebasmonia** [comment]
Found in another issue about `dap-print-io`.

The output is
```
Sending: 
{
  "command": "initialize",
  "arguments": {
    "clientID": "vscode",
    "clientName": "Visual Studio Code",
    "adapterID": "c-sharp",
    "pathFormat": "path",
    "linesStartAt1": true,
    "columnsStartAt1": true,
    "supportsVariableType": true,
    "supportsVariablePaging": true,
    "supportsRunInTerminalRequest": true,
    "locale": "en-us"
  },
  "type": "request",
  "seq": 1
}
dap--send-message: Writing to process: Invalid argument, C#::Launch
Debug session process exited with status: exited abnormally with code 1
```
`C#::Launch` is the `name`, and it seems that is being passed to the debugger and it can't interpret it.

**Comment by yyoncho** [comment]
@sebasmonia can you do toggle-debug-on-error? Also, can you remove `#` from the interpreter name just to make sure that it is not messing up the emacs internal infrastructure?

**Comment by sebasmonia** [comment]
I sure can. Now I'm also testing with `clrdbg` which uses the same parameters as the other debugger.
One sec...

**Comment by sebasmonia** [comment]
```
Sending: 
{
  "command": "initialize",
  "arguments": {
    "clientID": "vscode",
    "clientName": "Visual Studio Code",
    "adapterID": "c-sharp",
    "pathFormat": "path",
    "linesStartAt1": true,
    "columnsStartAt1": true,
    "supportsVariableType": true,
    "supportsVariablePaging": true,
    "supportsRunInTerminalRequest": true,
    "locale": "en-us"
  },
  "type": "request",
  "seq": 1
}
Debug session process exited with status: exited abnormally with code 255
```

Removed the `#` everywhere, no luck. Also no errors appeared to debug on. I think the problem is how my configuration is building the command string. From a `cmd` window I can attach just fine with either debugger using MI.
And I can launch them using `M-x gbd` but they have unsupported MI commands that break the interaction.
Using the vscode interpreter mode seems like my best bet now.

**Comment by yyoncho** [comment]
> Debug session process exited with status: exited abnormally with code 255

What is the content of the stderr buffer?

**Comment by sebasmonia** [comment]
```
ERROR: Unknown switch '--attach '.


Process Csharp Debug stderr finished
```

Guessing the process ID wasn't passed to the interpreter 🤔

**Comment by yyoncho** [comment]
I have missed that comment: https://github.com/emacs-lsp/dap-mode/issues/125#issuecomment-532747781

You should pass the id as part of the command, dap-mode wont do that for you. The target also is PORT, so you should keep it empty in this case because it is stdio provider. 

So something like that will bring you to the next step.

```
(defun dap-csharp-populate-netcoredbg (conf)
  "Populate CONF with the required arguments."
  (-> conf
      (dap--put-if-absent :dap-server-path `("c:/netcoredbg/netcoredbg.exe" "--interpreter=vscode" "--attach" ,(read-string "Process ID: ")))
      (dap--put-if-absent :type "c-sharp")
      (dap--put-if-absent :cwd default-directory)
      (dap--put-if-absent :name "C# Debug")))

(dap-register-debug-provider "c-sharp" 'dap-csharp-populate-netcoredbg)
(dap-register-debug-template "C#::Launch"
                             (list :type "c-sharp"
                                   :request "attach"
                                   :name "C#::Launch"))
```

**Comment by yyoncho** [comment]
Also, if you use gitter we may move the discussion there for faster and more interactive communication.

**Comment by sebasmonia** [comment]
I'm at work so it can be challenging, if possible will give your suggestion a try later today or tomorrow.

Thanks for taking the time to guide me through this setup!

**Comment by TOTBWF** [comment]
Got a preliminary implementation over at #138, would love to get a windows user to play with things a bit!

**Comment by sebasmonia** [comment]
Thank you @TOTBWF ! I have no idea how to test it though, but I have a minimal project setup now, and I have a Windows workstation.

**Comment by sebasmonia** [comment]
Finally got around to testing this, @TOTBWF .

Couldn't use the automatic installer for netcoredbg:

```
Expand-Archive : .gz is not a supported archive file format. .zip is the only supported 
archive file format.
At line:1 char:1
+ Expand-Archive -path 'c:/Users/smonia/AppData/Local/Temp/netcoredbgm1 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (.gz:String) [Expand-Archive], IOExceptio 
   n
    + FullyQualifiedErrorId : NotSupportedArchiveFileExtension,Expand-Archive
 ```
I have a version built so I pointed the install dir so it would pick it up. 
Modified the code suggesting the Debug dir to include a starting slash: `(concat (lsp-workspace-root) "/bin/Debug")`
Then it seems it's not quoting arguments correctly: `dotnet-~/debugtest/bin/Debug/netcoreapp2.1/win10-x64/debugtest.exe does not exist`

I couldn't get dap-mode to work with Python either (which I intended to use as a test of how things _should_ look 😅) so I might be doing something more basic wrong.

Will try to figure out the invocation...

**Comment by sebasmonia** [comment]
The problem was that my test project is inside my home folder, but on Windows `~` needs to be expanded.
`(expand-file-name (read-file-name....`

**Comment by sebasmonia** [comment]
It still fails, in the Messages buffer:
```
No message handler for capabilities
error in process filter: Failed command ’configurationDone’ : 0x80004005 [2 times]
error in process filter: Wrong type argument: hash-table-p, nil [2 times]
``

**Comment by mslot** [comment]
Did you ever fix this?

I have this config
```
(defun dap-netcore--populate-default-args (conf)
  "Populate CONF with the default arguments."
  (dap--put-if-absent conf :cwd default-directory)
  (dap--put-if-absent conf :program (read-file-name "Select an executable:" (concat (lsp-workspace-root) "bin/Debug")))
  (dap--put-if-absent conf :dap-server-path (list (dap-netcore--debugger-locate) "--interpreter=vscode")))

(dap-register-debug-provider
 "coreclr"
 'dap-netcore--populate-default-args)

(dap-register-debug-template ".Net Core Launch (Console)"
                             (list :type "coreclr"
                                   :request "launch"
                                   :name "NetCoreDbg::Launch"
                                   :stopAtEntry t))

(dap-register-debug-template ".Net Core Attach"
                             (list :type "coreclr"
                                   :request "attach"
                                   :program ""
                                   :processId "${command:pickProcess}"
                                   :name "NetCoreDbg::Launch"
                                   :stopAtEntry f))
```

When it attach, i need to switch to `dap-switch-thread` and then i get this in the Messages buffer

```
error in process filter: Failed command ’stackTrace’ : 0x80131302 [2 times]
```

I can easily launch my program, and attach on entry. 

It is not anything difficult i am testing with
```csharp
using System;

namespace console
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello");

            while(true)
            {
                System.Threading.Thread.Sleep(5000);
                Console.WriteLine(" world!");
            }
        }
    }
}
```

**Comment by sebasmonia** [comment]
I still can't debug web applications (on Linux at least) but I think that has more to do with netcoredbg than dap-mode.
Should we close this issue? My vote is _yes_.

**Comment by yyoncho** [comment]
> I still can't debug web applications (on Linux at least) but I think that has more to do with netcoredbg than dap-mode.
> Should we close this issue? My vote is _yes_.

I am fine. Have you tested with vscode?

**Comment by sebasmonia** [comment]
No :)

**Comment by mslot** [comment]
I can debug Web applications and azure functions on Linux with spacemacs.

**Comment by sebasmonia** [comment]
Interesint @mslot , when I try I have to switch threads but even then it won't stop on the breakpoints. I see an error about an invalid commands for the debugger.

**Comment by mslot** [comment]
@sebasmonia I think you just have to invoke a controller, eg call an endpoint and then it invokes, if I remember correctly. I also thought I had to switch thread for it to work, both in a webapi and in a function.

**Comment by XMasterNinni** [comment]
Hi, 
`dap-netcore-download-url` links seem to be broken. :)

**Comment by sebasmonia** [comment]
Hi @XMasterNinni! It seems the netcoredbg publishers changed something in their CI setup.

https://github.com/Samsung/netcoredbg/releases/download/1.2.0-635/netcoredbg-linux-focal.tar.gz should work, check out 
https://github.com/Samsung/netcoredbg/releases/latest if you need a different OS.

To have dap-netcore automatically handle the download for you, customize the variable to the new URL.

(Been playing a bit with it and couldn't find a way to link directly to /latest like we had before...?)

**Comment by sebasmonia** [comment]
Howdy @mslot!!! I managed to get it working :) thank you!

Sometimes I just need to switch thread and then try the same switch command again for a new thread to show up with a `(breakpoint)` in parenthesis, which then works.

I still get some messages about `error in process filter: Failed command ’stackTrace’ : [address]` but they seem to not have any negative impact.

**Comment by CsBigDataHub** [comment]
@mslot @sebasmonia 

I see that you got  `netcoredbg` working with `dap-mode`. Can you please provide steps to configure it or share a working configuration as a reference.

Thanks

**Comment by sebasmonia** [comment]
Hi @CsBigDataHub! here is a minimal `dap-mode` config for `netcoredbg`:
```
(use-package dap-mode
  :commands (dap-debug dap-breakpoints-add)
  :init
  (dap-mode 1)
  (dap-ui-mode 1)
  (dap-auto-configure-mode)
  (require 'dap-netcore)
  :custom
  (dap-netcore-install-dir "/home/hoagie/.emacs.d/.cache/"))
```
My full config `dap-mode` config, includes a bunch of keybindings I tried once and didn't like, but never got around to revisiting :)
https://github.com/sebasmonia/dotfiles/blob/9f768ef5e5d0f19117eb4b12982979692594a28b/.emacs/init.el#L295

Let me know if you encounter any problems.
BTW your message reminded me we should close this issue...we can do it after your setup is running :)

**Comment by CsBigDataHub** [comment]
Thanks @sebasmonia , all I needed is 

```
 (require 'dap-netcore)
```
This issue can be closed.

@yyoncho 
Also in I think this page needs to be  https://emacs-lsp.github.io/lsp-mode/page/lsp-csharp/ updated with `dap-netcore` debugger option.
Looks like these pages are auto-generated, I could not find where to update and create a PR.
