### ISSUE TITLE
How to go back in stack trace

### ISSUE THREAD

**Issue by ratnesh1729** [emacs-lsp/dap-mode#127]
This is more of a readme/tutorial addition - also helpful in understanding DAP.
Supposing I stop at a breakpoint - how do I go back. In gdb terms - "up" is the right keyword.
I am looking for equivalent functionality . Or if there is a way to list stack as in gdb - which lists all functions called prior to the breakpoint (btrace). 

Thanks!

**Comment by yyoncho** [comment]
Use dap-switch-stack-frame or the session view. There is https://github.com/emacs-lsp/dap-mode/issues/54
