### ISSUE TITLE
dap-java-debug and templates

### ISSUE THREAD

**Issue by r-darwish** [emacs-lsp/dap-mode#129]
Using `dap-java-debug` is convenient because `dap-java--populate-default-args` automatically fills arguments such as the class path. However, this function doesn't use the template system.

On the other hand, If I do define a template and use `dap-debug` then I need to set everything myself, including the class path.

I hacked this function in my configuration:

```elisp
(defun my/dap-java-debug (debug-args)
  "Start debug session with DEBUG-ARGS."
  (interactive (list (dap-java--populate-default-args (-> (dap--completing-read "Select configuration template: "
                                                                                dap--debug-template-configurations
                                                                                'cl-first nil t)
                                                          cl-rest
                                                          copy-tree))))
  (dap-start-debugging debug-args))
```

This allows me to define a partial template such as this:

```elisp
(dap-register-debug-template "Minion"
  (list 
   :cwd "/Users/rodarwis/path/to/somewhere"
   :vmArgs "-Dpackage.environmentName=Dev"
   :args ""
   :env '(("DEV" . "1"))
   :mainClass "com.whatever.ConsoleRunner"
   :projectName "myproject"
   ))
```

and still have `dap-java--populate-default-args` fill in the class path and other values.

I think this would be useful for others, but I'm not sure what's the correct solution here. Maybe have a new `dap-java-debug-from-template` which is similar to my function?

**Comment by yyoncho** [comment]
Have you tried `C-u dap-debug-edit-template`? This will prepopulate the template and let you register it under a different name with prepopulated arguments. 

> On the other hand, If I do define a template and use dap-debug then I need to set everything myself, including the class path.

AFAICS this is not the case, it calls the populate function and the populate function should be written in a way that it populates only the missing properties.

**Comment by r-darwish** [comment]
> Have you tried `C-u dap-debug-edit-template`? This will prepopulate the template and let you register it under a different name with prepopulated arguments.

I wasn't aware of this feature. This is really nice. I think it should be documented somehow.

> AFAICS this is not the case, it calls the populate function and the populate function should be written in a way that it populates only the missing properties.

Seems so... I remember that it didn't work like that in the past but perhaps I misused something. I think it's best if I'll just submit a PR explaining these things in the documentation.

**Comment by yyoncho** [comment]
Yes, we are a bit weak on the documentation side and there are a lot of hidden features. Ideally, we would have demo/wiki as vscode does.

**Comment by yyoncho** [comment]
Is there anything to address for this issue?

**Comment by r-darwish** [comment]
No. I think my documentation improvements are helpful enough.
