### ISSUE TITLE
Typing next in dap-ui-repl with gdb causes the navigated buffer to replace repl

### ISSUE THREAD

**Issue by cbourgeois** [emacs-lsp/dap-mode#136]
Hello,

I have setup dap-mode with GDB, I am interested in having access to the native GDB console and dapl-ui-repl is adequate but unfortunately the buffer is always replaced by the source being navigated.

Let me know if it's difficult to reproduce, I'm happy to help. Additionally, having the capability to setup the environment like `gdb-many-windows` would be helpful.

Thanks for you work,

**Comment by yyoncho** [comment]
Use https://gist.github.com/makinbakonpancakes/9cd17fc95351fe61c49beeff385ddb5c to mark the window as dedicated and https://github.com/emacs-lsp/dap-mode/wiki/HowTo:-Display-debug-windows-on-session-startup to show the debug windows(or whatever windows you want). 

At some point, we might have out of the box solution.

**Comment by cbourgeois** [comment]
Thanks for the workaround !

**Comment by yyoncho** [comment]
This should be fixed in latest dap-mode, we use different strategy for selecting windows. Please reopen if you are still hitting it.
