### ISSUE TITLE
Wording on readme

### ISSUE THREAD

**Issue by dericbytes** [emacs-lsp/dap-mode#139]
The following sentence has not translated well  to english and is difficult to read. 

```
For easier of setting up vscode extension, you only need call dap-firefox-setup after requiring dap-firefox.
Or manually download and extract VSCode Firefox Debug Extension.
```
here is a possible alternative.

```
After installing the library `dap-firefox'. You can use the helper function `dap-firefox-setup' to download and setup the 'vscode extension' needed for `dap-firefox' to work.
Or you can download and extract it manually: VSCode Firefox Debug Extension.
```

**Comment by yyoncho** [comment]
I am not a native speaker, but is: "After installing the library `dap-firefox'."  a correct sentence? Also, willing to provide a PR with the proper adjustments?

**Comment by dericbytes** [comment]
I am a native speaker, although many non-natives know english better than me. It is not a complete sentence i should have used a comma.  'After installing the library `dap-firefox.el', you can..'

**Comment by yyoncho** [comment]
This was fixed by @brotzeit
