### ISSUE TITLE
project specific dap debug template

### ISSUE THREAD

**Issue by joaocortes** [emacs-lsp/dap-mode#140]
I have multiple independent `java` projects that I would like to debug, and the classes I want to run take command line arguments.

Consider project0. I want to run a class that takes a command line argument \<cmd args\>. If i create a new template by calling ``dap-debug-edit-template`` and filling the ``:args`` field with "<cmd args>", I can run It as intended.
However, when I want to debug another project, project1, the template specifically made for project0 is listed by dap debug ``dap-debug``.

Shouldn't the ``:projectName`` field in the template prevent templates from different projects to populate the options displayed by ``dap-debug``?

**Comment by yyoncho** [comment]
The implementation that you are proposing wont work because the projectName is java specific and also there is no convenient API for retrieving the current project name (AFAIK). I changed the templates to be dir local here it is an example configuration dap-mode project: (of course, you could use .dir-locals as well).

``` elisp
(dir-locals-set-class-variables
 'dap-mode-templates
 '((java-mode . ((dap-debug-template-configurations . (("This is the only template that you will see when you are in dap-mode project"
                                                        :type "java"
                                                        :request "attach"
                                                        :hostName "localhost"
                                                        :port nil)))))))

(dir-locals-set-directory-class
 "/home/kyoncho/Sources/lsp/dap-mode/" 'dap-mode-templates)
```

**Comment by joaocortes** [comment]
That was quick. Thanks

**Comment by skebanga** [comment]
>  there is no convenient API for retrieving the current project name

Can you use `projectile-project-name`?
