### ISSUE TITLE
dap-go doesn't seem to support Go mod

### ISSUE THREAD

**Issue by f4nyc** [emacs-lsp/dap-mode#142]
**Description :octocat:**
I use spacemacs and get dap-mode to work for project in $GOPATH/src well.
I am trying to get debugging to work for go project which use go module.

**Reproduction guide :beetle:**
+ open the project
+ `M-x` `dap-breakpoint-toggle`
+ `M-x`  `dap-debug`
+ select `Go Launch File Configuration.`

**Observed behaviour :eyes: :broken_heart:**
I got
>Warning (emacs): Initialize request failed: Failed to continue: Check the debug console for details.
Warning (emacs): Initialize request failed: Failed to continue: Check the debug console for details.
Warning (emacs): Initialize request failed: Failed to continue: Check the debug console for details.

and
>go: GOPATH entry is relative; must be absolute path: "undefined".
For more details see: 'go help gopath'
exit status 2
Process exiting with code: 1

**System Info :computer:**
My ~/.spacemacs is
```elisp
   dotspacemacs-configuration-layers
   '(
     (go :variables
           go-backend 'lsp
           go-tab-width 4
           godoc-at-point-function 'godoc-gogetdoc)
     lsp
     debug
     dap
     ...
     )
...

(defun dotspacemacs/user-config ()
  (use-package lsp-mode
    :hook (go-mode . lsp-deferred)
    :commands (lsp lsp-deferred))
  (require 'dap-go)
  ...
)
```
+ `$GOPATH` is `/opt/go`
+  project is in /opt/test

And the VSCode-Go extension is copied from VSCode which also works well with go mod.
I put `(message "%S" conf)` in dap-go.el, and get
>(:type "go" :request "launch" :name "Launch File<3>" :mode "debug" :program "/opt/test/main.go" :buildFlags nil :args nil :env nil :envFile nil :dap-server-path ("node" "/home/f4nyc/.emacs.d/.extension/vscode/ms-vscode.go/extension/out/src/debugAdapter/goDebug.js") :dlvToolPath "/opt/go/bin/dlv")

I notice that dlvToolPath doesnt seem to be used in dap-mode.el

Thanks for your help!

**Comment by yyoncho** [comment]
> go: GOPATH entry is relative; must be absolute path: "undefined".

Can you check what `M-: (getenv "GOPATH") RET` is returning? You may use `(setenv "GOPATH" "...")` to update the internal emacs path

> I notice that dlvToolPath doesn't seem to be used in dap-mode.el

It is sent to the adapter.

**Comment by f4nyc** [comment]
Thanks, since GOPATH is set , dap-mode works normally.
