### ISSUE TITLE
Restart dap command with `g` like in compilation mode

### ISSUE THREAD

**Issue by dakra** [emacs-lsp/dap-mode#150]
I like that in `compilation-mode` I can simpy press `g`
and it re-runs the compilation command I used.

I mainly use `dap-java-run-test-class` and there it would be
handy to easily re-run the tests.
(Also I think the session name is wrong but that's another
and very minor issues, e.g. buffer name is "* server log*")

Thank you very much for your work on lsp-java and this.
Without it I would be forced to use Eclipse or IntelliJ ;)

**Comment by yyoncho** [comment]
Have you tried using `dap-debug-last` to achieve the same?

**Comment by dakra** [comment]
No. But `dap-debug-last` prompts for a run configuration.
I guess I want `dap-debug-restart` but there it says
`user-error: There is session to restart`
when I try the restart from the `dap-java-run-test-class` buffer.
(Also just saw that there is a "no" missing in the error).

**Comment by yyoncho** [comment]
dap-debug-last prompts for configuration only if there was no previous run.

**Comment by dakra** [comment]
Well, I don't call any `dap-debug-*` commands, I run `dap-java-run-test-class` which apparently doesn't set a session, so dab-debug-last and -restart don't work (and the buffer name is missing the session name).
I tried to look at the code quick but couldn't figure out what to change in 5-10minutes and I don't have much time atm.

**Comment by yyoncho** [comment]
I see - It works on my side because I use `dap-java-debug-test-class` instead of `dap-java-run-test-class`. This is an inconsistency/bug on dap-mode side.

You may use `M-x recompile` to run the last test right now(if you have used the `run` version). I will keep the bug open but it will be handled with lower priority because there is a workaround and the functionality you want is there.

**Comment by dakra** [comment]
Oh, it didn't even occur to me that the dap output is also a compilation buffer and I can simply use `recompile`. That works as I want. :+1: 
Thanks for your fast help.

**Comment by dakra** [comment]
Just went through some old issues and think I can close this as `recompile` does what I want. Thanks.
