### ISSUE TITLE
Identify breakpoints in emacs-nox

### ISSUE THREAD

**Issue by hacktivista** [emacs-lsp/dap-mode#151]
I like to use emacs-nox, but this mode gives me no quick clues about breakpoints while using emacs without X.

Do you have any idea on how to make it clear using this mode, or maybe an alternative to fringe-mode (when not in x)?

**Comment by yyoncho** [comment]
Do you have markers for flycheck/flymake in the fringe? I am not very familiar with the differences between GUI/TUI. If you have flycheck/flymake markers we may use the same code to do the same. Alternatively, if there is no support for fringe we may highlight the line in "breakpoint" face. But before we continue, can you make sure that you have dap-ui-mode enabled?

**Comment by hacktivista** [comment]
Nope, flycheck does not display markers in the console, as `fringe-mode` is a GUI-only function. What flycheck does is actually applying an underline, bold and change the color of the non-conforming code. Here an image which explains it all.

![emacsnoxandgui](https://user-images.githubusercontent.com/5282749/68629703-82ee2380-04c3-11ea-9009-6b58daf3fbf9.png)

I don't know what you actually refer to when you say highlighting, but if it's highlighting as I do on the line where my cursor is (as in the image), I think that would be great :)

**Comment by yyoncho** [comment]
Actually, dap-mode already supports what you want:

```
(custom-set-faces
 '(dap-ui-pending-breakpoint-face ((t (:underline "dim gray"))))
 '(dap-ui-verified-breakpoint-face ((t (:underline "green")))))
```
