### ISSUE TITLE
Locals buffer keep refreshing and closes expanded variables

### ISSUE THREAD

**Issue by r-darwish** [emacs-lsp/dap-mode#153]
When using the locals buffer in Java, whenever I expand an object it's a matter of seconds until the buffer refreshes and everything becomes collapsed again, making it pretty impossible to look at expanded values.

**Comment by yyoncho** [comment]
This will be solved once we fix https://github.com/emacs-lsp/dap-mode/issues/85 . I am closing this issue, please use #85 for tracking.
