### ISSUE TITLE
Can't debug Java applications with no Main Class

### ISSUE THREAD

**Issue by iocanel** [emacs-lsp/dap-mode#160]
Some java frameworks work without a main class.
If I start such a framework with debug options and then call from within emacs `dap-java-debug` I expect to be able to select the remote port that I want the debuger to attach to.
Instead I get an error message that there is no Main Class.

**Comment by yyoncho** [comment]
Have you tried `M-x dap-debug` and then select `Java Attach` ?

**Comment by iocanel** [comment]
Yeah, this works fine for me.
I am closing the issue.
