### ISSUE TITLE
Support paths that contain spaces

### ISSUE THREAD

**Issue by rynoV** [emacs-lsp/dap-mode#164]
If there is a space in the full path to a python file the code that creates the debug command doesn't currently recognize this and just puts the full path without wrapping it in quotes.
I fixed this in my local version by putting quotes around the right `%s`:
https://github.com/emacs-lsp/dap-mode/blob/4e25c8334f2ace87275f86b11f0ed969c2f20def/dap-python.el#L78
but this is obviously just a temporary fix and I don't have the skill with elisp to create a more permanent one.

**Comment by yyoncho** [comment]
Isn't it possible to quote the actual value to the python binary like that `(setq python-executable "\"path with spaces\"")`?

**Comment by rynoV** [comment]
I don't have any issues with the actual python binary although maybe it should be quoted as well. I'm talking about
https://github.com/emacs-lsp/dap-mode/blob/4e25c8334f2ace87275f86b11f0ed969c2f20def/dap-python.el#L83
and the lines around it. Could we wrap each line that could give a path with a `(shell-quote-args )` or something like that?

**Comment by yyoncho** [comment]
Sorry for the delayed response.

> Could we wrap each line that could give a path with a (shell-quote-argument ) or something like that? 

Make sense, would you mind opening a PR?
