### ISSUE TITLE
Configuring dap-mode & dap-ui-mode question

### ISSUE THREAD

**Issue by rileyrg** [emacs-lsp/dap-mode#168]
Firstly thank you so much for this wonderful development. This and lsp mode have bought Emacs back as a viable development environment for large projects on a par with the JetBrains IDE. 

Not so much an issue as a request for clarification: How does one configure this properly, for PHP in my instance, so that dap-mode and dap-ui modes are on when debugging but turn off when I quit the debugger? Currently when I "q" from the hydra, the UI mode highlights are still in my php buffer, even if I eval dap-ui-mode to disable it. 

Your provided config lines I have simply added  to my php-mode hook but I think they should probably be somewhere else along with corresponding code to turn them off when I quit the debugger. 

```
     (use-package php-mode
       ;;
       :hook (
              (php-mode . (lambda () 
                            ;; (make-local-variable 'eldoc-documentation-function)
                            ;; (setq eldoc-documentation-function
                            ;;       'phpactor-hover)
                            (dap-mode 1)
                            (dap-ui-mode 1)
                            ;; enables mouse hover support
                            (dap-tooltip-mode 1)
                            ;; use tooltips for mouse hover
                            ;; if it is not enabled `dap-mode' will use the minibuffer.
                            (tooltip-mode 1)
                            (set (make-local-variable 'company-backends)
                                 '(;; list of backends
                                   company-phpactor
                                   company-files))
                            (lsp)
                            )))

```

Many thanks for any further info.

**Comment by yyoncho** [comment]
> the UI mode highlights are still in my php buffe

Can you provide a screenshot?

**Comment by rileyrg** [comment]
OK, put this down to user error. I had confused Q and q as well as having multiple sessions running. Sorry for the noise. An excellent addition. One slight improvement might be somehow seeding google with it, I had all but given up on trying to debug php in emacs.  In fact maybe "debugging php in emacs" here will do just that. I shall close this.
