### ISSUE TITLE
How to interact with a python program on CLI ?

### ISSUE THREAD

**Issue by MicLennartz** [emacs-lsp/dap-mode#169]
Hi,
I'm trying to test lsp-mode and dap-mode for Python programming. Looks very good so far, but I'm not able to find a way to interact with my program, when running the debugger. 

The prompt for some user input is shown in the dap-server-log. But this is read-only and I even can't give my input, when I switch the buffer to read-write.

As this is a very fundamental requirement, I guess that I just had bad luck to find the guide. Any suggestion would be very appreciated.

Br,
Michael

**Comment by yyoncho** [comment]
`M-x dap-ui-repl`?

**Comment by yyoncho** [comment]
Use ... 
```
(setq dap-python-terminal "xterm -e ")
```

... after https://github.com/emacs-lsp/dap-mode/commit/96aadd4c95b7f2e4a3b73080ed85dbe3ae003eab

**Comment by MicLennartz** [comment]
The dap-ui-repl sounds like a good option. But that only works, when I hit a breakpoint -> no interaction with a running program.

I'm still digging in the dark and it would be great, if you can lead me to some quick start guide on how to start a dap debugging session properly, where I can handle the debugger and also the interactivity with the running program.

(I should mention, that currently I'm a beginner in Python, as well as not yet a pro in emacs)

**Comment by yyoncho** [comment]
@MicLennartz if you do this:
```
(setq dap-python-terminal "xterm -e ")
```

the debug session will start in a terminal which has stdin. Have you tried that?

**Comment by yyoncho** [comment]
This will work if you upgrade to latest dap-mode.

**Comment by MicLennartz** [comment]
As I'm on a mac, and use iTerm, I attempted this
`(setq dap-python-terminal "iterm ")`

It starts a new iTerm2 tab with the python debugging process. But in emacs it fails to connect to the client process. I guess, it could be a timeout problem, as iTerm and the python process takes 2-3 seconds, and the error message in Emacs is pushed earlier.

**Comment by yyoncho** [comment]
You should find the iTerm argument that means execute a command.

**Comment by MicLennartz** [comment]
Yeah, that's working: The debugger is running in iTerm already. So far so good. But emacs don't connect to it. Looks like it's timing out, already before the process in iTerm is launched.

**Comment by yyoncho** [comment]
Ah, I see, ATM there is no setting for increasing the timeout - it is 100x0.02. Can you update it in your source so we can make sure this is the case before exposing the settings. You could do that by doing: `M-x find-library RET dap-mode RET` and then find line   

>  (when wait-for-port (dap--wait-for-port host port))

and change it to

>     (when wait-for-port (dap--wait-for-port host port 1000 0.02))

**Comment by MicLennartz** [comment]
Yes, that's working as it should. (I've chosen 100x0,2) 
Would be great, if you could expose this as a setting in one of the next versions

**Comment by yyoncho** [comment]
Pushed https://github.com/emacs-lsp/dap-mode/commit/e2efcc3cb49bc1ef45341bd5581a3222704b9637 with 1000/0.02 which is the same as 100x0.2 but it will result in dap-mode being more responsive. 

Let me know if you run into any issue.

**Comment by etern** [comment]
On remote ssh session, there is no X-window, use "xterm -e “ raise an error: `xterm: Xt error: Can't open display: xterm: DISPLAY is not set`. Is there a way to work out?

**Comment by yyoncho** [comment]
@etern I am working on an integration which will allow using vterm in emacs for that purpose and for making compilation faster.

**Comment by jtpavlock** [comment]
> @etern I am working on an integration which will allow using vterm in emacs for that purpose and for making compilation faster.

Using vterm for user input for debugging would be awesome!

**Comment by simurgh9** [comment]
I just tried running `xterm -e python3` which works and then set `(setq dap-python-terminal "xterm -e ")` which made no difference.

**Comment by trentsteel777** [comment]
I tried:
(setq dap-python-terminal "vterm")

but no luck.
