### ISSUE TITLE
dap-mode hangs after several debug sessions with Microsoft Python Langauge Server

### ISSUE THREAD

**Issue by prittjam** [emacs-lsp/dap-mode#171]
After 3 or 4 debugging sessions, emacs just hangs and must be killed. I use the Microsoft Python Language Server. 

I am running this command to start the debug session. 

  (interactive)                                                                 
  (dap-debug    (list :type "python"                                            
                      :args ""                                                  
                      :cwd nil                                                  
                      :target-module nil                                        
                      :request "launch"                                         
                      :name "Python :: Run Configuration")))

**Comment by yyoncho** [comment]
What happens when pressing C-g? If it works can you provide the callstack after doing M-x toggle-debug-on-error?

**Comment by prittjam** [comment]
C-g is working but i did use toggle-debug-on-error, but no call stack appears. How can I get the call stack?

**Comment by yyoncho** [comment]
Sorry, it is toggle-debug-on-quit

**Comment by prittjam** [comment]
Debugger entered--Lisp error: (quit)
  make-network-process(:name "*connection-test*" :buffer nil :host "localhost" :service 32000 :nowait nil :tls-parameters nil)
  open-network-stream("*connection-test*" nil "localhost" 32000 :type plain)
  dap--find-available-port("localhost" 32000)
  dap-python--populate-start-file-args((:type "python" :args "" :cwd nil :target-module nil :request "launch" :name "Python :: Run Configuration"))
  dap-debug((:type "python" :args "" :cwd nil :target-module nil :request "launch" :name "Python :: Run Configuration"))
  my/debug-directly()
  funcall-interactively(my/debug-directly)
  call-interactively(my/debug-directly nil nil)
  command-execute(my/debug-directly)

**Comment by prittjam** [comment]
it just hangs here while trying to start the debug sesssion.

**Comment by yyoncho** [comment]
Can you look for err buffer corresponding to that session? I guess for some reason the python application fails to start and the connect code hangs(it actually waits 20 second before timeout).

**Comment by prittjam** [comment]
Yes, where can I find the err buffer?

**Comment by prittjam** [comment]
It's repeatable; it always happens after the 4th time; I am running the latest dap-mode, lsp-mode, etc...

**Comment by yyoncho** [comment]
That's odd.

The buffer will be called something like: `*Python :: Run Configuration out*` My guess is that the port was not released.

**Comment by prittjam** [comment]
*Python :: Run Configuration out*  is empty

**Comment by yyoncho** [comment]
Test after you eval this:

```
(defun dap-python--populate-start-file-args (conf)
  "Populate CONF with the required arguments."
  (let* ((host "localhost")
         (debug-port (dap--find-available-port host (incf dap-python-default-debug-port)))
         (python-executable (dap-python--pyenv-executable-find dap-python-executable))
         (python-args (or (plist-get conf :args) ""))
         (program (or (plist-get conf :target-module)
                      (plist-get conf :program)
                      (buffer-file-name)))
         (module (plist-get conf :module)))

    (dap--put-if-absent conf :program-to-start
                        (format "%s%s -m ptvsd --wait --host %s --port %s %s %s %s"
                                (or dap-python-terminal "")
                                (shell-quote-argument python-executable)
                                host
                                debug-port
                                (if module (concat "-m " (shell-quote-argument module)) "")
                                (shell-quote-argument program)
                                python-args))
    (plist-put conf :program program)
    (plist-put conf :debugServer debug-port)
    (plist-put conf :port debug-port)
    (plist-put conf :wait-for-port t)
    (plist-put conf :hostName host)
    (plist-put conf :host host)
    conf))
```

**Comment by prittjam** [comment]
In fact there are several, Python :: Run Configuration out<N> where N in 0..2; I suspect this is the problem

**Comment by prittjam** [comment]
I put it in my init.el, restarted and tested. The same result. after 3 sessions it just hangs and waits.

**Comment by prittjam** [comment]
Ok, I ran eval-defun and tried it, returns

Symbol's function definition is void: incf

**Comment by yyoncho** [comment]
Sorry, add (require 'cl) or change to cl-incf

**Comment by prittjam** [comment]
now it hangs as before

**Comment by prittjam** [comment]
hold on.. double checking

**Comment by yyoncho** [comment]
can you do post the new callstack?

**Comment by prittjam** [comment]
it seems to work ok in this session.

**Comment by prittjam** [comment]
I just did 24 restarts and it is working with your evaluated code you provided; it seems. I will check again.

**Comment by prittjam** [comment]
yes, I started from scratch and it is now working with your added code. verified. you still want a callstack?

**Comment by yyoncho** [comment]
No, if it works then it is fine. I will try to make the code more robust.

**Comment by prittjam** [comment]
it works now; not sure what magic you did, but I was able to restart the session many times, which is what I like to do for interactive debugging.

**Comment by prittjam** [comment]
there is some problem with add and deleting breakpoints, error in process filter, but I am still able to proceed.

**Comment by yyoncho** [comment]
You probably have a hanging session - you may force cleanup with `dap-delete-all-sessions`
