### ISSUE TITLE
lsp file watching settings : lsp has started looking at files outside of the project.

### ISSUE THREAD

**Issue by rileyrg** [emacs-lsp/dap-mode#174]
lsp-mode           20191218.610  dependency            LSP mode

At some stage in one of the last updates, lsp file watch has started to look at files outside of my project. I get this after opening my php file following a significant delay (see pic), I realise I can turn file watch off, and also filter what is monitored but this seems like a possible bug. home/rgr being my home directory while the opened file is in a development project subdirectory (.git and .projectile there).

![Screenshot from 2019-12-19 12-12-04](https://user-images.githubusercontent.com/362891/71169250-cbce9000-2258-11ea-984b-e852cc0d6da6.png)

**Comment by yyoncho** [comment]
Probably you have added your home folder as a workspace folder. Use lsp-workspace-folders-remove to fix that.

**Comment by rileyrg** [comment]
Thanks for the prompt feedback.

I haven't configured any folder list. Certainly, there is nothing relevant in my custom.el or package configuration.

But adding (lsp-workspace-folders-remove "/home/rgr") has solved the issue. I'm assuming this doesn't mean it now ignores all sub folders of my home directory? And there is no list variable I can customise?

**Comment by yyoncho** [comment]
> I'm assuming this doesn't mean it now ignores all sub folders of my home directory?

Yes.

> And there is no list variable I can customise?

The list of workspace folders can be accessed like that via `(lsp-session-folders (lsp-session))`
