### ISSUE TITLE
dap-mode variable inspect : how to see the actual values of an object/array?

### ISSUE THREAD

**Issue by rileyrg** [emacs-lsp/dap-mode#176]
If I have my cursor on $_SERVER for example and I "eis" via the hydra (dap-ui-inspect-thing-at-point) ir replies with  "array(27)" 

![Screenshot from 2019-12-23 23-11-49](https://user-images.githubusercontent.com/362891/71382763-a4215400-25d9-11ea-9393-83bee1dfc602.png)

Am I missing something on how I can actually display/expand the contents? Yes, I can see it from the dap-ui-locals window but  I would love to be able to quickly view an array/object under the cursor without needing to find it in the locals window.

**Comment by rileyrg** [comment]
Sigh, I dont know why but my mouse on my laptop is very finicky in these trees. So I see now I can expand it.  Anyway, I need to focus on the spyglass icon and hit enter - maybe enter on the "array" text could expand too? (I would also like to see the variable name eg $_SERVER (array[27]))

**Comment by yyoncho** [comment]
I am planning to rewrite these controls and use treemacs to render the trees (it will work better). What you are suggesting to have the original variable in the view like watch window, right?

**Comment by rileyrg** [comment]
The variable name in the inspect window after "inspect at region" or "eval at region". 
eg currently I see
[spyglass icon] array[28]

nicer if possible would be
[icon] arrayName[28}
AND to auto expand it when specifically inspected/evaluated (defcustom  option).

Also pressing enter anywhere on the line, not just the icon, would expand/close the tree - but good to hear you're planning to overhaul the tree. I dont know what tree mechanics "treemacs" uses but it's pretty cool.
