### ISSUE TITLE
dap-mode docker mapping

### ISSUE THREAD

**Issue by Sasanidas** [emacs-lsp/dap-mode#177]
Hello, I'm trying to use dap-debug with felixfbecker/vscode-php-debug, but i cant pass the first index stop. I tried to "hack it" by putting my project in the same directory, ("/var/www/html").
And it worked, so I'm assuming  that is a mapping problem, this is my configuration:
```elisp
(require 'dap-php)
(dap-php-setup)
(dap-register-debug-template "My Php Debug"
  (list :type "php"
        :cwd nil
        :request "launch"
        :name "Php Debug"
        :args '("--server=4711")
	:pathMappings (ht ("/var/www/html" "/local/src"))
        :sourceMaps t))
```
Thank you!

**Comment by yyoncho** [comment]
> but i cant pass the first index stop. 

Can you elaborate?

**Comment by Sasanidas** [comment]
> > but i cant pass the first index stop.
> 
> Can you elaborate?

Sure! sorry, well the thing is, when I use 
```elisp
 :stopOnEntry t
```
Dap correctly stop in the index file, but then cannot find the next file in the path, so when I put the local file in the same route as the machine, "it works", but the mapping options is not taken correctly.
Thank you!

**Comment by yyoncho** [comment]
@Sasanidas sorry, I do not use PHP and even configuring the debugger is hard for me. 

CC @quan-na can you take a look?
@Sasanidas  See https://github.com/emacs-lsp/dap-mode/issues/123

**Comment by yyoncho** [comment]
CC @rileyrg who might have a clue as well.

**Comment by rileyrg** [comment]
I can offer very little other than "works for me out of the box" . I use intelephense. I havent had to use any mappings as everything is in the one "project" (.git and .projectile are there).

Does lsp allow you to navigate to the other files? see:
```

(define-key lsp-ui-mode-map [remap xref-find-definitions] #'lsp-ui-peek-find-definitions)
(define-key lsp-ui-mode-map [remap xref-find-references] #'lsp-ui-peek-find-references)
 
```

**Comment by Sasanidas** [comment]
> I can offer very little other than "works for me out of the box" . I use intelephense. I havent had to use any mappings as everything is in the one "project" (.git and .projectile are there).
> 
> Does lsp allow you to navigate to the other files? see:
> 
> https://github.com/rileyrg/Emacs-Customisations#language-server-protocol-lsp
> 
> ```
> 
> (define-key lsp-ui-mode-map [remap xref-find-definitions] #'lsp-ui-peek-find-definitions)
> (define-key lsp-ui-mode-map [remap xref-find-references] #'lsp-ui-peek-find-references)
>  
> ```

Ok seems like this works! this is the final config:
```elisp
(dap-register-debug-template "PHP"
  (list :type "php"
        :cwd nil
        :request "launch"
        :name "Php Debug"
        :args '("--server=4711")
	:pathMappings (ht ((docker-container-path) (projectile-project-root (buffer-file-name))))
        :sourceMaps t))
```
Thanks!

**Comment by zilti** [comment]
It would be nice if you would add this to the documentation. I had a similar problem - Application runs on FreeBSD in a Vagrantbox - and also needed to find out how to do pathMappings.
