### ISSUE TITLE
DAP Session tree corrupting source files. 

### ISSUE THREAD

**Issue by rileyrg** [emacs-lsp/dap-mode#179]
This might seem somewhat orchestrated but its the only way I can reliably reproduce the issue which has been incredibly frustrating as I had to keep reinstalling my core symfony source files. There is some focus issue where the update to the sessions tree updates in the wrong window corrupting the other file. Here is how to reproduce in my set up:-

Start a debug on entry debug session.
Step a line to two.
open the Sessions tree from the hydra (sS)
step into a (php in this case) "require".
set focus to the session tree.
expand the running subtree.
select the current line in the stack to set focus back to the source.
now "step out".

In my case I end up with this:-

![Screenshot from 2019-12-26 10-36-43](https://user-images.githubusercontent.com/362891/71470354-2a04f100-27cc-11ea-9c37-23f039aea529.png)

Note the "running" subtree embedded into the source code. Similar has been happening loads of times but this is the only way I can faithfully reproduce.

I have a feeling that a fix here will greatly improve dap as there are currently a lot of "window-live" type errors occurring when sessions crash or complete and trees are open - hopefully related.

Small aside: a default "kill session" keybinding on the session tree would be nice too.

**Comment by yyoncho** [comment]
All these will be addressed as part of treemacs migration, I already have some code for it.

**Comment by rileyrg** [comment]
Wonderful. If you want to pass me any betas happy to try it out.

**Comment by yyoncho** [comment]
Check this out - https://github.com/emacs-lsp/dap-mode/tree/sources - it fixes a lot of the issues you have reported.

**Comment by rileyrg** [comment]
Good to hear, but I updated this morning and I'm afraid to say I'm seeing the same issues.

> error in process filter: Wrong type argument: window-live-p, nil

Easy to reproduce: run the debugger, stop at a breakpoint, show the hydra,  simpy "eis" (inspect thing at point) and we're lost. (php).

Also, I am getting this sporadically

> error in process filter: lsp-ui--hide-doc-frame-on-window-change: Wrong type argument: window-live-p, nil

I shall try to remake all from scratch to ensure I don't have an issue with the compilation of melpa packages and try to reproduce the second issue with some more clarity.

**Comment by rileyrg** [comment]
just a note that I see my MELPA one is from 4-1-2020.

**Comment by yyoncho** [comment]
The fixes are in separate branch and not pushed to master.

> error in process filter: lsp-ui--hide-doc-frame-on-window-change: Wrong type argument: window-live-p, nil

This one is yet to be fixed.

**Comment by rileyrg** [comment]
ah ok. I Just saw that this minute. I will need to a while to try and deal with that as I havent tried cloning overriding melpa.

**Comment by yyoncho** [comment]
Also, it requires you to have the latest version of lsp-treemacs.

**Comment by rileyrg** [comment]
My treemacs is from 29-12 which is the latest. I cloned the link https://github.com/emacs-lsp/dap-mode/tree/sources you gave me. I don't see that in "branches" though so I'm not sure of the mechanisms used for this branch. I deleted my melpa dap-mode and added the clone to my elisp path and forced a recompile. Its definitely picked up from the git clone of https://github.com/emacs-lsp/dap-mode/tree/sources. 

Stepping through works fine.

still a hydra "eir", or "eis" completely breaks the debugging session I'm afraid.

The error messages at this point are:

> error in process filter: lsp-ui--hide-doc-frame-on-window-change: Wrong type argument: window-live-p, nil
> error in process filter: Wrong type argument: window-live-p, nil
> 

doing an sS and trying to regain control after doesn't work but there doesn't seem to be any more issue the session tree infecting other buffers. I'll keep an eye on that.


(There have been some changes to structure? I need to specifically suck in dap-mouse now for tooltips.)

**Comment by yyoncho** [comment]
dap-ui-inspect* commands are removed. Use dap-ui-expressions and dap-ui-expressions-add instead. I will try to fix the  window-live-p related bug too.

**Comment by rileyrg** [comment]
Hang on, I just remembered: this might help. Its to do with another bug I raised. The eir bug s caused because the output window isn't open. If I dap-go-to-output-buffer first it works. I have the output buffer turned off as a default,.

              

Backtrace:

> Debugger entered--Lisp error: (wrong-type-argument window-live-p nil)
>   #<subr select-window>(nil nil)
>   lsp-ui--hide-doc-frame-on-window-change(#<subr select-window> nil)
>   apply(lsp-ui--hide-doc-frame-on-window-change #<subr select-window> nil)
>   select-window(nil)
>   dap-ui--show-buffer(#<buffer *dap-ui-inspect*>)
>   dap-ui--inspect-value(#s(dap--debug-session :name "Php SOE Debug" :last-id 12 :proc #<process Php SOE Debug> :response-handlers #<hash-table eql 1/65 0x1580906e6a2d> :parser #s(dap--parser :waiting-for-response nil :response-result nil :headers nil :body nil :reading-body nil :body-length nil :body-received nil :leftovers "") :output-buffer #<buffer *Php SOE Debug out*> :thread-id 1 :workspace nil :threads (#<hash-table equal 2/65 0x15809055e4a5>) :thread-states #<hash-table eql 1/65 0x1580906e6b69> :active-frame-id nil :active-frame #<hash-table equal 5/65 0x1580905c0be9> :cursor-marker nil :session-breakpoints #<hash-table equal 0/65 0x1580906e6b89> :state running :breakpoints #<hash-table equal 4/65 0x15809073442d> :thread-stack-frames #<hash-table eql 1/65 0x158090237b39> :launch-args (:type "php" :cwd "/home/rgr/Dropbox/homefiles/development/Symfony/kn..." :request "launch" :name "Php SOE Debug" :stopOnEntry t :sourceMaps t :dap-server-path ("node" "/home/rgr/.emacs.d/.extension/vscode/felixfbecker....")) :initialize-result #<hash-table equal 6/65 0x1580906c6a5d> :error-message nil :loaded-sources nil) #<hash-table equal 6/65 0x1580905c5779>)
>   apply(dap-ui--inspect-value (#s(dap--debug-session :name "Php SOE Debug" :last-id 12 :proc #<process Php SOE Debug> :response-handlers #<hash-table eql 1/65 0x1580906e6a2d> :parser #s(dap--parser :waiting-for-response nil :response-result nil :headers nil :body nil :reading-body nil :body-length nil :body-received nil :leftovers "") :output-buffer #<buffer *Php SOE Debug out*> :thread-id 1 :workspace nil :threads (#<hash-table equal 2/65 0x15809055e4a5>) :thread-states #<hash-table eql 1/65 0x1580906e6b69> :active-frame-id nil :active-frame #<hash-table equal 5/65 0x1580905c0be9> :cursor-marker nil :session-breakpoints #<hash-table equal 0/65 0x1580906e6b89> :state running :breakpoints #<hash-table equal 4/65 0x15809073442d> :thread-stack-frames #<hash-table eql 1/65 0x158090237b39> :launch-args (:type "php" :cwd "/home/rgr/Dropbox/homefiles/development/Symfony/kn..." :request "launch" :name "Php SOE Debug" :stopOnEntry t :sourceMaps t :dap-server-path ("node" "/home/rgr/.emacs.d/.extension/vscode/felixfbecker....")) :initialize-result #<hash-table equal 6/65 0x1580906c6a5d> :error-message nil :loaded-sources nil) #<hash-table equal 6/65 0x1580905c5779>))
>   #f(compiled-function (&rest args2) #<bytecode 0x158090719581>)(#<hash-table equal 6/65 0x1580905c5779>)
>   #f(compiled-function (input0) #<bytecode 0x158090719599>)(#<hash-table equal 6/65 0x1580905c5779>)
>   #f(compiled-function (m) #<bytecode 0x1580906689b5>)("{\"seq\":16,\"type\":\"response\",\"request_seq\":12,\"comm...")
>   mapc(#f(compiled-function (m) #<bytecode 0x1580906689b5>) ("{\"seq\":16,\"type\":\"response\",\"request_seq\":12,\"comm..."))
>   #f(compiled-function (_ msg) #<bytecode 0x15809073444d>)(#<process Php SOE Debug> "Content-Length: 134\15\n\15\n{\"seq\":16,\"type\":\"response\"...")
>

**Comment by yyoncho** [comment]
Can you try now with the latest version of the sources branch?

**Comment by rileyrg** [comment]
On github I can see you have made some changes, I cloned from the link above. git pull isnt pulling anything. Any idea what I'm doing wrong? Is the link an actual branch or something else?

**Comment by rileyrg** [comment]
I owe you an apology, I hadn't realised that when I cloned from that link it was a whole repo clone and not just for that branch. 

Anyway.... "source" now checked out. I need to investigate this 

> dap-ui-expressions

 thing as there is nothing in the hydra now. What I can say is that the Treemacs "list locals pane" (that needs changing)  doesn't work  with the enter key but does with the mouse

"Treemacs no ret action defined"

That said it is HUGELY better. Nice one. I'll have a look at inspect functions and get back to you.

**Comment by yyoncho** [comment]
> Mouse hover over those would be nice.

I will add these(not sure if it will be as part of the first iteration).

> "Treemacs no ret action defined"

Ret = Double click = Select object - it is defined if it makes sense - e. g. in sessions to select a thread, stackframe, etc.

TAB = Single click = Toggle

**Comment by rileyrg** [comment]
agreed re:tab. Nice one. FYI S-Tab : funcall-interactively: Wrong type argument: arrayp, nil

but to use defo need the resize of the locals pane - I can barely see any values on  laptop

looking good.
