### ISSUE TITLE
dap-java-debug not working since vscode-java-debug v0.21.0 

### ISSUE THREAD

**Issue by clement-buchart** [emacs-lsp/dap-mode#182]
Hello,

I've been using extensively lsp-mode and dap-mode for a few month with success, thank you for you work on this 2 great projects.

Today I ran lsp-java-update-server, and I haven't been to start a java launch debug session since.
Here is the error I am getting : 
`com.microsoft.java.debug.core.DebugException: Failed to launch debuggee in terminal. Reason: Failed to launch debuggee in terminal. Reason: java.util.concurrent.TimeoutException: timeout`

A quick search revealed that it might be related to https://github.com/microsoft/vscode-java-debug/issues/651#issuecomment-526984315

As suggested I added `(dap--put-if-absent conf :console "internalConsole")` in `dap-java--populate-launch-args`, and it is working fine again.

Are you aware of this change in default is vscode-java-debug ?
Do you want me to propose a PR with this change, or would you prefer to adapt dap-mode to this new vscode default ? (from my understanding, it allows us to have a stdin on the debugger process, i don't know if dap-mode would benefit from that)

Cheers

**Comment by yyoncho** [comment]
I wasn't aware of that, I bumped the version of the debug adapter as part of implementing serVariable functionality.  A PR would be great since I do not have an access to PC right now. We should also implement the stdin functionality NAT some point. Thank you.

**Comment by clement-buchart** [comment]
Submitted a PR.

Another way would be to set the user setting `java.debug.settings.console`. Is there a way to do set user settings for vscode-java-debug that you would prefer ?

**Comment by yyoncho** [comment]
> Submitted a PR.
> 
> Another way would be to set the user setting `java.debug.settings.console`. Is there a way to do set user settings for vscode-java-debug that you would prefer ?

Yes, you could do that using lsp-register-custom-settings. Check lsp-java.el for example. There are several settings for dap-java debug adapter which are not exposed. There is a script in lsp-mode project lsp-generate-settings which can be used to generate the code from package.json file.
