### ISSUE TITLE
dap-java breakpoint on exception

### ISSUE THREAD

**Issue by alendit** [emacs-lsp/dap-mode#185]
Is there an option to set breakpoint to catch exceptions, like in IDEA or VSCode?

**Comment by yyoncho** [comment]
The protocol supports that feature but I haven't implemented it. I am planning to work on fixing missing pieces in dap-mode next few weeks.

**Comment by yyoncho** [comment]
I am working on that - https://github.com/emacs-lsp/dap-mode/tree/sources

**Comment by yyoncho** [comment]
How it works:

![exceptions](https://user-images.githubusercontent.com/13259670/72394252-38e12280-373e-11ea-8d16-3763e86a5cf6.gif)

**Comment by zoechi** [comment]
Is there a variable/function that allows to clear/set that?
(for startup setting or key binding?)

**Comment by yyoncho** [comment]
@zoechi it is stored in dap-exception-breakpoints, you may set it once trough the UI and then inspect what is the correct format.
