### ISSUE TITLE
dap list sessions error

### ISSUE THREAD

**Issue by rileyrg** [emacs-lsp/dap-mode#187]
dap-mode           20200111.644  

When debugging, sS from the hydra to list sessions results in this error:

( I toggled debug on to get a stack trace but for some reason it didnt trigger)

> Wrong type argument: listp, #s(dap--debug-session "Php SOE Debug" 12 #<process Php SOE Debug> #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data ()) #s(dap--parser nil nil nil nil nil nil nil "") #<buffer *Php SOE Debug out*> 1 nil (#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("id" 1 "name" "Request 1 (12:43:36 PM)"))) #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data (1 nil)) nil #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("id" 3 "name" "{main}" "source" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("name" "35e418c61587bad89fc1c91da58cce25de7591f0-router.php" "path" "/home/rgr/Dropbox/homefiles/DotFiles/.symfony/php/35e418c61587bad89fc1c91da58cce25de7591f0-router.php")) "line" 17 "column" 1)) nil #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ()) running #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("/home/rgr/Dropbox/homefiles/development/php/index.php" (#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("verified" t "line" 2))) "/home/rgr/Dropbox/homefiles/development/Symfony/knp/02-Symfony4-Fundamentals/the_spacebar/vendor/knplabs/knp-markdown-bundle/DependencyInjection/KnpMarkdownExtension.php" (#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("verified" t "line" 29))) "/home/rgr/Dropbox/homefiles/development/Symfony/knp/02-Symfony4-Fundamentals/the_spacebar/src/Controller/ArticleController.php" (#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("verified" t "line" 55))))) #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data (1 (#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("id" 3 "name" "{main}" "source" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("name" "35e418c61587bad89fc1c91da58cce25de7591f0-router.php" "path" "/home/rgr/Dropbox/homefiles/DotFiles/.symfony/php/35e418c61587bad89fc1c91da58cce25de7591f0-router.php")) "line" 17 "column" 1))))) (:type "php" :cwd "/home/rgr/Dropbox/homefiles/development/Symfony/knp/02-Symfony4-Fundamentals/the_spacebar" :request "launch" :name "Php SOE Debug" :stopOnEntry t :sourceMaps t :dap-server-path ("node" "/home/rgr/.emacs.d/.extension/vscode/felixfbecker.php-debug/extension/out/phpDebug.js")) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("seq" 1 "type" "response" "request_seq" 1 "command" "initialize" "success" t "body" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("supportsConfigurationDoneRequest" t "supportsEvaluateForHovers" nil "supportsConditionalBreakpoints" t "supportsFunctionBreakpoints" t "exceptionBreakpointFilters" (#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("filter" "Notice" "label" "Notices")) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("filter" "Warning" "label" "Warnings")) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("filter" "Error" "label" "Errors")) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("filter" "Exception" "label" "Exceptions")) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("filter" "*" "label" "Everything" "default" t))))))) nil nil)

**Comment by yyoncho** [comment]
I am unable to reproduce it and with that much info it is impossible to find out the rootcause. Can you confirm that it reproduces on your side with these steps and provide the callstack?

**Comment by rileyrg** [comment]
I'm unable to reproduce today too. I''m debugging today so if it doesn't come up I shall close.
