### ISSUE TITLE
Recent change to dap--find-available-port broke dap-java-debug-xxx

### ISSUE THREAD

**Issue by adhilton** [emacs-lsp/dap-mode#191]
There seems to have been a recent change to dap--find-available-port where it now takes 0 parameters instead of 2.  However,  other parts of the code still assume this has two parameters, e.g. dap-java-debug-test-method  and dap-java-debug-test-class have:

(interactive (list (dap--find-available-port "localhost" dap-java-compile-port)))

So any attempt to call these interactively results in an error message and the debugger not starting.

**Comment by fgabolde** [comment]
This still doesn't work for me unfortunately.

`(dap--find-available-port)` seems to always return 0.

Relevant log file (directory and class names anonymized):

```
-*- mode: dap-server-log; default-directory: "~/work/foo/" -*-
Debug Adapter started at Wed Feb 19 11:25:05

java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=0 -jar /home/fgabolde/.emacs.d/eclipse.jdt.ls/test-runner/junit-platform-console-standalone.jar -cp $JUNIT_CLASS_PATH -m foo.SomeClassTest#someTestMethod
Listening for transport dt_socket at address: 36065
```

I eventually get this in the `*warnings*` buffer:

```
Warning (emacs): Initialize request failed: Failed to attach to remote debuggee VM. Reason: java.net.ConnectException: Connection refused (Connection refused)
```

If I "patch" `dap--find-available-port` to make it always return the same value, `dap-java-debug-test-method` works again.

**Comment by adhilton** [comment]
Are you using Emacs 26 or an older version of Emacs?  I had a student using Emacs 25 who had a problem with the same symptoms as you.

**Comment by yyoncho** [comment]
```
(let ((process (make-network-process :name " *dap test-connection*"
                                       :family 'ipv4
                                       :service 0
                                       :server 't)))
    (prog1 (process-contact process :service)
      (delete-process process)))
```

This piece of code is supposed to return a random port. `:service 0` means - bind to random port. Apart from emacs version what OS do you use?

**Comment by fgabolde** [comment]
> Are you using Emacs 26 or an older version of Emacs? I had a student using Emacs 25 who had a problem with the same symptoms as you.

> Apart from emacs version what OS do you use?

I'm running Ubuntu 18.04 (LTS) and Emacs 25 since that's what's packaged in their repositories.
