### ISSUE TITLE
elisp help wanted: calling dap-debug

### ISSUE THREAD

**Issue by rileyrg** [emacs-lsp/dap-mode#192]
I had a quick look at dap-debug and alas my elisp is not up to working out how to call dap debug with a named debug profile already set. Can someone help please? eg just run dap-debug with the "stop on entry" profile.

**Comment by yyoncho** [comment]
Use:

``` elisp
(dap-debug
 (list :type "java"
       :request "attach"
       :hostName "localhost"
       :port 1000))
```

**Comment by rileyrg** [comment]
Just as a learning process I came up with this to reuse the run config:-

     (defun rgr/debug-php()
       (interactive)
       (dap-debug (cdr (car (cdr dap-debug-template-configurations)))))
