### ISSUE TITLE
dap-java: Attach to debuggee VM when it ready

### ISSUE THREAD

**Issue by ctrl2wei** [emacs-lsp/dap-mode#194]
When I first call `dap-debug` and select `Java Run Configuration (compile/attach)` everything works well. But if I try it again, errors will occur.
```
Warning (emacs): Initialize request failed: Failed to attach to remote debuggee VM. Reason: java.net.ConnectException: Connection refused (Connection refused)
```
when I put `(sleep-for 3)` under the code, no matter how many times it will success.

https://github.com/emacs-lsp/dap-mode/blob/9d08eaf77d4aeb80880be85bc0591554314d0eb7/dap-mode.el#L1140-L1142

**Comment by js896** [comment]
Hi, same problem here, how did you fix it?

**Comment by yyoncho** [comment]
@js896 should be fixed in latest dap-mode
