### ISSUE TITLE
Feature Request : Support for scala in dap-mode

### ISSUE THREAD

**Issue by rchallapalli** [emacs-lsp/dap-mode#196]
Metals seems to be implementing the debug adapter protocol [1]. So it would be nice if the dap-mode provides support for scala.

[1] https://scalameta.org/metals/docs/editors/debug-adapter-protocol.html

**Comment by yyoncho** [comment]
CC @kurnevsky @dsyzling

**Comment by yyoncho** [comment]
I will take a look.

**Comment by yyoncho** [comment]
@olafurpg hi - I am trying to port this functionality to emacs but I am struggling to make the code lenses work in emacs(metals return []) - do you know what might be the reason? If not, is there a way to trace the client-server communication in vscode?

**Comment by olafurpg** [comment]
@yyoncho this is exciting! I'm not so familiar with the debugging support in Metals. The docs here are quite slim https://scalameta.org/metals/docs/editors/debug-adapter-protocol.html

cc/ @tgodzik do you know what's needed for Emacs to enable the test/run code lenses?

**Comment by yyoncho** [comment]
@olafurpg thank you - I figured it out - you have to specify experimental flags.

**Comment by olafurpg** [comment]
That makes sense. We avoid publishing those code lenses by default so that users don't get "run" buttons that don't work. We should improve our docs for integrating with the new DAP functionality.

**Comment by yyoncho** [comment]
I got it working:
![metals-debug](https://user-images.githubusercontent.com/13259670/73133438-38dffd00-4031-11ea-87f3-afa581f2d05f.gif)

**Comment by olafurpg** [comment]
@yyoncho That looks amazing 😍

**Comment by dsyzling** [comment]
@yyoncho That's looking really good - I've been out of the discussions on gitter for a while - but I saw some discussion of moving metals specific behaviour into a separate metals project - is this going ahead? I do think it makes sense to localise/group metals behaviour for lsp together from a cohesion point of view this makes sense, assuming any changes in lsp can equally be verified reasonably easily across the dependent projects.

**Comment by olafurpg** [comment]
If there is interest, we would be happy to host this repo under scalameta/metals-emacs (repo name up for debate) the same way we have scalameta/metals-vscode and scalameta/coc-metals (for vim)

**Comment by yyoncho** [comment]
@dsyzling it is entirely up to you(the scala users/devs) to decide. I will put the implementation of the debugger in lsp-mode using `declare-function`.

I will do that for lsp-java - it makes much more sense to have one project which references all deps that are needed (e. g. lsp-java will refer dap-mode + lsp-mode + lsp-treemacs) so users will have to install only one package and then they are good to go.
