### ISSUE TITLE
Go template with remote mode is not working

### ISSUE THREAD

**Issue by apmattil** [emacs-lsp/dap-mode#199]
I think the purpose of remote was to attach to local process.. it is broken as well.
I'll put PR that fixes remote issue.
I'll make new one about attach.

ps. anybody knows how take logs from goDebug.js ? or post here the output when attach template is used.

pss. I would like to resize locals window.. just could not implement it.

**Comment by apmattil** [comment]
I think we can now close this one.

**Comment by yyoncho** [comment]
You can close it too.

**Comment by apmattil** [comment]
ok.
