### ISSUE TITLE
Support for Eglot

### ISSUE THREAD

**Issue by jojojames** [emacs-lsp/dap-mode#2]
Might be cool to decouple dap-mode from lsp-mode and support https://github.com/joaotavora/eglot too!

Thanks for the package. :)

**Comment by yyoncho** [comment]
I will keep that in mind. Eglot does not work with Java JDT LS server so at this point there is no way to test it.

**Comment by yveszoundi** [comment]
It looks like Eglot now supports the Java JDT LS server, likely less options than `lsp-java` but maybe `dap-mode` could work with it.

**Comment by yyoncho** [comment]
@yveszoundi Given the fact I was promoted to member in lsp-mode, the fact that lsp-mode was redesigned and it now supports most(if not all) features of eglot out of the box(https://github.com/emacs-lsp/lsp-mode#whats-new-in-lspel) and much more, the fact that eglot is not interested in supporting extension methods brings this PR closer to rejecting or at least not addressing it in near future.

**Comment by yveszoundi** [comment]
Thanks @yyoncho, fair enough.

**Comment by yyoncho** [comment]
Closing as won't fix considering the amount of work in lsp-mode/dap-mode repo and the overhead that solving this PR will introduce.
