### ISSUE TITLE
debug python code many steps result in 'NoneType' object has no attribute 'xxx' error

### ISSUE THREAD

**Issue by wztdream** [emacs-lsp/dap-mode#204]
Hi,
dap-mode is great! thank you for your effort for such great tool.
Here is the issue:
I use dap-mode to debug python code, but if I debug many steps, press 'n' many times in debug mode, will results in an error called:
```
/home/wzt/anaconda3/envs/tf-gpu/bin/python -m ptvsd --wait --host localhost --port 37871  /home/wzt/research/code/learning/Reinforcement-learning/test.py 
Traceback (most recent call last):
  File "/home/wzt/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 1515, in pydevd_find_thread_by_id
    if thread_id == tid or thread_id.endswith('|' + tid):
AttributeError: 'NoneType' object has no attribute 'endswith'
```
It seems to me the thread of debug somehow becomes None, if debug too many steps. I have no further idea where is wrong, maybe due to some kind of overflow?
You can reproduce this error by any python code:
such as:
```
i = 0
while True:
    i += 1
    if i >= 100000:
        break
```
then press 'n' to debug step by step many times, in my case it should around 100 times, above error will occur.

**Comment by yyoncho** [comment]
I think that most probably dap-mode allows calling next before the thread has been stopped and we sent thread id nil. I will try it on my side and let you know.
