### ISSUE TITLE
dap-go: dlv test

### ISSUE THREAD

**Issue by fleimgruber** [emacs-lsp/dap-mode#205]
I am learning go with the help of https://exercism.io/ where each exercise comes with roughly these files (example for hello world):

```
go.mod
hello_world.go
hello_world_test.go
```

where I can successfully run `dlv test`.
When I run `(dap-debug)` from the `hello_world.go` buffer I get this error in `*Launch Unoptimized Debug Package out*`:

```
API server listening at: 127.0.0.1:6507
Can not debug non-main package
Process exiting with code: 1
```

So is there a possibility to tell dap-go to not assume a `main` package structure, but a test structure that `dlv test` understands?

**Comment by yyoncho** [comment]
@apmattil do you have a clue?

**Comment by apmattil** [comment]
do you have 'package main' and 'func main() {' at hello_world.go ?

try to put your code as following directory structure src/hello/cmd/hello_world.go and _test.go

if it does not work add (setq dap-print-io t) at dap-mode :confing and post here the message buffer.

**Comment by fleimgruber** [comment]
> do you have 'package main' and 'func main() {' at hello_world.go ?

No, the file `hello_world.go` has a `package greeting` and one `HelloWorld` function. It is intended to be used in a test file `hello_world_test.go` which imports testing. For reference, please see also https://github.com/exercism/go/tree/master/exercises/hello-world. The instructions are to run `go test`, which works (same as `dlv test` as mentioned). 

> try to put your code as following directory structure src/hello/cmd/hello_world.go and _test.go

I really don't want to change the directory structure for each of the exercises - they are self-contained and ready to be tested.

If you could give me a pointer to where and how `dlv` is called, we could come up with a way to pass the `test` argument to it - and hope that it works as it does already from CLI.

**Comment by apmattil** [comment]
open hello_world_test.go and File Configuration template, it checks from buffer/file name which mode to use run or test.

**Comment by fleimgruber** [comment]
That worked, thanks for the shove and sorry for the noise. Did I miss this in the docs?

**Comment by apmattil** [comment]
np
I'll make PR for readme to clarify this.

I'll also make medium.com page since there are things that are not so clear.
https://medium.com/@apmattil/debug-go-golang-with-emacs-fbf840c0aa56

**Comment by fleimgruber** [comment]
Great. Thanks again @apmattil and @yyoncho and keep up the great work!

**Comment by apmattil** [comment]
@fleimgruber could you help testing issue #211 
If you select locals buffer/window (shown via dap-hydra + 'sl') can you resize that window ?
if not, does `M-x treemacs-toggle-fixed-width` help ?
