### ISSUE TITLE
go templates arguments not passed to executable correctly

### ISSUE THREAD

**Issue by apmattil** [emacs-lsp/dap-mode#208]
bug is at MS go extension (goDebug.js)
I made a ticket and fix for them : https://github.com/microsoft/vscode-go/issues/3022

**Comment by apmattil** [comment]
hmm.. I think goDebug.js expects args parameter as list.
@yyoncho : how can I convert string (space separated) to list with elisp ?

**Comment by yyoncho** [comment]
`s-split`

**Comment by apmattil** [comment]
@yyoncho thanks for the help.. still learning elisp.
PR #209 fixes this.
MS js likes to have args as list.

**Comment by apmattil** [comment]
fix merged.. closing this one.
