### ISSUE TITLE
dap-breakpoint-conditon should check syntax ahead

### ISSUE THREAD

**Issue by wztdream** [emacs-lsp/dap-mode#210]
Hi,
This issue is for debugging python code. If I use `dap-breakpoint-condition` to add a conditional breakpoint, and the syntax is wrong by mistake, there is no warning for current version. The error will show up when debugging the code. This behavior is strange especially then the conditional breakpoint is in a loop, in this case, the error will show again and again for each loop. If the loop is 10000 cycles, it will show 10000 times.
I also tried it on vscode, the behavior is the same. So maybe you can improve this, best to check the syntax ahead, or at least to hang the debug process when the first error occurs instead of showing the error 10000 times.
You can reproduce the error by following python code:
```
i = 0
while True:
    i += 1
    if i >= 10000:
        break
```
set the conditional breakpoint at `i +=1`, and set a "wrong syntax" condition such as `i = 10`, then debugging the code, this syntax error will show up 10000 times for this case.

**Comment by yyoncho** [comment]
There is no API for that so there is nothing we can do on our side - you may do a feature request in DAP protocol repository.
