### ISSUE TITLE
feature request to enable resizing locals buffer

### ISSUE THREAD

**Issue by apmattil** [emacs-lsp/dap-mode#211]
my problem is that hydra 'list locals'/ dap-ui-locals buffer is very often too small.
I can roll the buffer to left but since I can not see the cursor so I often slip over and I'm back where I started. 

As you can see I'm trying to see 'f' variable content.. and to read the name variable from file struct is very inconvinient.

![image](https://user-images.githubusercontent.com/20554772/73597594-35b7a600-4536-11ea-9bd3-18dea56d64b9.png)

I tried some testing by my self, but my elisp skills are still at baby steps phase and could not make it work.

**Comment by yyoncho** [comment]
you could change the default size by modifying `dap-ui-buffer-configurations`

**Comment by apmattil** [comment]
well it looks better when I set size to 30 chars, but it really does not solve the issue.. I just get it bigger and problem remains.
e.g when I look at r.a variable.
``` 
(,dap-ui--locals-buffer . ((side . right) (slot . 1) (window-width . 30)))
```
most cases e.g int variable size is ok.
Issue is that I need to resize it Sometimes.

**Comment by yyoncho** [comment]
I don't understand what the issue is: you could use the mouse or `M-x enlarge-window-horizontally` and resize it as a normal buffer and you could also open that buffer in the current buffer and have it as a single window.

**Comment by apmattil** [comment]
if I use M-x enlarge-window-horizontally it says 'window is fixed size'
if I use mouse it says 'no reziable window on right of this one'.

if I set at dap-ui--show-buffer
```
(fit-window-to-buffer-horizontally t)
(window-resize-pixelwise t)
```
resize works bug locals (treemacs ?) disapears.

**Comment by apmattil** [comment]
how do I get it as a single buffer ?

**Comment by yyoncho** [comment]
`(window-preserved-size (nil . nil))` I think that this should be added to make the window resizable. It works fine on my side when using emacs 27.

**Comment by apmattil** [comment]
where should I add (window-preserved-size (nil . nil)) ? .emacs does not like it.
I have emacs snapshot 25.0.70

**Comment by yyoncho** [comment]
Here it is the relevant documentation - https://www.gnu.org/software/emacs/manual/html_node/elisp/Window-Parameters.html#Window-Parameters 

https://www.gnu.org/software/emacs/manual/html_node/elisp/Displaying-Buffers-in-Side-Windows.html

**Comment by apmattil** [comment]
whatever way I try I can not get it to work.. and I tried.
perhaps I need to check with some other emacs version.

**Comment by apmattil** [comment]
no help 28.0.50 gives same result.

**Comment by apmattil** [comment]
`M-x treemacs-toggle-fixed-width` unlocks fixed size of locals-buffer and you can resize the frame/win.

**Comment by apmattil** [comment]
@yyoncho  perhaps set above as a default ?

**Comment by fleimgruber** [comment]
@apmattil I tested resizing the locals window on macOS with Emacs 26.3 and on Windows with Emacs 27.0.60, works on both machines.

**Comment by fleimgruber** [comment]
But one thing I noticed (maybe missed before) is that at each step with `n` the previously unfolded locals view gets folded down to `> Local` and I have to unfold it again at every step through the program.

**Comment by apmattil** [comment]
@fleimgruber : thanks.. it worked without `M-x treemacs-toggle-fixed-width` ? hmm... then it is some of my settings.
for me the locals tree stays open when I step the code.
what version of treemacs you have ?

**Comment by apmattil** [comment]
@yyoncho this patch makes resize to work for me.. would you consider adding this if I make PR ?
```
apmattil@penguin:~$ diff -u dap-mode/dap-ui.el .emacs.d/elpa/dap-mode-20200124.717/dap-ui.el
--- dap-mode/dap-ui.el  2020-01-31 21:38:44.915706826 +0200
+++ .emacs.d/elpa/dap-mode-20200124.717/dap-ui.el       2020-02-04 21:12:30.432223593 +0200
@@ -819,6 +819,7 @@
   (dap-ui--show-buffer (get-buffer-create dap-ui--locals-buffer))
   (dap-ui-locals--refresh)
   (with-current-buffer dap-ui--locals-buffer
+    (if treemacs--width-is-locked (treemacs-toggle-fixed-width))
     (add-hook 'dap-terminated-hook #'dap-ui-locals--refresh-schedule)
     (add-hook 'dap-session-changed-hook #'dap-ui-locals--refresh-schedule)
     (add-hook 'dap-continue-hook #'dap-ui-locals--refresh-schedule)
```

**Comment by yyoncho** [comment]
I don't like accessing private variables. This probably should go in lsp-treemacs project to reuse the logic. Is there a way to do it without accessing the property?

**Comment by fleimgruber** [comment]
@apmattil treemacs version "v2.7-2020.01.25 @ 26.3"

**Comment by apmattil** [comment]
@yyoncho @fleimgruber 
my mistake ..sorry about this noise.
I have my treemacs version from non stable melpa (now 20200204.1831)

If this happens to come to stable release we know how to fix it ;)

**Comment by mgalgs** [comment]
20201230.1245

**Comment by mgalgs** [comment]
I'm having the same problem. I'm using [lsp-dart](https://emacs-lsp.github.io/lsp-dart/#debug). I've tried `M-x treemacs-toggle-fixed-width` but still can't resize my locals window horizontally:


https://user-images.githubusercontent.com/152014/103586194-6d8f4200-4e99-11eb-97c0-535f24a3b445.mp4



This is with treemacs 20201230.1245

**Comment by chmouel** [comment]
For anyone else who were looking for this, just use : 

`(treemacs-set-width` &optional ARG)`

or shortcut to `w` to set a new width on the fly and being able to resize the window.
