### ISSUE TITLE
what is the standard way to terminate debug and re-start the debug?

### ISSUE THREAD

**Issue by wztdream** [emacs-lsp/dap-mode#212]
Hi,
When we debugging, sometimes we need to terminate it before finish, or need to re-start the debug. What is the standard command to to these?
Currently, I just kill the buffer to terminate it, or call `list-process` then press `d` to terminate it. I do not think they are standard method.
BTW, what is the haydra key `Q: disconnection`  and `r: restart frame` mean?

**Comment by yyoncho** [comment]
I use `M-x dap-disconnect` and then `M-x dap-debug-last` (I think that
the first one does not work for python and it seems like that we should
explicitly kill it after we call dap-disconnect and servers returns.


wztdream writes:

> Hi,
> When we debugging, sometimes we need to terminate it before finish, or need to re-start the debug. What is the standard command to to these?
> Currently, I just kill the buffer to terminate it, or call `list-process` then press `d` to terminate it. I do not think they are standard method.
> BTW, what is the haydra key `Q: disconnection`  and `r: restart frame` mean?
