### ISSUE TITLE
[ Native Debug GDB]  dap-ui-locals keybinds?

### ISSUE THREAD

**Issue by tosiek88** [emacs-lsp/dap-mode#222]
Hi. I have issue with treemacs Local, is there a way to expand tree with keybinds? When cursor is on >Local i have info `mouse-2, RET, Push this button`, Mouse is working fine (almost), but pressing RET,  I am getting information `[Treemacs] No ret action defined. `.  Is there a way to automatically unfold all nested variables? 

This can be issue with doom emacs? Somewhere i read that "<return>" is for windowed Emacs and "RET" for terminal .

**Comment by yyoncho** [comment]
Did you try with TAB?

**Comment by tosiek88** [comment]
TAB is working ! Thanks a lot, I can't find this information.

**Comment by yyoncho** [comment]
I will add it do readme. About the expand - there is an issue in treemacs repo to provide expand function which accepts arguments for how much levels to expand.

**Comment by tosiek88** [comment]
For now that fine I can easy move by hydra "sl" macro to Locals and open expand interesting variables, so for me that enough. Thanks a lot.
