### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by ovidius72** [emacs-lsp/dap-mode#225]
I'm trying to setup dap to debug node JS in typescript, transpiled with ts-node.

In VSCode I use this configuration:

```(json)
    {
      "name": "TS Index",
      "type": "node",
      "request": "launch",
      "args": ["${workspaceFolder}/src/index.ts"],
      "runtimeArgs": ["--nolazy", "-r", "ts-node/register"],
      "sourceMaps": true,
      "cwd": "${workspaceRoot}",
      "protocol": "inspector"
    }
```

I can't find a way to have dap-node working with typescript. I can debug plain javascript files, meaning the it is installed and working fine, but no luck with the above configuration:
Replacing all the placeholders with absolute paths still doesn't work.
```Warning (emacs): Initialize request failed: Cannot launch program '{path}'; setting the 'outFile' attribute migh help.```

Any suggestion ?
Thanks

**Comment by yyoncho** [comment]
What is the template you are trying to run?

**Comment by ovidius72** [comment]
I've registered this template
```
(dap-register-debug-template "TSNode2"
    (list :type "node"
          :request "launch"
          :args ["/home/antonio/projects/opa/tsnode2/src/index.ts"]
          :runtimeArgs ["-r", "ts-node/register"]
          :cwd "/home/antonio/projects/opa/tsnode2"
          :protocol "inspector"
          :name "TsNode2"
          ))
```

**Comment by yyoncho** [comment]
> "sourceMaps": true,

This is missing?

If this does not solve the issue, can you prepare a ts project (hello world) or instructions to create such with the steps you do in vscode?

**Comment by ovidius72** [comment]
Thanks you @yyoncho 
setting `:sourceMap t` does not solve the problem.
I'm going to prepare a simple project.

**Comment by ovidius72** [comment]
If you want, you can pull this repo and test it https://github.com/ovidius72/dap-node-test

**Comment by tosiek88** [comment]
I did try with Indium once and was working (without dap-mode) I would like to transient also on dap-mode. My .indium looks like this 
```
{
"configurations": [
  {
    "name": "test of typescript",
    "type": "node",
    "program": "node --inspect-brk -r ts-node/register -r tsconfig-paths/register src/main.ts",
      "port":9229
    }

  ]
}
```
I will try in second with your example.

**Comment by yyoncho** [comment]
Your initial template would work with sourceMaps: true. The issue was that dap-node.el was requesting :program and when you pick a program it was breaking the template since it is not part of that template particular flow. FYI at some point, we will support the vscode debug templates for better interoperability.

**Comment by ovidius72** [comment]
Can you please share the template that is working for you ?
I've updated to the last commit but I'm still getting the same error :disappointed: .

**Comment by yyoncho** [comment]
```
(dap-debug
 (list :name "TS Index"
       :type "node"
       :request "launch"
       :args ["/home/kyoncho/dap-node//src/index.ts"]
       :runtimeArgs ["--nolazy" "-r" "ts-node/register"]
       :sourceMaps t
       :cwd "/home/kyoncho/dap-node/"
       :protocol "inspector"))

```

**Comment by tosiek88** [comment]
I am getting:
```
No message handler for process
No message handler for capabilities
Debug session process exited with status: killed
```

**Comment by yyoncho** [comment]
So it is working - place a breakpoint in the code using M-x dap-breakpoint-toggle or using mouse.

**Comment by tosiek88** [comment]
Thank you it working!

**Comment by tosiek88** [comment]
Is there are a way to run this one with nodemon?

**Comment by yyoncho** [comment]
I have little to no nodejs experience. If you can do it in vscode we can do it too. But I need more details.

**Comment by ovidius72** [comment]
Thanks you @yyoncho Now it works fine. There was another subtle error in my configuration, the comma inside the runtimeArgs array. I copied it from the VSCode settings and didn't remove that damn comma.
Now I'm able to add breakpoints, and see the locals on the sidebar. Because I'm using emacs doom I have to enter in insert mode and press TAB to expand variables. Do you know if there is an easier way to exand variables without swithing between insern/normal mode to expand and navigate ?

**Comment by yyoncho** [comment]
I am using spacemacs and it works OOTB. I think that it uses https://melpa.org/#/treemacs-evil to make it work .
