### ISSUE TITLE
Unable to get django view to stop at breakpoint

### ISSUE THREAD

**Issue by seanfarley** [emacs-lsp/dap-mode#229]
I've created a skeleton of a project for a django app here: https://github.com/seanfarley/django-dap-debug

But I'm having trouble getting the breakpoints to stop. For example, I'm trying to get a breakpoint on this line: https://github.com/seanfarley/django-dap-debug/blob/c5c1c88bc4304b714735a02927946bbe4fa86cb8/mysite/polls/views.py#L5

I can get a dap process to launch via this lisp,

```
(dap-register-debug-template "debug mysite"
                               (list :name "Debug Django App"
                                     :type "python"
                                     :args "runserver"
                                     :cwd nil
                                     :env '(("DEBUG" . "1"))
                                     :request "launch"))
```

but nothing seems to stop the process and enter into a debugger even after I set a few test breakpoints. Any help would be appreciated!

**Comment by yyoncho** [comment]
I just translated the debug template from: https://code.visualstudio.com/docs/python/tutorial-django and it worked out.

``` elisp
(dap-debug
 (list :type "python"
       :args "runserver --noreload"
       :cwd "/home/kyoncho/Sources/django-dap-debug/mysite/"
       :module nil
       :console "integratedTerminal"
       :program "/home/kyoncho/Sources/django-dap-debug/mysite/manage.py"
       :request "launch"
       :name "Python: Django"
       :django t))
```

**Comment by seanfarley** [comment]
Thank you! That works perfectly!

**Comment by arvydasg** [comment]
Hello, may I ask here even though it is closed? 

I don't really find any other sources that explain how to use **dap-mode** with **Django**. I am running emacs on NixOS, on WSL.

I notice that at the time of this ticket creation [ptvsd ](https://github.com/microsoft/ptvsd) was used(from requirements.txt) and now its deprecated, so I am using `debugpy` package instead.

## my emacs config for dap-mode:

```elisp
(use-package dap-mode
  :commands dap-debug
  :hook ((python-mode . dap-ui-mode) (python-mode . dap-mode))
  :config
  (require 'dap-python)
  (setq dap-python-debugger 'debugpy)
  (dap-auto-configure-mode 1)
  )
```

## venv setup:

If I open emacs, then open the `test.py` file and try to run `dap-debug`, I get such message:

> Debug session process exited with status: exited abnormally with code 1

Then I do `pyvenv-workon` and choose a virtual environment in which I have debugpy and other python packages installed, this is the requirements.txt file(has dajngo stuff, eglot stuff, debugpy):

```txt
Django
django-allauth
pyodbc
gunicorn
mssql-django
django-autocomplete-light
django-unfold
django-simple-history
django-debug-toolbar
debugpy
python-language-server[all]
```
## debugging a single python file - WORKS:

I then run `dap-debug` and all of a sudden I see this - Beauuuuutiful!!:

![image](https://github.com/emacs-lsp/dap-mode/assets/78803192/9ba8919f-0440-416e-9d8a-661eea8e7cff)

I am able to run the debugger just fine it seems.

## debugging Django - QUESTION:

BUT!!!!! If I try to run the same app https://github.com/seanfarley/django-dap-debug that this ticket creator used for his testing, I activate venv, go to views.py file, set breakpoints:

![image](https://github.com/emacs-lsp/dap-mode/assets/78803192/b6d20b58-6c7b-4726-98d1-0e1518372fd3)

And try to run `dap-debug`, I get `No message handler for process`, but some of the dap-ui shows up.:

![image](https://github.com/emacs-lsp/dap-mode/assets/78803192/1d427ef2-12ca-47e0-9226-5f3e1f12f77b)

I saw someone mentioning this message here - https://github.com/emacs-lsp/dap-mode/issues/456. I am not sure what a call stack is, I could try to provide it if needed.

Maybe I am calling the `dap-debug` from a wrong location? Should I have the django server already running with `python manage.py runserver` or dap-debug should start the server by itself(like in vscode)?

### attempting to debug the same django app in vscode

If I try to debug this app, breakpoints in the same location, same packages installed, it's successful:

![image](https://github.com/emacs-lsp/dap-mode/assets/78803192/0000aada-fc4a-4b08-a253-7fdc467a980b)

As you might expect, the browser window is also spawned with the django service running on localhost.

## Call for help

I really would like to be able to use Emacs for Django developing, so figuring out how to debug in Emacs as well is crucial for me! :)

Thank you!

**Comment by seanfarley** [comment]
I haven't tried this in a while but am actually about to work on some django stuff so I can a look next week or so (hopefully 😬)

**Comment by arvydasg** [comment]
> I haven't tried this in a while but am actually about to work on some django stuff so I can a look next week or so (hopefully 😬)

Hello!!! Just a reminder, in case you have tried it and forgot to share your experience here 🙏

**Comment by seanfarley** [comment]
Yep, I forgot
