### ISSUE TITLE
Feature req: expand first level dap-ui-locals

### ISSUE THREAD

**Issue by skybert** [emacs-lsp/dap-mode#230]
The new tree widget in `dap-mode` is really nice, but it's lacking in two respects:

- the locals view is always collapsed, forcing me to use the mouse or navigate there to expand it. It would be great (I'd say essential) to have the possibility to expand the first level by default (this is was Eclipse, IDEA do). IMHO, this should be the default behaviour but I'd be happy for a configurable option too :smile: 

- the tree is refreshed without any step being issued. The developer can thus be investigating a deep object graph when `dap-mode` suddenly refreshes the tree, collapsing the whole thing again.

Keep up the good work!

-Torstein

**Comment by yyoncho** [comment]
> the tree is refreshed without any step being issued. The developer can thus be investigating a deep object graph when dap-mode suddenly refreshes the tree, collapsing the whole thing again.

can you provide steps to reproduce?

**Comment by skybert** [comment]
> > the tree is refreshed without any step being issued. The developer can thus be investigating a deep object graph when dap-mode suddenly refreshes the tree, collapsing the whole thing again.
> 
> can you provide steps to reproduce?

```
Given I have a break point set in a Java source file
And the debugger stops at this break point
And I expand a complex object 3 levels deep in the locals widget (`dap-ui-locals`)
When I wait for a `n` minutes
Then the locals widget is refreshed automatically 
And my expanded locals object is collapsed
```

I cannot tell you how long `n` is, but I'd say a minute or `3`.

**Comment by Keating950** [comment]
I second this interest in having the locals expand automatically, or at least having an option to enable this. Is there a workaround for this right now? My knowledge of elisp is quite shallow, so I'm not sure if this could be automated with a hook or function advice somehow.

**Comment by bk138** [comment]
Same here, would love to have the locals expanded automatically.  I could not find any customize-group setting that would enable this...
