### ISSUE TITLE
Why download vscode extensions to user-emacs-directory

### ISSUE THREAD

**Issue by petr-tik** [emacs-lsp/dap-mode#233]
Hey, 
This is a great mode - thanks for all your work so far. 

I forked it, because I want to add a standalone dap-rust.el powered by vadimcn/vscode-lldb. This is my first experience hacking on elisp, so I might be slow. One thing I noticed, when trying to wrap my setup function with `dap-utils-vscode-setup-function` is the default path to check for existing and save downloaded vscode extensions. 

```elisp
(defcustom dap-utils-extension-path (expand-file-name ".extension" user-emacs-directory)
  "Directory to store vscode extension."
  :group 'dap-utils
  :type 'directory)
```

This evaluates to my "\~/.emacs.d/.extension/". Having installed some vscode extensions in vscode, I find them in "~/.vscode/extensions". Surely, if we want to help people switch between emacs and VSCode we can use VSCode's own ".vscode/extensions/*" directories and either find extensions or install them there?

I understand it's a customizable group variable and I can change it locally, only wanted to ask why this was the case and check what the best way to work with this is, as I am adding my mode. 

thanks again for all your work

**Comment by yyoncho** [comment]
Having emacs extension kept in vscode extension dir feels unnatural and also it will couple unnecessarily emacs version with vscode version. The main objective of the extension is to provide a consistent experience with the rest of the emacs ecosystem, not with vscode. But certainly, we would like to make vscode->emacs transition easy, thus we have created an automatic installation. 

>  This is my first experience hacking on elisp, so I might be slow. 

Feel free to ask questions.

**Comment by petr-tik** [comment]
hey, thanks for your swift reply. The wrapper to automatically install is great - that's why I want to use it. I think we should admit that the convenience of vscode is improving the UX for emacsers as well. 

Your reasoning for installing into a separate folder makes sense. 

However, I noticed differences between the installations carried out by vscode and our macro - namely our macro doesn't install the dap-server binary. This might be due to vscode-lldb not configuring direct download intsallations until now, so I can also ask them about it. 

** steps to reproduce
*** Install codelldb in vscode
Open vscode, install codelldb
Instructions here: https://github.com/vadimcn/vscode-lldb

*** Install in emacs
open a new buffer in emacs (assuming you obviously always have an open emacs) 

Paste this and evaluate buffer
```elisp
(require 'dap-mode)

(defcustom dap-rust-debug-path (expand-file-name "vscode/vadimcn.vscode-lldb" dap-utils-extension-path)
  "The path to Rust's DAP powered by lldb."
  :group 'dap-rust
  :type 'string)

(dap-utils-vscode-setup-function "dap-rust" "vadimcn" "vscode-lldb" dap-rust-debug-path)
(dap-rust-setup)
```

This should install vscode-lldb to the emacs-specific .extension dir. 

Comparing the 2 installations shows
vadimcn/vscode-lldb installed through vscode

```bash
~/.vscode/extensions/vadimcn.vscode-lldb-1.5.0$ tree
.
├── adapter2
│   ├── codelldb                                 <---- executable we need
│   ├── codelldb.py
│   ├── debugger.py
│   ├── libcodelldb.so
│   ├── rust.py
│   └── value.py
├── CHANGELOG.md
├── extension.js
├── images
│   ├── checked.svg
│   ├── lldb.png
│   └── unchecked.svg
├── lldb
│   ├── bin
│   │   ├── lldb
│   │   ├── lldb-argdumper
│   │   └── lldb-server                      <------ lldb-dap-server
│   └── lib
│       ├── liblldb.so                          <------- shared library needed for embedding a Python interpreter and pretty printing
│       └── python3
│           └── dist-packages
│               ├── lldb
│               │   ├── embedded_interpreter.py
│               │   ├── formatters
│               │   │   ├── attrib_fromdict.py
│               │   │   ├── cache.py
│               │   │   ├── cpp
│               │   │   │   ├── gnu_libstdcpp.py
│               │   │   │   ├── __init__.py
│               │   │   │   └── libcxx.py
│               │   │   ├── __init__.py
│               │   │   ├── Logger.py
│               │   │   ├── metrics.py
│               │   │   └── synth.py
│               │   ├── __init__.py
│               │   ├── lldb-argdumper
│               │   └── utils
│               │       ├── in_call_stack.py
│               │       ├── __init__.py
│               │       └── symbolication.py
│               └── six.py
├── package.json
├── platform.ok
├── README.md
└── syntaxes
    └── disassembly.json

12 directories, 35 files

```

vscode-lldb installed with our emacs macro

```bash
:~/.emacs.d/.extension/vscode/vadimcn.vscode-lldb$ tree
.
├── [Content_Types].xml
├── extension
│   ├── CHANGELOG.md
│   ├── extension.js
│   ├── images
│   │   ├── checked.svg
│   │   ├── lldb.png
│   │   └── unchecked.svg
│   ├── package.json
│   ├── README.md
│   └── syntaxes
│       └── disassembly.json
└── extension.vsixmanifest

3 directories, 10 files
```

If we don't want to reuse extensions installed by vscode - what do you think is the best way to auto-install vadimcn's codelldb extension?

Thanks

**Comment by petr-tik** [comment]
I want to first hack on top of the dap-server installed in .vscode/ and then investigate and stabilise the auto-install method for it. Expect a hacky draft PR over the weekend?

**Comment by yyoncho** [comment]
> I want to first hack on top of the dap-server installed in .vscode/ and then investigate and stabilise the auto-install method for it. Would you be able to review a hacky draft PR over the weekend?

I was about to suggest the same. The challenging/mandatory part is to make it work. For the missing files: I guess that the plugin does some platform-specific installation on the first startup. You may also ask in their gitter channel.

**Comment by petr-tik** [comment]
Hey, it's me with some questions. 

The readme section about "Extending DAP with new Debug servers" says

> dap-register-debug-provider - register a method to call for populating startup parameters. It should either populate :debugPort and :host in case of TCP Debug Adapter Server

Grepping for "debugPort" gives no results, however I have found debugServer in dap-[java|python]. 

Lookng at dap-python.el closer, I found 2 variables assigned to 2 keys in the configuration plist inside `dap-python--populate-start-file-args`

```elisp
    (plist-put conf :debugServer debug-port)
    (plist-put conf :port debug-port)
    (plist-put conf :hostName host)
    (plist-put conf :host host)
```

This suggests that the documentation is out of date (git grepping "debugPort" showed results from 2 years ago). 

So my question is:
What is the best way to configure and start a lldb-powered DAP server at the start of a debugging session?

**Comment by petr-tik** [comment]
Another question:
vadimcn's lldb extension requires :type property to be set to "lldb" (see [user manual](https://github.com/vadimcn/vscode-lldb/blob/master/MANUAL.md#starting-a-new-debug-session)) in the launch command. 

There are 2 other lldb clients - `dap-gdb-lldb.el` and `dap-lldb.el`, the latter requires installing lldb-vscode from source provided in the llvm-mirror/lldb tree. 

How can I make sure that in rust-mode files it will be my provider that will be called? 

At the moment, when I call debug in a rust module, it calls lldb provided by dap-lldb. I will make a repro later tonight

**Comment by yyoncho** [comment]
> At the moment, when I call debug in a rust module, it calls lldb provided by dap-lldb. I will make a repro later tonight

We could have one adapter of type lldb so whoever is loaded last will handle the lldb type.


> This suggests that the documentation is out of date (git grepping "debugPort" showed results from 2 years ago).

Yes.

> What is the best way to configure and start a lldb-powered DAP server at the start of a debugging session?

You have to figure out what vscode do and do the same. VScode starts the adapter and then connects to it either using tcp or stdout. We support both ways in dap-mode.

**Comment by petr-tik** [comment]
> We could have one adapter of type lldb so whoever is loaded last will handle the lldb type.

That means we already have a clash between `dap-lldb` and `dap-gdb-lldb.el` that should be resolved somehow? If I add dap-rust powered by lldb, this will only exacerbate the problem. 

> You have to figure out what vscode do and do the same. VScode starts the adapter and then connects to it either using tcp or stdout. We support both ways in dap-mode.

Yes, I am working precisely on that. Due to the problem above, dap-mode looks up the "lldb" config and tries to spin up a non-existing llvm-org/lldb process. Hence me reading the suggestions in the readme and trying to work out at which stage
a) the DAP server is configured 
b) the DAP server is selected
c) started

**Comment by yyoncho** [comment]
So you register a template and a provider. One the user selects a template dap-mode looks for the provider with that same type and calls it to populate the params needed to start the adapter. Yes, there is a collision when both modules are loaded, we can look for a solution and introduce another key for the adapters but this shouldn't be a blocker for you since you could avoid requiring the other adapters and your adapter will take care for the lldb type. Let me know if this helps.

**Comment by yyoncho** [comment]
There doesn't seem to be anything to address here. Thus closing. Please reopen if you disagree.

**Comment by petr-tik** [comment]
You are right - thanks for answering my questions above
