### ISSUE TITLE
[Request & Question] How to share template ?

### ISSUE THREAD

**Issue by MokkeMeguru** [emacs-lsp/dap-mode#237]
Hello, I want to share my dap template file via some environments and I think we need this function.

So, I wrote these code (I'm not an expert on emacs-lisp.)

```emacs-lisp
(defun dap-dump (varlist buffer)
  "utility function: insert some data to buffer"
  (loop for var in varlist do
        (print  var buffer)))


(defun dap-export-all-templates (output-file)
 "export all configuration file to output-file"
 (let ((buf (find-file-noselect output-file)))
   (set-buffer buf)
   (erase-buffer)
   (print
    (list 'setq 'dap-debug-template-configurations (list 'quote dap-debug-template-configurations))
    buf)
   (save-buffer)
   (kill-buffer)))


;; (dap-export-all-templates "~/.dap-template.el")

(defun dap-load-templates (template-file)
  "load configuration from template file"
  (load template-file))

;; (dap-load-templates "~/.dap-template.el")
```

**Comment by yyoncho** [comment]
What is the question/request?

**Comment by MokkeMeguru** [comment]
Question: Was there the saving & loading function for dap template?

Request: some function for editting & loading & sharing template e.g. yasnipet

**Comment by zoechi** [comment]
As I understand is that these templates are only in memory and lost after Emacs restart.
If you want to keep the, you have to add them to your Emacs config so they are applied automatically. Is that correct?

**Comment by yyoncho** [comment]
@zoechi they are stored in dap-debug-template-configurations and then you may use desktop mode and desktop-globals-to-save .

**Comment by nbfalcon** [comment]
@zoechi yes, that is correct; however, as yyoncho said, there are Emacs plugins for saving state, like desktop-mode, where you could have it saved like this:
```emacs-lisp
(use-package 'desktop :config (desktop-mode 1) (add-to-list 'desktop-globals-to-save 'dap-debug-template-configurations))
```
Note that this might cause redundancies with persp-mode, which is used by most distributions (notably Spacemacs).

@MokkeMeguru are you asking for the functionality you described above to be included in mainline dap-mode?

**Comment by zoechi** [comment]
@nbfalcon I just store them in init.el, but thanks for reminding me of dap-debug-template-configurations, that's what I need right now 👍

**Comment by MokkeMeguru** [comment]
I do not focus on the additional function in emacs-lsp, if there are the solution of storing configuration.  
So that, this issue will help us to understand how to store it, and that is all.
thanks!
