### ISSUE TITLE
Run single test with pytest

### ISSUE THREAD

**Issue by dbankmann** [emacs-lsp/dap-mode#242]
Hi,

I'm not sure if that's within the scope of this project, but I'd like to run a single test with pytest.

My current template looks like:

```
(dap-register-debug-template
  "Python :: Run Configuration"
  (list :type "python"
        :args ""
        :cwd nil
        :program nil
        :module "pytest"
        :request "launch"
        :name "Python :: Run Configuration"))
```
which is perfectly fine, when run from a test file, for running the _whole_ test_file `test_foo.bar`.
It runs the command
```
bin/python -m ptvsd --wait --host localhost --port 34767 -m pytest /base/test_foo.py 
```
where `test_foo.py` contains
```python
def test_1():
    pass

class TestFoo:
    def test_2(self):
        pass
    def test_3(self):
        pass
```
For debugging purposes I'd like to run the single test `test_3`.
From console I would run the command `bin/python  -m pytest /base/test_foo.py::TestFoo::test_3`

**Comment by yyoncho** [comment]
```
(dap-debug
 (list :type "python"
       :args ""
       :cwd nil
       :program "/home/kyoncho/.temp/mytest.py::TestFoo::test_3"
       :module "pytest"
       :request "launch"
       :name "Python :: Run Configuration"
       :hostName "localhost"
       :host "localhost"))
```

**Comment by dbankmann** [comment]
Thanks, I guess I should have made it clearer, that I want to have this automatized. The template I use works for running the tests of the currently visited file.
How can I get your program value for the current cursor position?

**Comment by yyoncho** [comment]
You may use https://github.com/emacs-lsp/dap-mode/blob/master/dap-java.el#L76 as a guide. It does the same for java(note that the code is java specific). Let me know if this is sufficient for you.

**Comment by dbankmann** [comment]
This goes in the right direction, yes. I'm not too familiar with elisp, tbh.

I tried to obtain the current class name:

```lisp
(defun dap-python-test-class ()
  "Get class FDQN."
  (-if-let* ((symbols (lsp--get-document-symbols))
                          (class-name (->> symbols
                              (--first (= (gethash "kind" it) 5))
                              (gethash "name"))))
      (concat "::" class-name)
    (user-error "No class found")))
```
This however, spits out the first classname appearing somewhere in the document, e.g. from an import like `from logging import Logger` at the top.
Is there some trick to get the the class at place instead?

**Comment by yyoncho** [comment]
Check https://github.com/emacs-lsp/dap-mode/blob/master/dap-java.el#L88 - it also compares the ranges.

**Comment by benbovy** [comment]
I was looking for this too, and saw this has been added in #274. Nice!
