### ISSUE TITLE
Could not start debugger process, does the program exist in filesystem?

### ISSUE THREAD

**Issue by ltrottier** [emacs-lsp/dap-mode#243]
Hi!

It seems that lldb-mi was removed from the lldb source tree and is now in a standalone repo (see annoucement [here](http://lists.llvm.org/pipermail/lldb-dev/2019-August/015357.html))

On ubuntu, after installing the default package (from [here](https://apt.llvm.org/)), there is no lldb-mi executable and I get the following error when trying to use lldb in dap-mode:

```
Could not start debugger process, does the program exist in filesystem?
Error: spawn lldb-mi ENOENT
```

I tried to compile lldb-mi myself, but I failed. I got compile errors, some I could fix, but others I could not. So, what would be the best option ? Get help to compile lldb-mi or update dap-mode to not use lldb-mi ?

Thanks!

**Comment by yyoncho** [comment]
It is not dap-mode which uses the lldb-mi but it is used by the corresponding adapter. Unfortunately, I have zero experience with lldb(note that we support 100+ language servers and debug adapters) so I would suggest you to ask for guidance for the compilation of lldb channels.

**Comment by ltrottier** [comment]
Thanks for the quick answer! I'll ask them.

**Comment by rileyrg** [comment]
@ltrottier did you get anywhere?
