### ISSUE TITLE
Unable to attach to node process in docker container

### ISSUE THREAD

**Issue by ruderngespra** [emacs-lsp/dap-mode#250]
Thank you for this great project, I am still very much enjoying it!

When I use the following template from my `launch.json` file in vs code, I am able to attach to node processes that the docker container exposes to port 9229:

``` json
    {
      "type": "node",
      "request": "attach",
      "name": "Attach to node process in docker container",
      "port": 9229,
      "localRoot": "${workspaceFolder}", 
      "remoteRoot": "/app",
      "skipFiles": [ "<node_internals>/**" ]
    }

```
I tried to register a template that allows me to do the same thing with dap-mode:

``` elisp
(dap-register-debug-template
  "Attach to node process in docker container"
  (list :type "node"
        :request "attach"
        :port 9229
        :localRoot "<my_hardcoded_workspace_folder>"
        :remoteRoot "/app"
        :name "Attach to node process in docker container"))
```
When I run `dap-debug` and chose my template, I would expect the debugger to attach to the node process. Instead, it asks me to "Select the file to run" - which I can not provide as it is placed in a docker container and also I don't want the debugger to run a new file, but attach to an already running process.
 
I am grateful for any advice on how to proceed with this!

**Comment by yyoncho** [comment]
We need to patch the populate function on dap-mode side - I have tested used attach to debug JS language providing also `:program "__ignored"` - can you check if it works?

(reference: https://github.com/emacs-lsp/lsp-mode/wiki/How-do-debug-nodejs-language-using-dap-mode )

**Comment by ruderngespra** [comment]
Thank you for the quick response! 

I added `program "__ignored` to my template and it did not ask for a file anymore, but still did not attach to the node process, but just returned `Debug session process exited with status: exited abnormally with code 1`.

**Comment by yyoncho** [comment]
Hm, it is hard for me to tell - can you upload the logs from messages buffer after setting dap-print-io to t and also the content of stderr buffer? Are you able to debug anything with dap-node?

**Comment by ruderngespra** [comment]
Thank you! I had a look at the buffers you were referring to and were able to debug my setup, everything works perfectly now!
