### ISSUE TITLE
[Request] Breakpoint indication on text mode.

### ISSUE THREAD

**Issue by rafagil** [emacs-lsp/dap-mode#251]
Hello!
I've been using the dap-mode recently and I'm loving it.
However, I currently use emacs only on text mode, and that means I can't see any indication of a breakpoint in the file.
I'm a noob at emacs and elisp, but if you don't have the time to do it, I would appreciate it if you could just point me in the right direction and I could try to do a PR myself. (Maybe changing the line background color or something like that)

Thanks.

**Comment by yyoncho** [comment]
We do support that by customizing dap-ui-pending-breakpoint-face and dap-ui-verified-breakpoint-face .

**Comment by yyoncho** [comment]
As a side note, we have plenty of tasks to do so if you are interested in dap-mode/lsp-mode development, you may ping me here or in gitter chat.

**Comment by rafagil** [comment]
Thanks for the help and quick response, I'll have a look at that!
