### ISSUE TITLE
Can't execute a .go file from a different folder

### ISSUE THREAD

**Issue by alvatar** [emacs-lsp/dap-mode#253]
I'm trying to run this template. It works well, but I'm unable to run the executable with a different PWD, to emulate the way it's normally run. Asset loading depends on this. Is there a way to do it? 

```elisp
(dap-register-debug-template
  "Launch Exchange"
  (list :type "go"
        :request "launch"
        :name "Launch Exchange"
        :mode "debug"
        :program "/Users/alvatar/projects/infra/cmd/myprogram/main.go"
        :buildFlags "-gcflags '-N -l'"
        :dlvToolPath "/Users/alvatar/go/bin/dlv"
        :args nil
        :env (list "PWD" "/Users/alvatar/projects/infra/")
        :envFile nil))
```

**Comment by yyoncho** [comment]
Maybe missing :cwd or :packagePathToGoModPathMap is causing the problems? As a side note, I usually use dap-debug-last which should works globally.

Also, you may prepopulate the template by doing `C-u M-x dap-debug-edit-template` - this will generate a buffer with the exact template that is going to be executed. 

Let me know which option makes it work:
```
      (dap--put-if-absent :packagePathToGoModPathMap
                          (ht<-alist `((,(f-dirname (buffer-file-name))  . ,(lsp-find-session-folder (lsp-session) (buffer-file-name))))))
```

This code from dap-go is suspicious - IMO packagePathToGoModPathMap should be calculated based on :program when it is different from buffer-file-name.

**Comment by alvatar** [comment]
Actually setting the `cwd` parameter fixed it. I was trying to find for this option
Thank you!

**Comment by yyoncho** [comment]
Is there anything else?
