### ISSUE TITLE
missing stack frame if function name is identical

### ISSUE THREAD

**Issue by wztdream** [emacs-lsp/dap-mode#255]
Hi,
This issue is about debug python code.  The stack frame will be missing if the function name is same when call `dap-switch-stack-frame`. See below example:
Suppose there are three python files a.py, b.py and c.py. a.py is for run the test, b.py has a function foo, which will call another foo function in c.py. Then add a break point in the foo function in c.py. Then `dap-switch-stack-frame`, the stack frames will be:
foo
test
module
Then the stack frame of foo in b.py is missing.
If you change the foo function in c.py to foo_c, then do the test again, you will see all the stack frame come back:
foo_c
foo
test
module
I did some edebug of the function `dap-switch-stack-frame`, it seems to me the thread-id is some how missing if the function name is the same.
` (thread-id (dap--debug-session-thread-id (dap--cur-session)))`
Or maybe due to the hash key is identical if the function is the same which results in missing stack. I also test the same code in vscode, there is no such missing. I hope these information is helpful to fix the bug.

 

#a.py
```
import b
def test():
    b.foo()
if __name__ == '__main__':
    test()
```
#b.py
```
import c
def foo():
    print("foo in b")
    c.foo()
```
#c.py
```
def foo():
    print("foo in c")
```

**Comment by yyoncho** [comment]
Also with 43c6727 I fixed an issue related to dap-ui-sessions not showing the stack frames.
