### ISSUE TITLE
Displaying the last assigned value of a variable

### ISSUE THREAD

**Issue by UndeadKernel** [emacs-lsp/dap-mode#268]
Hey there.
I was wondering if the following feature is already implemented or not:
When stepping through code, is it possible to display the last value of an assigned variable automatically? Say, I'm stepping though some python code and I step over:
```
ii += 1
```
Instead of adding `ii` to the watch list to see its value, is there a way to display the value assigned to the variable automatically after every assignment?

I see this type of functionality when stepping through `elisp` code. When debugging such code, after every `sexp`, the returned value of the `sexp` is shown in the modeline. For non lisp-like code, this is not viable, but displaying the returned values of functions or variable assignments should be possible.

Or is this just way out of scope?

**Comment by yyoncho** [comment]
see https://github.com/emacs-lsp/dap-mode/issues/219

**Comment by UndeadKernel** [comment]
The `locals` window is definitely helpful, yet unusable many times. When debugging functions/scopes with large amounts of local variables, most times the variables that change due to an assignment are not visible in the local window without scrolling.

**Comment by yyoncho** [comment]
Check the screenshot closely - it displays the values inline(including the one for the latest variable).

**Comment by yyoncho** [comment]
And to elaborate a bit more - the only backend data that we have is the locals data, we cannot find out what is the value of the last function call for example.

**Comment by UndeadKernel** [comment]
Got you! I see what you mean and that's exactly what I was thinking of. I'll keep track of that issue :+1:

**Comment by yyoncho** [comment]
ok, I will close this one.
