### ISSUE TITLE
Live debugging session fails in emacs-nox (but works in Emacs GUI)

### ISSUE THREAD

**Issue by mpsq** [emacs-lsp/dap-mode#272]
When I try to debug my Java application I get the following errors:

```
error in process filter: ad-Advice-select-window: Wrong type argument: window-live-p, nil
error in process filter: Wrong type argument: window-live-p, nil
ad-Advice-set-window-buffer: Window is dedicated to ‘ *dap-ui*’
```

I currently run Emacs in a terminal (Alacritty) and it is worth noting that the exact same debugging session works fine in Emacs GUI.

Is emacs-nox not supported or something is wrong with my setup?

Thanks

**Comment by yyoncho** [comment]
Based on the error message my guess is that you have a package that breaks due to the fact that dap-mode makes the helper windows dedicated. You may check that by doing the same after M-x toggle-debug-on-error

**Comment by mpsq** [comment]
Thanks for the quick reply :)

The backtrace is:

```
Debugger entered--Lisp error: (wrong-type-argument framep nil)
  select-frame(nil)
  dap-ui--update-controls()
  run-hook-with-args(dap-ui--update-controls)
  #f(compiled-function (_) #<bytecode 0x46f5349>)(#<hash-table equal 5/65 0x46f5c45>)
  #f(compiled-function (input0) #<bytecode 0x46f5365>)(#<hash-table equal 5/65 0x46f5c45>)
  #f(compiled-function (m) #<bytecode 0x46f5c0d>)("{\"success\":true,\"request_seq\":5,\"command\":\"configurationDone\",\"seq\":6,\"type\":\"response\"}")
  mapc(#f(compiled-function (m) #<bytecode 0x46f5c0d>) ("{\"success\":true,\"request_seq\":5,\"command\":\"configurationDone\",\"seq\":6,\"type\":\"response\"}"))
  #f(compiled-function (_ msg) #<bytecode 0x3ade7f5>)(#<process ServerMain (core)> "Content-Length: 88\015\n\015\n{\"success\":true,\"request_seq\":5,\"command\":\"configurationDone\",\"seq\":6,\"type\":\"response\"}")
```

My understanding is that the parameter is `nil` when calling https://github.com/emacs-lsp/dap-mode/blob/master/dap-ui.el#L512 ?

**Comment by yyoncho** [comment]
Ah, I got it - dap-ui-controls-mode is not supposed to be used in TUI.

**Comment by yyoncho** [comment]
To elaborate - there is no posframe implementation for TUI, also, it does not make sense for TUI since it is for improving mouse support.

**Comment by paulalesius** [comment]
> Does that mean dap is not supported at all for TUI? Or that there is a configuration that avoids this bug?

It seems to be possible to configure dap-mode by toggling UI features (reference https://emacs-lsp.github.io/dap-mode/page/configuration/)

M-x dap-ui-controls-mode

But there are no indicators in the editor or anything to know whether it is working, I'm not sure what's supposed to happen. There seems to be a dap session running (M-x dap-ui-sessions).

**Comment by ericdallo** [comment]
Yeah, disabling `dap-ui-constrols-mode` or setting removing `controls` feature like:
```elisp
(setq dap-auto-configure-features (remove 'controls dap-auto-configure-features))
```
While this feature is not available for TUI
