### ISSUE TITLE
Closing Sessions?

### ISSUE THREAD

**Issue by azer** [emacs-lsp/dap-mode#281]
After going through the documentation, I couldn't see how would we close debugging sessions. Is it enough to continue the program ? The modeline keeps the dap-mode icon though, also the modeline color stays in the debugging style (orange background). 

It'd be nice to have a simple workflow example users can adopt. In my personal case, I created a debugging mode that opens breakpoint / sessions list. Now I'm trying to figure out how to exit the debugging mode completely. I can't find any relevant documentation in this context.

**Comment by zoechi** [comment]
I found `dap-delete-all-sessions` `dap-delete-session` `dap-disconnect` but it's not clear to me what the difference between delete and disconnect is, because there is no reconnect or similar.

Perhaps there is a `request "attach"` (dap-debug-template) that can re-connect to disconnected sessions?

**Comment by azer** [comment]
@zoechi thanks for the answer! Do you have workflow functions to manage the debugging sessions ? I wonder how people put things together.

**Comment by yyoncho** [comment]
dap-disconnect = send disconnect to the server
dap-delete-session = send disconnect and cleanup session related stuff (e. g. the session will be cleaned from recent sessions).

Do you need more info than that?

**Comment by zoechi** [comment]
@azer I'm just starting as well. Trying to figure out which functions are worth key bindings and stuff. I just had my first few debug sessions working.

**Comment by azer** [comment]
Thanks @yyoncho for the info. I'm using `dap-delete-all-sessions` @zoechi  suggested and it works great. Here is my current function to quit the debugging mode;

```elisp
(defun stop-debugging-mode ()
  (interactive)
  (dap-delete-all-sessions)
  (dap-mode 0)
  (dap-ui-mode 0)
  (dap-ui-controls-mode 0)
  (delete-other-windows) ;; hide all the dap UI. I might want to delete the buffers as well.
  )
```

One problem with `dap-delete-all-sessions` is, it leaves the breakpoint UI even after deleting the sessions and disabling the UI modes. For example, if you delete the sessions before continuing the session, it'll stay in that look.

And here is my starting function:

```
(defun debugging-mode ()
  (interactive)
  (start-remote-delve) ;; I use Go, so need delve remote debugging server to be ready.
  (dap-mode t)
  (dap-ui-mode t)
  (dap-tooltip-mode)
  (dap-ui-controls-mode 1)
  (dap-ui-sessions)
  (dap-ui-locals)
  (dap-ui-breakpoints)
  (dap-ui-repl)
  )
```

Generally, It'd be nice to share more information about our workflows, which would significantly improve the development experience.

**Comment by nbfalcon** [comment]
I documented stopping and deleting sessions: see [emacs-lsp.github.io/dap-mode](https://emacs-lsp.github.io/dap-mode/page/how-to/).
