### ISSUE TITLE
dap-debug-last and dap-debug-restart should not prompt for configuration

### ISSUE THREAD

**Issue by MetaDark** [emacs-lsp/dap-mode#291]
Instead of prompting users for configuration when running either `dap-debug-last` or `dap-debug-restart` the configuration should be saved and reused.

**Comment by yyoncho** [comment]
They do that if there are no previous sessions. This will happen also if you have deleted previous sessions.

**Comment by MetaDark** [comment]
I wrote a provider for CMake tests + GDB and I'm still getting prompted even when reusing an existing session. Could there be something I'm doing wrong in the populate function?

**Comment by MetaDark** [comment]
Oh, I see what's happening now. The population function is always called, but it's being passed the output from the previous run. I can work around this, but is this the intended behaviour? Shouldn't it just use the config without passing it through the function again?

**Comment by yyoncho** [comment]
Populate behaviour is the intended behaviour. Let say you have a template that populates a field interactively. you run that template and it is selected. Then you will be able return that config with dap-debug-last without being asked again. 

> Shouldn't it just use the config without passing it through the populate function again?

No, it shouldn't. There might be a set of parameters that are unique to the run. E. g. if you are debugging over tcp the populate function should be able to pick free port. If you dont want something to go through the populate function you could call directly `dap-start-debugging`

**Comment by MetaDark** [comment]
Ok, thank you for the clarification. I will close this.
