### ISSUE TITLE
dap-debug-restart should delete or reuse the original session

### ISSUE THREAD

**Issue by MetaDark** [emacs-lsp/dap-mode#292]
I've noticed that after restarting a session multiple times, old sessions are still left behind. This can quickly clutter up the session list. I can't really think of a reason why we would want to keep them around. If someone really wanted to, they could just run `dap-disconnect` + `dap-debug-last` instead of `dap-debug-restart`.

**Comment by shackra** [comment]
I did not know dap-mode had a debug restart command

**Comment by ericdallo** [comment]
I thought that was on purpose to keep the history, what do you think @yyoncho

**Comment by yyoncho** [comment]
ATM we keep the old session to allow checking the output from it. I think that we can create an option to allow what this issue report is asking for.

**Comment by nbfalcon** [comment]
Oh, I forgot to update: everything is merged. Press C-u M-x dap-debug-restart and your old session will be reused. The prefix always overrides the default behaviour, which you can configure with the variable `dap-debug-restart-keep-session`. So if you dap-debug-restart to *not* retain sessions by default, setq `dap-debug-restart-keep-session` to nil after dap is loaded:
```elisp
(use-package dap-mode :config (setq dap-debug-restart-keep-session nil)
```
Or use with-eval-after-load/your distributions equivalent, ....
