### ISSUE TITLE
Missing output in repl and output buffers with gdb

### ISSUE THREAD

**Issue by wchasekelley** [emacs-lsp/dap-mode#303]
In *dap-ui-repl* and *GDB::Run out* for my application, I can't find a way to see the output for gdb commands. If I say `print varName` there is nothing. I see errors, for example when varName is out of scope it tells me "No symbol varName in the current context" or if I type an invalid command it will tell me that. How do I get the valid output as well?

**Comment by yyoncho** [comment]
Have you tried `(dap-go-to-output-buffer)` ?

**Comment by wchasekelley** [comment]
yes, in this case its the GDB::Run out buffer I mentioned. It has the regular program output as well as the errors, but print statements coming through. Same thing if I put it in the expressions window, i see red errors if there are any, but when the variable is in scope it goes blank.

**Comment by yyoncho** [comment]
```
(setq dap-output-buffer-filter '("stdout" "stderr" "console"))
```

This will enable printing in Run out buffer.

I am not quite sure if this should be part of the default. In any case, once we integrate with vscode-cpp this issue will disappear(and many more).

**Comment by yyoncho** [comment]
Most likely vscode has separate panes for each category, but someone has to verify that. If we dedicate a buffer per category we should provide a convenient way to navigate through the buffers.

**Comment by wchasekelley** [comment]
I do see it in the output buffer now at least. Thanks!
