### ISSUE TITLE
[Java] Breakpoint hit in attached process is slow, lag

### ISSUE THREAD

**Issue by karbiv** [emacs-lsp/dap-mode#304]
Debugging installed _Eclipse JDT Language Server_ code, `JDTLanguageServer.definition` method.
If Eclipse IDE is attached to the process(that Emacs uses) then breakpoint is hit immediately in IDE.
If `dap-debug` is attached,  then on requesting some definition Emacs waits several seconds showing a pending cursor.

So that big lag, delay in hitting a breakpoint, I'm wondering what part of the code is responsible for that. DAP documentation doesn't mention how events are triggered in the client, is it polling the status of a debugger or what...

**Comment by karbiv** [comment]
This code,  in `dap--on-event` function. But it seems to work normally.
https://github.com/emacs-lsp/dap-mode/blob/554f7cac9097ea1151af0b5b723dcdcc12abc4a8/dap-mode.el#L848-L860

The problem is in `xref--show-defs-buffer`, calling "fetcher".

**Comment by yyoncho** [comment]
Maybe set dap-print-io to t and then inspect when the event is received? If the time is spent on the server we might bump the adapter version and crosscheck with vscode.

**Comment by karbiv** [comment]
> If the time is spent on the server

"_stopped_" event is triggered immediately, but something happens after that.

`dap-print-io` is helpful, shows some requests for threads info, stack frames info.
Needs more Edebugging.

**Comment by yyoncho** [comment]
In order to go to the point we request the stackframes for the thread. So, you should check also when we get stackTrace response.

**Comment by yyoncho** [comment]
Also you may do `M-x trace-function RET dap--go-to-stack-frame RET` to see when the actual navigation is happening.
