### ISSUE TITLE
No easy way to tell which session I'm at in dap-hydra

### ISSUE THREAD

**Issue by shackra** [emacs-lsp/dap-mode#305]
As stated in the title, yesterday I found myself trying to debug a python and a go project, and because I'm new to dap-mode didn't realize that I need to switch between sessions in order to execute dap commands or hit breakpoints.

Since I'm using dap-hydra much, some sort of indicator should be available in it or document which variable shows the name of the current session or something like that.

**Comment by yyoncho** [comment]
There is an indicator in the modeline of the active buffer. Probably your modeline is hiding it.

**Comment by shackra** [comment]
I'm using doom-modeline, do you as well?

**Comment by shackra** [comment]
it seems doom-modeline "hides" this information behind an icon :/

**Comment by shackra** [comment]
made a report on doom-modeline.
