### ISSUE TITLE
Evaluate an Expression show no output with LLDB and GDB

### ISSUE THREAD

**Issue by edil3ra** [emacs-lsp/dap-mode#308]
When I try to evaluate a simple expression like print variable nothing shows up on the output buffer it happens with daps-eval and with dap-ui
It doesn't happen with python

![Screenshot from 2020-06-25 21-19-01](https://user-images.githubusercontent.com/11901087/85786899-fed36e00-b72a-11ea-826f-7f5e14c49f22.png)

**Comment by yyoncho** [comment]
see https://github.com/emacs-lsp/dap-mode/issues/303
