### ISSUE TITLE
Configure REPL window position

### ISSUE THREAD

**Issue by lccambiaghi** [emacs-lsp/dap-mode#310]
Hi, I can configure position and size vita the variable `dap-ui-buffer-configurations`. However, the REPL buffer is not affected. How can I, for instance, have the REPL window on side right and slot 2?

Thanks a lot for your work!!

**Comment by nbfalcon** [comment]
Right now, you can't, because `dap-ui-repl` doesn't call `dap-ui--show-buf`. I think we should move `dap-ui-repl` into dap-ui.el and display the repl like everything else. I might implement it at some point.

**Comment by nbfalcon** [comment]
I fixed it in latest master. You can configure dap-ui-repl in `dap-ui-buffer-configurations' like you would everything else. In your case, you can use the following with-eval-after-load block:
```emacs-lisp
(with-eval-after-load 'dap-ui
  (setq dap-ui-buffer-configurations
        `((,dap-ui--locals-buffer . ((side . right) (slot . 1) (window-width . 0.20)))
          (,dap-ui--expressions-buffer . ((side . right) (slot . 2) (window-width . 0.20)))
          (,dap-ui--sessions-buffer . ((side . right) (slot . 3) (window-width . 0.20)))
          (,dap-ui--breakpoints-buffer . ((side . left) (slot . 2) (window-width . ,treemacs-width)))
          (,dap-ui--debug-window-buffer . ((side . bottom) (slot . 3) (window-width . 0.20)))
          (,dap-ui--repl-buffer . ((side . right) (slot . 2) (window-width . 0.45))))))
```
