### ISSUE TITLE
Unable to run main with dap-debug on windows 10

### ISSUE THREAD

**Issue by deb75** [emacs-lsp/dap-mode#311]
Hello,

I try to run the `main` method of a java class with `dap-debug`.

It works fine on Linux, but fails on Windows 10, although I have the same version of `emacs`, `lsp` and `dap` on both OS.

When I issue `dap-debug`, I then choose `Java Run Configuration (compile/attach)` and I get : 
```
-*- mode: dap-server-log; default-directory: "d:/.../example/" -*-
Debug Adapter started at Mon Jun 29 16:31:53

java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=59275,quiet=y -cp %CLASSPATH_ARGS% com.....example.Example1

```

and nothing shows up. The LSP server displays `pending`, I have to issue `dap-delete-all-sessions` to come back to normal.

The only visible difference between both OS is that the java executable is not in a standard place on Windows 10.
I have set `lsp-java-java-path` to this place, but it seems from above that `dap-mode` only knows `java` probably
assuming it is in the Windows path.

Am I missing something ?

Regards

**Comment by yyoncho** [comment]
This is something that are currently investigating try this: https://github.com/emacs-lsp/dap-mode/issues/295#issuecomment-650914628

I am closing this as duplicate, please follow the other issues.
