### ISSUE TITLE
How to keep locals window unfolded?

### ISSUE THREAD

**Issue by wztdream** [emacs-lsp/dap-mode#317]
Hi,
My dap-mode version is 20200707.1837, I use it to debug python code. There is a small but noisy issue, the **locals window keeps folded**. So I have to switch to local window and "Tab" to unfold it after each debug step.

**Comment by yyoncho** [comment]
This should be fixed in latest dap-mode.

**Comment by wztdream** [comment]
yes, I just test the latest version, it is fixed, thank you.
