### ISSUE TITLE
variable's value in local window can not fold if it is an array

### ISSUE THREAD

**Issue by wztdream** [emacs-lsp/dap-mode#322]
Hi,
I use dap-mode for python code, here is the issue, if the variable value is an numpy array, after click the fold button it still takes multiple lines which is noisy if the array is large. See comparison with vscode below. 

You can easily reproduce the bug by creating any numpy array, then debug to show the value.
```
import numpy as np
a = np.arange(100).reshape(20,-1)
print('done')
```
dap-mode after fold "a"
![example on dap-mode](https://user-images.githubusercontent.com/39213018/89535759-6fd96b80-d829-11ea-9fb2-34c18f0bfe78.png)

vscode after fold "a"
![example on vscode](https://user-images.githubusercontent.com/39213018/89536195-1d4c7f00-d82a-11ea-8afe-2aad805943c3.png)

**Comment by wztdream** [comment]
@yyoncho Hi, can you have a look at this issue, it should be a small issue but can improve the debug experience a lot, as a long list of array showing there is quit noisy. Maybe need to update some format rule, but the logic of dap-mode is too complex for me to debug.

**Comment by ericdallo** [comment]
Probably we need to decorate the `value` or `variableReferences` [here](https://github.com/emacs-lsp/dap-mode/blob/master/dap-ui.el#L789), I just not sure how we can do that only for arrays and if this applies for all languages... you can debug that code adding some `(message "%s" value)` to help the debug.

**Comment by yyoncho** [comment]
```
(defun dap-ui-render-variables (debug-session variables-reference _node)
  (when (dap--session-running debug-session)
    (->>
     variables-reference
     (dap-request debug-session "variables" :variablesReference)
     (gethash "variables")
     (-map (-lambda ((&hash "value" "name"
                            "indexedVariables" _indexed-variables
                            "variablesReference" variables-reference))
             `(:label ,(concat (propertize (format "%s" name)
                                           'face 'font-lock-variable-name-face)
                               ": "
                               (propertize (s-truncate 30 (s-replace "\n" "\\n" value))
                                           'help-echo value))
                      :icon dap-variable
                      :value ,value
                      :session ,debug-session
                      :variables-reference ,variables-reference
                      :name ,name
                      ,@(list :actions '(["Set value" dap-ui-set-variable-value]))
                      :key ,name
                      ,@(when (and variables-reference (not (zerop variables-reference)))
                          (list :children (-partial #'dap-ui-render-variables
                                                    debug-session
                                                    variables-reference)))))))))

```
