### ISSUE TITLE
pls fix read watch exression syntax error

### ISSUE THREAD

**Issue by wztdream** [emacs-lsp/dap-mode#329]
Hi,
Here is a syntax error when read a string to watch the expression

dap-ui.el
around line 873

(read-string) receive string not symbol

`                       (t (symbol-name (symbol-at-point)))))))
`

**Comment by ericdallo** [comment]
Thanks for the report, do you mind opening a PR? then other people can review the changes :)

**Comment by wztdream** [comment]
ok

**Comment by wztdream** [comment]
PR #330
