### ISSUE TITLE
Redefine class in Java

### ISSUE THREAD

**Issue by blandest** [emacs-lsp/dap-mode#33]
I think this is not specific to dap-mode but I am looking for a method to accomplish the following.

While attached with jdb to a Java process, you can reload a class by typing in the REPL:

```
> redefine <class id> <class file name>
                          -- redefine the code for a class

```

The problem is that once a debugger has been attached to the process (dap-mode, for instance), no further debuggers can attach. The error subsequent debuggers receive is "Connection refused".

So, the problem is that I can no longer redefine Java classes unless I do it from dap-mode.
However, I could not find a way to accomplish this after reading the [official specification](https://microsoft.github.io/debug-adapter-protocol/specification).

**Comment by yyoncho** [comment]
@blandest hot reload is implemented by Java Debugger but it is not exposed by `dap-mode`. You may take a look at https://github.com/Microsoft/vscode-java-debug in the user settings section.

**Comment by blandest** [comment]
I found java.debug.settings.enableHotCodeReplace but I am not sure where to enable it in dap-mode. Would this option translate to some attach configuration in `dap-java--populate-attach-args'?

I was thinking something along the lines, but it does not seem to work:

`(dap--put-if-absent conf :enableHotCodeReplace t)`

**Comment by yyoncho** [comment]
I think that the following code has to be translated to dap-mode 

https://github.com/Microsoft/vscode-java-debug/blob/master/src/hotCodeReplace.ts 

in addition to the setting in the template.

**Comment by yyoncho** [comment]
> However, that did not trigger a reload of the code so I tested the hot replace feature in VSCode and I can confirm that it does not work there as well.

If this is so we should file a bug in the java adapter especially if it is reproducible with VScode. I guess you may have hit some edge case(e. g. unsupported version of JDK or something like that) since the Java Debug Adapter tends to work.
