### ISSUE TITLE
dap-debug not work | related with launch.json

### ISSUE THREAD

**Issue by rafamedina** [emacs-lsp/dap-mode#335]
Hi

The `dap-debug` command is returning this error:
version:   ##dap-mode-20200811.436

`helm-M-x-execute-command: Opening input file: No such file or directory, /Users/rafael.medina/dev/source/fluttertesting/hello_flutter/launch.json`

Related
#https://github.com/emacs-lsp/lsp-dart/issues/52

**Comment by ericdallo** [comment]
@nbfalcon could you take a look?

**Comment by yyoncho** [comment]
@rafamedina workaround:

```
(setq dap-launch-configuration-providers  '(dap-debug-template-configurations-provider))
```

**Comment by nbfalcon** [comment]
What a blunder on my side: I should check if the file exists before returning the filename in dap-launch-find-launch-json. I tested it on projects without launch.json files, but they weren't lsp projects. I guess I overlooked that.
At line 30:
dap-launch-find-launch-json should be:
```elisp
(defun dap-launch-find-launch-json ()
  "Return the location of the launch.json file in the current project."
  (when-let ((project (lsp-workspace-root))
             (launch-json (concat project (file-name-as-directory "launch.json"))))
    (when (file-exists-p launch-json)
      launch-json)))
```

**Comment by nbfalcon** [comment]
@yyoncho that is a temporary fix. The launch.json provider shouldn't fail if the project has no launch.json file.

**Comment by nbfalcon** [comment]
I'm making a PR against master asap.

**Comment by nbfalcon** [comment]
https://github.com/emacs-lsp/dap-mode/pull/336

**Comment by ericdallo** [comment]
It should be fixed on master now @rafamedina and soon on melpa latest release

**Comment by nbfalcon** [comment]
Sorry for the inconvenience.

**Comment by ericdallo** [comment]
No problem @nbfalcon, thanks for the quick fix :)
