### ISSUE TITLE
dap-debug for dart no handler

### ISSUE THREAD

**Issue by rafamedina** [emacs-lsp/dap-mode#337]
The command dap-debug displays correctly the templates, the devices, and launches the simulator.
The problem is that nothing happens in the simulator and emacs shows a message
By the way, the simulator controls are shown (Play, Reload, Refresh, etc.)

Message
`No message handler for dart.progressStart`

**Comment by ericdallo** [comment]
This time this is a `lsp-dart` bug :sweat_smile: 
The extension has changed this recently, thanks for the report, I'll take a look

**Comment by rafamedina** [comment]
It worked with the today version
```
[LSP Dart] [DAP] Loading app...
[LSP Dart] [DAP] App ready!
```
