### ISSUE TITLE
Feature parity of dap-launch

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/dap-mode#339]
1. VScode sometimes places the file in .vscode folder. It will be nice if we check that location as well.
2. VScode supports comments in json. We fail. We should filter out comments before parsing the json.

**Comment by yyoncho** [comment]
cc @nbfalcon

**Comment by nbfalcon** [comment]
1. I will do that now.
2. Comments in JSON? Can you show me the link or give me an example (e.g. with an example snippet)?

Also, as a side note: I have been working on making dap-variables.el generic and usable as a standalone library, because I needed it for my emacs tasks plugin. Perhaps we could integrate that into dap, or do you think that having another dependency would be an issue?

**Comment by nbfalcon** [comment]
https://github.com/emacs-lsp/dap-mode/pull/340

**Comment by nbfalcon** [comment]
And I got the issue wrong again... This time only in the branch name though.

**Comment by nbfalcon** [comment]
In VSCode, do the files override each other? That is, if I have two launch.json files:
```json
{
    "configurations": [
        {
            "name": "Debug",
            "type": "python"
        }
    ]
}
```
and
```json
{
    "configurations": [
        {
            "name": "Debug 2",
            "type": "python"
        }
    ]
}
```
Would both "Debug" and "Debug 2" show up as debug targets, or only either of them? If not, which would be preferred?

**Comment by yyoncho** [comment]
> 2\. Comments in JSON? Can you show me the link or give me an example (e.g. with an example snippet)?

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Cucumber",
            "type": "Ruby",
            "request": "launch",
            "program": "${workspaceRoot}/bin/cucumber"
        }
    ]
}
```

**Comment by yyoncho** [comment]
> In VSCode, do the files override each other?

AFAICS the one in .vscode folder wins.

**Comment by nbfalcon** [comment]
> > In VSCode, do the files override each other?
> 
> AFAICS the one in .vscode folder wins.

I'll need to change that.

**Comment by nbfalcon** [comment]
Comments are interesting though, because they must be handled correctly in strings, and also because JSON doesn't technically allow them. Do you know how I could enable comment support with jsonls (lsp-json)?

**Comment by nbfalcon** [comment]
Can I depend on rx?

**Comment by yyoncho** [comment]
> Can I depend on rx?

rx is built-in and we already use it in lsp-mode. 

> JSON doesn't technically allow them

json5 allows them.

> Do you know how I could enable comment support with jsonls (lsp-json)?

I don't know, most likely yes.

**Comment by nbfalcon** [comment]
Implemented in the latest commit of my feature branch. Handles both // and /* style comments, without nesting. Comments in strings are not replaced, so launch configurations like
```json
{
    // A comment
    "configurations": [
        {
            "type": "python",
            "name": "Debug /**/ //"
        }
    ]
}
```
will be handled perfectly, with the configuration showing up as "Debug /**/ //" and not "Debug  ".

**Comment by yyoncho** [comment]
Willing to add tests for these cases?

**Comment by nbfalcon** [comment]
Sure.

**Comment by yyoncho** [comment]
@nbfalcon as a side note, which language servers/debug adapters do you use?

**Comment by nbfalcon** [comment]
Language servers: jsonls, clangd, pyls (not the ms one, pip: python-language-server)
Debug adapters: gdb, pdb

**Comment by yyoncho** [comment]
@nbfalcon ok, because we looking for someone to integrate vscode-cpp debug adapter which is better than gdb one that is integrated currently in dap-mode. It does not have the limitations of gbd one (e. g. no support for multithreading) and I think that it renders locals and related better.

Here it is a starting point.
```
(defun dap-cppdbg--debug-test-at-point ()
  (interactive)
  (dap-debug (dap--template "Rust :: Debug test (at point)")))


(defun dap-cppdbg--populate-test-at-point (conf)
  "Populate CONF with the required arguments."
  (let ((cwd (lsp-workspace-root)))
    (plist-put conf :dap-server-path
           '("/Users/adamkowalski/.vscode-insiders/extensions/ms-vscode.cpptools-0.28.0-insiders/debugAdapters/OpenDebugAD7"))
    (plist-put conf :cwd cwd)
    (plist-put conf :request "launch")
    (plist-put conf :program (concat cwd "/target/debug/deps/test_parser-3aef394e7183e621"))
    (plist-put conf :externalTerminal :json-false)
    (plist-put conf :MIMode "lldb")
    (plist-put conf :args '("--test" "parse_local_define"))
    conf))


(dap-register-debug-provider "cppdbg" 'dap-cppdbg--populate-test-at-point)
(dap-register-debug-template "Rust :: Debug test (at point)"
                 (list :type "cppdbg"
                   :name "Rust :: Debug test (at point)"))
```

**Comment by nbfalcon** [comment]
Tests added.

**Comment by nbfalcon** [comment]
Is there some way to configure the json dialect for jsonls? As per the project page (https://github.com/vscode-langservers/vscode-json-languageserver#:~:text=The%20JSON%20Language%20server%20provides,any%20code%20editor%20or%20IDE.), jsonls supports a second dialect: jsonc. Comments are allowed in jsonc, not in json however. jsonc is a separate language-id. Perhaps there could be a mapping between json dialects and filenames like with lsp-json-schemas?

**Comment by yyoncho** [comment]
> Comments are allowed in jsonc, not in json however. jsonc is a separate language-id. Perhaps there could be a mapping between json dialects and filenames like with lsp-json-schemas?

There is `lsp-language-id-configuration`, so we can map jsonc extension to jsonc language id.

**Comment by nbfalcon** [comment]
> > Comments are allowed in jsonc, not in json however. jsonc is a separate language-id. Perhaps there could be a mapping between json dialects and filenames like with lsp-json-schemas?
> 
> There is `lsp-language-id-configuration`, so we can map jsonc extension to jsonc language id.

jsonc isn't a valid extension. However, mapping "launch.json" to "jsonc" is a possibility.

**Comment by nbfalcon** [comment]
Is there perhaps also some alist mapping between language ids and language servers?

**Comment by yyoncho** [comment]
> jsonc isn't a valid extension. However, mapping "launch.json" to "jsonc" is a possibility.

That makes sense. 

> Is there perhaps also some alist mapping between language ids and language servers?

There isn't such mapping atm.

**Comment by nbfalcon** [comment]
> There isn't such mapping atm.

But how is the language server for some language id decided then? C/C++ have 3 valid language servers: clangd, ccls and cquery. How is the decision made?

**Comment by yyoncho** [comment]
There is an activation function for each language. It does not involve the language id mapping but it uses major mode for most of the servers.

**Comment by kiennq** [comment]
You can get `jsonc-mode` from here https://github.com/kiennq/json-mode.
The `json-ls` is configured to `jsonc` when it in `jsonc-mode`.
