### ISSUE TITLE
Breakpoints not active unless toggled on subsequent requests

### ISSUE THREAD

**Issue by tomterl** [emacs-lsp/dap-mode#35]
As promised the first issue I encountered integrating php support:

Using dap-php to debug a http-request via xdebug, added breakpoints are not honored on subsequent requests, unless I toggle/reset one of them -- if I do that, all active breakpoints work.

**Comment by yyoncho** [comment]
Thanks for the PR - please include client-server communication.

**Comment by yyoncho** [comment]
The communication is in \*Messages\* buffer. It would be ideal if you can send me the logs from the start of the session until you hit the breakpoint.

**Comment by yyoncho** [comment]
I think that I have found the issue while I was adding support for the gdb/lldb adapter so you may wait for the fix before working on providing logs.

**Comment by yyoncho** [comment]
The PR is in, you may retest with latest dap-mode(once picked up by melpa).

**Comment by tomterl** [comment]
Yes - closing this; the behaviour is now more irratic wrt/ #36 , but breakpoints are honoured now on every request. One down :-)
