### ISSUE TITLE
dap-launch-remove-comments:  invalid use of rx builder

### ISSUE THREAD

**Issue by tomasjura** [emacs-lsp/dap-mode#354]
rx builder accepts `not` in three forms
`(not (any SET ...))`    matches any character not in SET ...
`(not (syntax SYNTAX))`   matches a character that doesn't have syntax SYNTAX.
`(not (category CATEGORY))`    matches a character that doesn't have category CATEGORY.

The simple `(not character)` style is not allowed as used in `dap-launch-remove-comments` function

patch:
```
dap-launch.el:42
- (: "/*" (* (or (not ?*) (: (+ ?*) (not ?/)))) (+ ?*) ?/))) 
+ (: "/*" (* (or (not (any ?*)) (: (+ ?*) (not (any ?/))))) (+ ?*) ?/)))
```

**Comment by yyoncho** [comment]
cc @nbfalcon

**Comment by nbfalcon** [comment]
From M-x describe-function rx on my system (emacs 28.0.50):
(not CHARSPEC)  Match one character not matched by CHARSPEC.  CHARSPEC
                **can be a character**, single-char string, (any ...), (or ...),
                (intersection ...), (syntax ...), (category ...),
                or a character class.
Evaluating
```elisp
(rx (not ?*))
```
in scratch yields "[^*]" as expected, too.

Can you show me the relevant section on your system, or perhaps link me to any internet manual?

Does it not compile on your system? What version of emacs do you use? We have a test suite to assert that `dap-launch-remove-comments' works (tests/dap-launch-test.el), so if there were such an error it wouldn't pass (I just checked, it passes).

**Comment by tomasjura** [comment]
My Emacs is the GNU version 26.3. I don't see the rx package in my package list (elpa,melpa), so I guess that rx macro is a part of Emacs core Lisp libraries and is not automatically updated via package management.

**Comment by kiennq** [comment]
I've been burnt by this before. You have to use `(rx (not (any ...)))` in this case for it to work in emacs pre 27.1

**Comment by nbfalcon** [comment]
Fixed in latest master. It will go live on MELPA in ~3 hours. @tomasjura, @kiennq thank you for clarifying.
