### ISSUE TITLE
dap-delete-session does not run `dap-terminated-hook`

### ISSUE THREAD

**Issue by nbfalcon** [emacs-lsp/dap-mode#359]
When running `dap-delete-session` with an active debug session, `dap-terminated-hook` is not called. This causes issues with e.g. doom-modeline, which colors itself yellow during debugging and relies on `dap-terminated-hook` to reset that color. As a workaround, I had to run
```elisp
(run-hook-with-args 'dap-terminated-hook nil)
```
afterwards to revert the modeline's color.

**Comment by ericdallo** [comment]
Hum, I already had this issue with doom-modeline, if it's really not running we should fix it

**Comment by ericdallo** [comment]
I think we should call `(dap--mark-session-as-terminated session)` [here](https://github.com/emacs-lsp/dap-mode/blob/master/dap-mode.el#L1599)?
c/c @yyoncho

**Comment by nbfalcon** [comment]
I think I found the issue: dap-delete-session must kill proc. dap-mode.el:1050: the process sentinel checks for death.

**Comment by nbfalcon** [comment]
Fixed it. Will commit ASAP. I suspect that `dap-delete-all-sessions` might have the same issue.

**Comment by nbfalcon** [comment]
@ericdallo we should not call `dap--mark-session-as-terminated` directly and instead use (kill-process `dap--debug-session-program-proc session`) instead, as the latter will go trough the process sentinel and that one will call `dap--mark-session-as-terminated`.

**Comment by nbfalcon** [comment]
Fixed in latest master. You can see the commit message for details of the issue and how it was fixed.
