### ISSUE TITLE
Sessions list/window 'confused' after a while

### ISSUE THREAD

**Issue by tomterl** [emacs-lsp/dap-mode#36]
This is a debug-session running for a couple of hours:

![image](https://user-images.githubusercontent.com/494717/51737847-ef5f7980-208d-11e9-93a1-cde188e5c0f0.png)

Everything works fine, just the display is out-of-sync.

**Comment by tomterl** [comment]
Will do.

**Comment by tomterl** [comment]
Thread list works fine, by the way; all Requests are listed, but only under one of the entries in the session-view; choosing via hydra 'st' works also, without hitch (errors when no current request/thread exists) -- I guess it'll clear up, once I manage to produce a communication-log

**Comment by tomterl** [comment]
This only happens if multiple processes connect via xdebug at the same time, if the requests come one at a time, everything's fine. I still don't have a clean communication log, but I'll get there.

**Comment by yyoncho** [comment]
Can you also `toggle-debug-on-error` to check whether there are errors while updating the Session list?

**Comment by tomterl** [comment]
Let's say I live in interesting times, professionally, ATM -- is it possible to log into a special buffer, not message? It seems to get truncated and is interspersed with other packages messages!? having a special buffer would help me produce a usable log for you.

**Comment by yyoncho** [comment]
I will switch dap-mode to use lsp-log function which logs into separate buffer. You may use message-log-max to change number of messages kept in Messages buffer.
