### ISSUE TITLE
debug inherited java test methods

### ISSUE THREAD

**Issue by joaocortes** [emacs-lsp/dap-mode#365]
Is there any command  in ``dap-java`` able  to debug an inherited test method?

``dap-java-debug-test-method`` doesn't work because it extracts the method name from point.
I tried to rewrite the compilation command associated to the buffer created by ``dap-java-debug-test-method``, but that doesn't work.

Maybe using  the universal arg to force ``dap-java-debug-test-method`` to query for the method name?

**Comment by yyoncho** [comment]
> Maybe using the universal arg to force `dap-java-debug-test-method` to query for the method name?

That would work. We could use completing-read with current methods and allow entering non-existing items. I think that some servers provide the methods from the super-class in imenu but `pyls` for sure does not return them. (not sure for the other language servers).

**Comment by joaocortes** [comment]
I am talking about java. You seem to be talking about python?
I am not familiar with the completion engines used. I may look into that, but for now it would be enough to allow the user to type the name of the method directly, even if cumbersome.
I was looking at the documentation of ``dap-java-debug-test-method``. When there is no method at point, it falls-back to running the test class. Don't you think It would make more sense to fallback to quering the user? After all, the command name strongly suggests it will try to run a method, not a test.

**Comment by joaocortes** [comment]
I thought ``dap-java`` was part of dap-mode, but it is part of lsp-java, which is slightly confusing. I will move this issue to the right place
