### ISSUE TITLE
Stepping swaps out locals window to code when changing files

### ISSUE THREAD

**Issue by adhilton** [emacs-lsp/dap-mode#390]
Whenever I step into a function and change sources files, the  locals frame on the right displays the new file, instead of the main code window I was in.    I was able to trace this down to (get-mru-window ) returning the dap-ui-locals window inside of dap--go-to-stack-frame.    
It appears that  mru window is incorrect because it has been affected by running dap-ui-locals, specifically

dap--select-thread-id   runs 
   'dap-stopped-hook  which in turn does 
   dap-ui--show-many-windows which then calls 
   dap-ui-locals  which does
   (with-current-buffer dap-ui--locals-buffer ....)

I can make an ugly hack of storing (get-mru-window ) in a variable before the run-hooks-with-arg and restoring it after, and it seems to fix the problem, but I'm sure there is a tidier way.

**Comment by nbfalcon** [comment]
Could you tell me which adapter you're using?

**Comment by adhilton** [comment]
Im doing this with Java via dap-java-debug-test-method

**Comment by yyoncho** [comment]
Can you provide a gif and M-x view-lossage(or explain what exactly you are pressing).

**Comment by adhilton** [comment]
![emacs-dap](https://user-images.githubusercontent.com/6645067/97089249-8ad7a280-1604-11eb-952e-891e434c105e.gif)
<img width="1238" alt="original-layout" src="https://user-images.githubusercontent.com/6645067/97089252-8f03c000-1604-11eb-80e6-10136c21634d.png">
Sure, I've included a gif of it.   view-lossage is full of mouse movement and such and doesn't show any of the relevant info.   Here is what I did though 
M-x dap-java-debug-test-method
(waited for things to start)
M-x dap-ui-locals in the right window to make it show locals
C-x 0 in the middle to get rid of the window showing the server interaction
Clicked the "step in" button on the control panel.
That takes us from code in ThingTest.java to Thing.java (contrived example) but as you can see the right panel with the locals switched.

You'll probably notice that I have changed dap-auto-configure-features to '(locals controls tooltip).   This is because the default gave me a very strange layout (as shown in the attached image) with the code in a small window on the right.  In that layout, I had a similar but different problem---anything that would change files would switch the small right window of the code, not the large one (even if I was in the large one before).  I get the same behavior if i use keystrokes in the hydra to step in rather than the buttons.

**Comment by yyoncho** [comment]
> It appears that mru window is incorrect because it has been affected by running dap-ui-locals, specifically

I am confused. We are using:

``` (select-window (get-mru-window (selected-frame) nil)) ```

to find out the window. get-mru-window should skip the locals windows since it is dedicated.

**Comment by adhilton** [comment]
Ahh that actually makes things perfectly clear.  gud brings up a dedicated window for IO which gets in the way, so I had a bit in my .emacs file that prevented that, and it was preventing these windows from being dedicated too.   Turning that off makes this work---thanks and sorry for the confusion.
