### ISSUE TITLE
debugpy remote debug issue

### ISSUE THREAD

**Issue by SarthakAdhikari** [emacs-lsp/dap-mode#397]
First of all, a big thanks to everyone for their efforts to make lsp-mode and dap-mode.

Recently, I was trying to debug a python application inside a docker container and there seems to be an issue with Remote Debugging functionality while using `debugpy`.

I get the following error when I perform M-x dap-debug for remote debugging purposes:
```No message handler for debugpyWaitingForServer```

Here is a small reproducible example:
https://github.com/SarthakAdhikari/debugpy_test

**Comment by nbfalcon** [comment]
I'll fix this soon.

**Comment by nbfalcon** [comment]
Try again.

**Comment by nbfalcon** [comment]
Actually, there are some more notifications we need to handle. This isn't an error though, just a message.

**Comment by nbfalcon** [comment]
Closing in favour of #398.
