### ISSUE TITLE
How to config python path?

### ISSUE THREAD

**Issue by Super151804** [emacs-lsp/dap-mode#405]
I checked my exec-path and python-shell-interpreter. I wanna use python3.8, but dap uses /usr/bin/python, which is python2.7. Could you please tell me how to solve it?

**Comment by nbfalcon** [comment]
```emacs-lisp
(setq dap-python-executable "python3.8")
```
(assuming "python3.8" is in your path)

**Comment by Super151804** [comment]
> ```emacs-lisp
> ```emacs-lisp
> (setq dap-python-executable "python3.8")
> ```
> 
> 
> (assuming "python3.8" is in your path)
> ```

thank you!
