### ISSUE TITLE
How to compile c++ file with dap?

### ISSUE THREAD

**Issue by IllustratedMan-code** [emacs-lsp/dap-mode#421]
Hello! This is probably a stupid question but I couldn't find it anywhere in the documentation. How exactly would I compile a c++ file with the breakpoints provided by dap? It has happened before where when i use dap-debug there suddenly is an executable with the same name as the file but I have no idea how it happened. Any help would be appreciated.

**Comment by yyoncho** [comment]
You are supposed to compile it by yourself (check M-x compile, M-x projectile-compile). Then you can use dap-mode to debug it. Here it is a guide - https://emacs-lsp.github.io/lsp-mode/tutorials/CPP-guide/
