### ISSUE TITLE
dap-debug on java doesn't find main class and includes a strange ^M on class name

### ISSUE THREAD

**Issue by emuvs** [emacs-lsp/dap-mode#424]
When I start a dap-debug with default java configuration I got the error:

Error: Could not find or load main class pin.BaseBox
Caused by: java.lang.ClassNotFoundException: pin.BaseBox^M

**Comment by yyoncho** [comment]
Can you provide a bit more information about your setup?

**Comment by emuvs** [comment]
Sure:
The project I was trying to debug is: https://github.com/emuvs/basebox
My emacs setup is on: https://github.com/emuvs/dotfiles
I was on a Windows 10 with OpenJDK 14

**Comment by yyoncho** [comment]
I am unable to build that project - 

> [ERROR] Failed to execute goal on project BaseBox: Could not resolve dependencies for project br.com.pointel:BaseBox:jar:0.1.0: Failure to find br.com.pointel:JarBox:jar:0.1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by emuvs** [comment]
Right, this project uses: https://github.com/emuvs/jarbox

I'm new in the Emacs world, is there some logger dump I could call?

I'm using GNU Emacs 27.1 from installer of 64b.

**Comment by emuvs** [comment]
Ok, I found out that is something about the enable-preview and the JDK 14, and is not about the dap-mode because in VS Code same we got same behavior. So I'll rewrite and remove the code that's make usage of preview features.
