### ISSUE TITLE
QUESTION: dap-python and multi-threading

### ISSUE THREAD

**Issue by gianscarpe** [emacs-lsp/dap-mode#425]
Hi, thanks for the great effort you put into this project! I've a question. If I launch a python script that uses multi-thread, dap failes with 
```
  File "/home/gianlucascarpellini/.local/share/virtualenvs/pytorch-ewc-ONpLtI3f/lib/python3.7/site-packages/ptvsd/daemon.py", line 145, in start                                                           
    raise RuntimeError('already started')    
```
In my case, it's a pytorch DataLoader.
I think I should specify some `subprocess` property in the template, but I cannot figure out how to do that. Can you help me?

**Comment by nbfalcon** [comment]
Perhaps this will work in `debugpy`? Evaluate (add to your config):
```emacs-lisp
(setq dap-python-debugger 'debugpy)
```
And `pip3 install debugpy`.

**Comment by gianscarpe** [comment]
Thank you :)

**Comment by SebastianCallh** [comment]
Are there any other settings relevant to this issues? I got the same error and tried `debugpy` but it simpy hangs forever for me.
