### ISSUE TITLE
dap-go-setup doesn't pull down vscode extension

### ISSUE THREAD

**Issue by davidkrauser** [emacs-lsp/dap-mode#445]
Hi dap-mode contributors, first off: thank you for all the work you do on dap-mode. I find it incredibly useful :-)

To the issue at hand:

Up until recently, I've been a happy user of dap-mode's golang features that rely on a local copy of the go vscode extensions. Yesterday, I installed dap-mode on a new machine, and it appears that dap-go-setup is no longer working.

When I run dap-go-setup, I expect the go vscode extension to be downloaded into the `~/.emacs.d/.extension/vscode` dir; however, after running the command, I end up with an empty folder under `vscode`.

I tried to manually download the extension, but I could not find a download for the version that dap-mode uses. I think that it uses `0.15.0` (according to the definition in dap-go-setup), but the go vscode extension doesn't have any downloads for that version. They also don't have that version tagged in their git repository.

I also tried changing `0.15.0` to the latest `0.22.1` to see if that version could be downloaded by dap-go-setup. That also resulted in an empty extension dir.

Any ideas on what's going wrong? Is there a problem with my setup perhaps? Or a problem with how I'm running these things?

I'm using dap-mode-20210222.419 if that helps :-)

**Comment by yyoncho** [comment]
My guess is that you don't have unzip, can you check that?

**Comment by davidkrauser** [comment]
unzip is installed :-/

**Comment by yyoncho** [comment]
@davidkrauser can you check what you have in `/tmp` folder? I noticed that sometimes the marketplace rejects the calls to provent DoS attack.

**Comment by yyoncho** [comment]
But in any case you should be able to unzip it and then adjust `dap-go-debug-path`  to point to your location. Also check this: https://github.com/emacs-lsp/dap-mode/pull/444

**Comment by davidkrauser** [comment]
@yyoncho thanks! That was the culprit:

```
{"$id":"1","innerException":null,"message":"Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on why your request was blocked, see the topic \"Rate limits\" on the Microsoft Web site (https://go.microsoft.com/fwlink/?LinkId=823950).","typeName":"Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, Microsoft.TeamFoundation.Framework.Server","typeKey":"RequestBlockedException","errorCode":0,"eventId":3000}
```

Any ideas on how to get around this? Or do I just need to wait?

**Comment by yyoncho** [comment]
> Any ideas on how to get around this? 

Manual installation, just make sure that dap-go-debug-path is pointing to the right thing.

**Comment by nbfalcon** [comment]
@yyoncho we should also add some better warning to the installation function. Currently it always claims success, no matter what.

**Comment by yyoncho** [comment]
> @yyoncho we should also add some better warning to the installation function. Currently it always claims success, no matter what.

Yes, I was planning to have that as part of the update PR or after the PR is merged.
