### ISSUE TITLE
Export locals as JSON

### ISSUE THREAD

**Issue by bobrowadam** [emacs-lsp/dap-mode#452]
Hi :)
Is it possible to copy/export 'dap-ui-locals' values as JSON (or any other acceptable data structure)?
The reason I'm asking is that long values are not fully shown.
Thanks!

**Comment by yyoncho** [comment]
What I use is increasing `dap-ui-variable-length` and then I show the locals in fullscreen(you can use switch-to-buffer and select the locals buffer).

**Comment by nbfalcon** [comment]
@yyoncho I propose that we remove truncation. If the variable is too long, it will be cut off anyway, and one can view it entirely using e.g. `end-of-line`.

**Comment by yyoncho** [comment]
@nbfalcon both vscode and emacs elisp debugging have truncation. IMHO having long lines in the locals will pretty much kill emacs considering that we update the locals on each step. See also https://github.com/emacs-lsp/dap-mode/issues/322

**Comment by bobrowadam** [comment]
OK thanks, using `dap-ui-variable-length` is a valid solution. If I would like to implement an export function, would that be part of dap or treemacs?

**Comment by nbfalcon** [comment]
@bobrowadam part of `dap-ui` I'd say.
