### ISSUE TITLE
dap-mode does not pick up launch.json from project folder I

### ISSUE THREAD

**Issue by mustiboost** [emacs-lsp/dap-mode#455]
Hi guys,
I have been trying to get dap-mode to work with lsp-mode to debug c++ code for well over a week now and I am at my wit's end. According to the instructions on the lsp-mode github page, I should be able to just drop a launch.json file in my project folder and then `M-x dap-debug` and I should be able to see my debug configuration. But it does not show up at all. I followed the instructions on https://emacs-lsp.github.io/lsp-mode/tutorials/CPP-guide/ exactly and everything else works. I even used the sample launch.json config on that page. Even when use `M-x dap-debug-edit` and try to debug that way I just get an error code (126). Any ideas?

**Comment by yyoncho** [comment]
Check if you have another launch.json in $ROOT/.vscode. Also check if the project root is the right one - use M-x lsp-describe-session.

**Comment by mustiboost** [comment]
Thanks! M-x lsp-describe-session showed my home folder (on Mac) as my root folder for all my projects for some reason. I deleted the .lsp-session-v1 file from .emacs.d and I was able to set the correct project root folder. Launch.json was picked up this time, but when I tried `dap-debug` I got following error: 
`Debug session process exited with status: exited abnormally with code 126`  
I tried both gdb and lldb in launch.json with the same result. I am literally using the same launch.json file as lsp-mode recommends, I just changed the path and name of the executable.  Any idea what "code 126" is and what the issue may be?

**Comment by yyoncho** [comment]
Check the corresponding stderr buffer. (Most likely you are missing mono, I have to add that to the tutorial).

**Comment by mustiboost** [comment]
I have mono but apparently there is a permissions issue: 
".emacs.d/.extension/vscode/cpptools/extension/debugAdapters/mono.osx: Permission denied" (from stderr buffer). I just checked and it is not executable. Should I make it executable? It was downloaded with those permissions automatically.

**Comment by yyoncho** [comment]
Yes. We do change permissions in the code but apparently, for Mac we have to do that for more files.

**Comment by mustiboost** [comment]
Ok, done that. Still did not work with lldb in launch.json. Then tried gdb and at least the debugging interface came up, but then it crashes again and disappears. Here is stderr: 

 Initialize request failed: Unable to start debugging. There was an error starting the pipe program '/Users/xxx/.emacs.d/.extension/vscode/cpptools/extension/debugAdapters/lldb-mi/bin/lldb-mi'. ApplicationName='/Users/xxx/.emacs.d/.extension/vscode/cpptools/extension/debugAdapters/lldb-mi/bin/lldb-mi', CommandLine='--interpreter=mi', CurrentDirectory='/Users/xxx/code/c++/testcode', Native error= Access denied
Warning (emacs): Initialize request failed: Unable to start debugging. GDB exited unexpectedly with exit code 134 (0x86).
Warning (emacs): Initialize request failed: Unable to start debugging. GDB exited unexpectedly with exit code 134 (0x86)

**Comment by yyoncho** [comment]
> '/Users/xxx/.emacs.d/.extension/vscode/cpptools/extension/debugAdapters/lldb-mi/bin/lldb-mi'. ApplicationName='/Users/xxx/.emacs.d/.extension/vscode/cpptools/extension/debugAdapters/lldb-mi/bin/lldb-mi', CommandLine='--interpreter=mi', CurrentDirectory='/Users/xxx/code/c++/testcode', Native error= Access denied

I am not familiar with Mac, seems like there is another access issue.

**Comment by mustiboost** [comment]
Interesting, I guess people with Macs just weren't able to debug c++ at all with lsp-mode so far. We'll have to change that as lsp-mode is really, really great. I guess for debugging there is always GUD or the command line, but having dap would be nice.  I'll investigate further and see what may be the problem on the Mac. I'll report back after I research a bit. Time to go to bed now. :)  (by the way, both gdb and lldb work fine on the command line and gdb works fine with GUD, so it's not an issue with the actual debuggers).

**Comment by yyoncho** [comment]
I know for sure that @danielmartin  is using lldb-vscode adapter on mac.

**Comment by danielmartin** [comment]
I have checked the tutorial instructions from a clean Emacs on macOS and there's two things to mention or to automatically fix:

- As you said, chmod +x .emacs.d/.extension/vscode/cpptools/extension/debugAdapters/mono.osx
- Also chmod +x .emacs.d/.extension/vscode/cpptools/extension/debugAdapters/lldb-mi/bin/lldb-mi
- Change `"MIMode": "gdb"` to `"MIMode": "lldb"` in `launch.json`. Most people on Mac has LLDB installed instead of GDB.

With that, I'm able to launch the debugged Emacs from inside Emacs and break in `insert-char`, for example.

@mustiboost Could you check if that fixes the problem for you?

**Comment by yyoncho** [comment]
@danielmartin thank you, I will update the installation to perform these chmod's + I will add mac section in the tutorial.

**Comment by mustiboost** [comment]
Yes, chmod +x for lldb-mi is necessary to fix the problem. Now lldb works! However, for people who are used to just starting a debugging session on the command line and/or on GUD (or even vscode) and seeing a debugger and *then* setting breakpoints and running the debugger, things are a bit confusing.  It would be a good idea to tell people to click on the left margin of the line where you want your breakpoint and *then* do M-x dap-debug and start the session. Otherwise the debugger quits with "killed" and exit code "9", very cryptic. It makes it look like dap-debug isn't working.  

As for gdb, it's still not working with dap. I installed and code signed gdb and it's working from the command line and with GUD. However, even on the command line I get a bunch of warnings when starting a debugging session, setting breakpoints and entering "r": 
```shell
warning: `/BuildRoot/Library/Caches/com.apple.xbs/Binaries/Libc_darwin/install/TempContent/Objects/Libc.build/libsystem_darwin.dylib.build/Objects-normal/x86_64/bsd.o': can't open to read symbols: No such file or directory.
warning: `/BuildRoot/Library/Caches/com.apple.xbs/Binaries/Libc_darwin/install/TempContent/Objects/Libc.build/libsystem_darwin.dylib.build/Objects-normal/x86_64/darwin_vers.o': can't open to read symbols: No such file or directory.
warning: `/BuildRoot/Library/Caches/com.apple.xbs/Binaries/Libc_darwin/install/TempContent/Objects/Libc.build/libsystem_darwin.dylib.build/Objects-normal/x86_64/dirstat.o': can't open to read symbols: No such file or directory.
warning: `/BuildRoot/Library/Caches/com.apple.xbs/Binaries/Libc_darwin/install/TempContent/Objects/Libc.build/libsystem_darwin.dylib.build/Objects-normal/x86_64/dirstat_collection.o': can't open to read symbols: No such file or directory.
warning: `/BuildRoot/Library/Caches/com.apple.xbs/Binaries/Libc_darwin/install/TempContent/Objects/Libc.build/libsystem_darwin.dylib.build/Objects-normal/x86_64/err.o': can't open to read symbols: No such file or directory.
warning: `/BuildRoot/Library/Caches/com.apple.xbs/Binaries/Libc_darwin/install/TempContent/Objects/Libc.build/libsystem_darwin.dylib.build/Objects-normal/x86_64/exception.o': can't open to read symbols: No such file or directory.
warning: `/BuildRoot/Library/Caches/com.apple.xbs/Binaries/Libc_darwin/install/TempContent/Objects/Libc.build/libsystem_darwin.dylib.build/Objects-normal/x86_64/init.o': can't open to read symbols: No such file or directory.
warning: `/BuildRoot/Library/Caches/com.apple.xbs/Binaries/Libc_darwin/install/TempContent/Objects/Libc.build/libsystem_darwin.dylib.build/Objects-normal/x86_64/mach.o': can't open to read symbols: No such file or directory.
warning: `/BuildRoot/Library/Caches/com.apple.xbs/Binaries/Libc_darwin/install/TempContent/Objects/Libc.build/libsystem_darwin.dylib.build/Objects-normal/x86_64/stdio.o': can't open to read symbols: No such file or directory.
warning: `/BuildRoot/Library/Caches/com.apple.xbs/Binaries/Libc_darwin/install/TempContent/Objects/Libc.build/libsystem_darwin.dylib.build/Objects-normal/x86_64/stdlib.o': can't open to read symbols: No such file or directory.
warning: `/BuildRoot/Library/Caches/com.apple.xbs/Binaries/Libc_darwin/install/TempContent/Objects/Libc.build/libsystem_darwin.dylib.build/Objects-normal/x86_64/string.o': can't open to read symbols: No such file or directory.
warning: `/BuildRoot/Library/Caches/com.apple.xbs/Binaries/Libc_darwin/install/TempContent/Objects/Libc.build/libsystem_darwin.dylib.build/Objects-normal/x86_64/variant.o': can't open to read symbols: No such file or directory.
```
Not sure if this has anything to do with gdb not working with dap. Like I said, GUD has no problems with gdb. Also, the message buffer shows an exit code of 134 when using gdb.

**Comment by danielmartin** [comment]
mustiboost ***@***.***> writes:

> Yes, chmod +x for lldb-mi is necessary to fix the problem. Now lldb
> works! However, for people who are used to just starting a debugging
> session on the command line and/or on GUD (or even vscode) and seeing
> a debugger and *then* setting breakpoints and running the debugger,
> things are a bit confusing.  It would be a good idea to tell people to
> click on the left margin of the line where you want your breakpoint
> and *then* do M-x dap-debug and start the session. Otherwise the
> debugger quits with "killed" and exit code "9", very cryptic. It makes
> it look like dap-debug isn't working.

I think that's good feedback for the documentation, thanks. It applies
to every debug adapter.

>
> As for gdb, it's still not working with dap. I installed and code
> signed gdb and it's working from the command line and with
> GUD. However, even on the command line I get a bunch of warnings when
> starting a debugging session, setting breakpoints and entering "r":
[...]
> Not sure if this has anything to do with gdb not working with
> dap. Like I said, GUD has no problems with gdb. Also, the message
> buffer shows an exit code of 134 when using gdb.

Is there any problem apart from the warnings?

I don't use gdb or have a system with it installed at hand, but I would
check if it works in Visual Studio Code. Just so we know if the problem
is in dap-mode or in gdb/debug adapter.

**Comment by mustiboost** [comment]
> I think that's good feedback for the documentation, thanks. It applies to every debug adapter.

No problem! :) There are a couple more things in the documentation we could improve to make it less confusing, but I'll probably open a new issue for that. 

> Is there any problem apart from the warnings? I don't use gdb or have a system with it installed at hand, but I would check if it works in Visual Studio Code. Just so we know if the problem is in dap-mode or in gdb/debug adapter.

No, there is no other issue with gdb when used from the command line or through GUD. At least not so far for basic debugging. I haven't tried debugging multithreaded applications or anything more demanding...yet. 

Alright, I went ahead and tested gdb in vscode and got the exact same issue (it's not working) and error: 
![Screen Shot 2021-03-31 at 6 09 17 PM](https://user-images.githubusercontent.com/6622621/113240041-bcfac980-9260-11eb-9292-afdd09b63c51.png)

I guess I could open an issue with the vscode maintainers. What do you think could possibly be the issue given that gdb on the mac works with GUD and on the command line?

**Comment by danielmartin** [comment]
I'm not sure what the issue may be. There was an issue in the vscode-cpptools repository that seems similar to yours: https://github.com/microsoft/vscode-cpptools/issues/5256

With 

```
"logging": {
   "engineLogging": true
}
```

in your `launch.json` you'll see more information about the problem.

**Comment by yyoncho** [comment]
PR for permission issues at https://github.com/emacs-lsp/dap-mode/pull/473
