### ISSUE TITLE
Dap-mode python does not execute or stop on breakpoints

### ISSUE THREAD

**Issue by ReggieMarr** [emacs-lsp/dap-mode#456]
I am running the latest dap-mode using the following as a test:
```

#!/usr/bin/env python3


if __name__ == '__main__':
    myvar = 5
    print("My var is {}".format(myvar))
```
```
❯ python --version
Python 3.8.5
```
pyls is my language serve and my debug template is as follows:

```

(dap-register-debug-template
  "Python :: Run file (buffer)"
  (list :type "python"
        :args ""
        :cwd nil
        :module nil
        :program nil
        :request "launch"
        :name "Python :: Run file (buffer)"))
```

My issue is that when trying to enter a debugging session I never hit the breakpoint (set at myvar=5) and the only message I get is "No message handler for process"

I'm a bit stuck on this one and it's especially odd since it had been working until recently. 

Any help is much appreciated.

**Comment by ReggieMarr** [comment]
It seems as though part of the problem was I was using ptsvd rather than debugpy. Once I switched to debugpy I now the following error: `error in process filter: Symbols Value as variable is void: debug-session`. This seems to come from within `dap-start-debugging-noexpand` but when I step though it debug-session seems to be set properly.
Is anyone else having this issue ? And if not how might I try to get to a known working state ?

**Comment by yyoncho** [comment]
> error: `error in process filter: Symbols Value as variable is void: debug-session`

can you provide callstack?

**Comment by yyoncho** [comment]
try deleting and installing dap-mode. To me, it sounds like you have compiled dap-mode with lexical binding being off.

**Comment by ReggieMarr** [comment]
> try deleting and installing dap-mode. To me, it sounds like you have compiled dap-mode with lexical binding being off.

I deleted ~/.emacs.d (I'm using doom) and now I'm reinstalling doom which will rebuild dap-mode for me. I'll provide a callstack if that doesn't fix it.

How might I check that dap-mode is compiled with lexical binding off?

**Comment by yyoncho** [comment]
can you provide the call stack first?

**Comment by ReggieMarr** [comment]
> can you provide the call stack first?

I had already started reinstalling when you suggested that. looks like I can used dap-mode again however I do still see the original `No message handler for process` pop up momentarily.

Is there any additional debugging I should try before closing this out ?

**Comment by yyoncho** [comment]
> `No message handler for process` pop up momentarily.

You can ignore that.
