### ISSUE TITLE
Debugging Python with Poetry and Pytest

### ISSUE THREAD

**Issue by vascoferreira25** [emacs-lsp/dap-mode#461]
Hi,

I've configured a template to debug a Python project using Poetry and Pytest. It only works if the `venv` is in the project root, and to do that you need to change the Poetry config with: `poetry config --local virtualenvs.in-project true` and then run `poetry install`. I don't know if this is the correct way to do this, but it works. I don't know how I should change this to also work with `debugpy`. 

This is not as much as an issue as it is just a template for anyone else to use Poetry and Pytest when debugging a Python project.

```lisp
(defun dap-poetry--populate-start-file-args (conf)
  "Populate CONF with the required arguments."
  (let* ((python-executable (dap-python--pyenv-executable-find dap-python-executable))
         (python-args (plist-get conf :args))
         (program (or (plist-get conf :target-module)
                      (plist-get conf :program)
                      (buffer-file-name)))
         (module (plist-get conf :module))
         (debugger (plist-get conf :debugger)))
    ;; These are `dap-python'-specific and always ignored.
    (cl-remf conf :debugger)
    (cl-remf conf :target-module)
    (plist-put conf :cwd (lsp-workspace-root))

    ;; ptvsd
    (let ((host "localhost")
          (debug-port (dap--find-available-port)))
      ;; support :args ["foo" "bar"]; NOTE: :args can be nil; however, nil is
      ;; a list, so it will be mapconcat'ed, yielding the empty string.
      (when (sequencep python-args)
        (setq python-args (mapconcat #'shell-quote-argument python-args " ")))
      ;; ignored by ptsvd anyway
      (cl-remf conf :module)
      (cl-remf conf :args)
      (plist-put conf :program-to-start
                 (format "poetry run python -m ptvsd --wait --host %s --port %s%s"
                         host
                         debug-port
                         (if module (concat " -m " (shell-quote-argument module)) "")))
      (plist-put conf :debugServer debug-port)
      (plist-put conf :port debug-port)
      (plist-put conf :hostName host)
      (plist-put conf :host host))
    conf))

(dap-register-debug-provider "poetry" 'dap-poetry--populate-start-file-args)

;; Create a new debugging template to use with Poetry and Pytest
(dap-register-debug-template
 "Poetry Pytest Debugging"
 (list :type "poetry"
       :args ""
       :program nil
       :cwd ""
       :module "pytest"
       :request "launch"
       :name "Python :: Poetry Pytest"))
```

**Comment by jtpavlock** [comment]
Don't know if you tried [this workaround](https://github.com/emacs-lsp/dap-mode/issues/126#issuecomment-754282754), but I'm using poetry and pytest and it worked for me.

**Comment by holocronweaver** [comment]
@jtpavlock @vascoferreira25 Could someone provide a code example of how to use [the aforementioned workaround](https://github.com/emacs-lsp/dap-mode/issues/126#issuecomment-754282754) with poetry? 

AFAICT tell only the solution by @vascoferreira25 works. Adding a prefix to the debug command should really be a field in the dap config.

**Comment by nsulmol** [comment]
@holocronweaver I am able to use the aforementioned workaround without issues. With doom-emacs, I hae the following in my config.el:

`;; dap-mode settings
(after! dap-mode
  (setq dap-python-debugger 'debugpy)
  ;; Feed the path to our venv to dap-mode. Note that dap-mode
  ;; does not do this by default, and expects the user to do
  ;; so via their preferred method.
  (defun dap-python--pyenv-executable-find (command)
    (with-venv (executable-find command)))
  )
`
If not using doom-emacs, I assume you would use 'with-eval-after-load' instead of 'after!', to set these variables after dap-mode has been loaded.

Do you still have this issue?
