### ISSUE TITLE
Docker remote debugging support

### ISSUE THREAD

**Issue by factyy** [emacs-lsp/dap-mode#463]
Hi everyone!

I want to help (if I have the time though) with dockerized debugging (both an app and a debug server residing inside a container). Any tips or hints? 

Edit: this is a part of my `lsp-mode` wishlist  suggestions: https://github.com/emacs-lsp/lsp-mode/issues/515#issuecomment-820338278

**Comment by yyoncho** [comment]
I will do it like this:
1. Change dap-mode to be able to start remote debug adapter and communicate with it.
2. Set dap-print-io to t and inspect that we are sending the correct local path to the debug adapter. We can put in the debug session function which translates the paths or we can eventually use that same function but from the `lsp--client` that is used by the current fine. I am not sure which approach will be better.

**Comment by milochadam** [comment]
There will also be a need to store currently used template somewhere, right? Since the user might define various mappings for different templates.

**Comment by yyoncho** [comment]
@milochadam yes.

**Comment by factyy** [comment]
@yyoncho I started to work on this feature at last. Decided to stick with option 2: using `lsp--client` features (`lsp--path-to-uri` with DAP mode changed to `"uri"` from `"path"` in the initialization request)

**Comment by factyy** [comment]
And quickly got a problem that not all debug providers support `URI`s... 
Ok, we need new translation functions (the ones provided by `lsp-mode` work only with `URI`s)

**Comment by yyoncho** [comment]
@factyy we can transform to uri and back I guess.

**Comment by factyy** [comment]
Filed a PR #559, closing this issue
