### ISSUE TITLE
Inconsistency in the debug configuration type names between VSCode and dap-mode

### ISSUE THREAD

**Issue by MayushKumar** [emacs-lsp/dap-mode#467]
The names used for some adapters for `dap-register-debug-provider` are not the same as the ones used by VSCode. This hinders the usage of the same `launch.json` file (with the configurations of these adapters) with both dap-mode and VSCode. Some of the ones that I have encountered are as follows:

| Adapter | VSCode | dap-mode|
| --- | :---: | :---: |
| CodeLLDB | `lldb`| `codelldb` |
| Native Debug(lldb) | `lldb-mi` | `lldb` |

I suggest that these should be refactored to match the ones used by VSCode.

**Comment by ztlevi** [comment]
Codelldb seems to be a much more popular one. Can we make lldb as default for codelldb?

Is it ok just change the following two locations?
https://github.com/emacs-lsp/dap-mode/blob/master/dap-codelldb.el#L57
https://github.com/emacs-lsp/dap-mode/blob/master/dap-gdb-lldb.el#L104

**Comment by yyoncho** [comment]
I guess we can go and apply the changes as suggested in the table.

**Comment by ztlevi** [comment]
sounds good. Thanks
