### ISSUE TITLE
Start dap-debug failed with exit code 127

### ISSUE THREAD

**Issue by stskyblade** [emacs-lsp/dap-mode#468]
I try to debug a binary file `/home/stskyblade/Project/c_data_struct/Debug/c_data_struct`. When I run `SPC d d d`, dap-debug failed to run. 

Output message in `*Message*` buffer:
```
dap--send-message: Process Debug Emacs not running
Debug session process exited with status: exited abnormally with code 127
```

My dap template:
```elisp
(dap-register-debug-template
  "cpptools::Run Configuration"
  (list :type "cppdbg"
        :request "launch"
        :name "cpptools::Run Configuration"
        :MIMode "gdb"
        :program "/home/stskyblade/Project/c_data_struct/Debug/c_data_struct"
        :cwd "/home/stskyblade/Project/c_data_struct"))
```

I have also tried to add a launch.json file:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Emacs",
            "type": "cppdbg",
            "request": "launch",
            "program": "/home/stskyblade/Project/c_data_struct/Debug/c_data_struct",
            "args": ["-q"],
            "stopAtEntry": false,
            "cwd": "/home/stskyblade/Project/c_data_struct",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb"
        }
    ]
}

```

I think I need a step-by-step documention about how to use dap-mode.

**Comment by yyoncho** [comment]
Maybe this: https://emacs-lsp.github.io/lsp-mode/tutorials/CPP-guide/ ?

What do you usee in the stderr buffer?

**Comment by stskyblade** [comment]
Stderr buffer says something like ".emacs.d/extension/vscode/cpptools/.... missing", but I didn't save that message.
I tried `M-x dap-cpptools-setup`, and it works. I can use Emacs like any other debuggers now.
Thank you for your help.

There is another problem:
`&"warning: GDB: Failed to set controlling terminal: Operation not permitted\n"` shows on the top of buffer `*Debug Emacs -cppdbg: c_data_struct`. Does it matter, and how to fix it ?

**Comment by yyoncho** [comment]
IDK, I am not familiar with that adapter and with gdb in general. May be it is related to :externalTerminal flag. (you may install vterm which will be picked by dap mode when emacs is supposed to start the app to debug).
