### ISSUE TITLE
Auto expand variables in dap-ui-locals

### ISSUE THREAD

**Issue by skybert** [emacs-lsp/dap-mode#47]
One thing I liked about the old JDIbug, was that it auto expanded the locals view and it would significantly improve the user experience with `dap-mode` IMHO. 

I wish I could have dap-mode:
- expand all objects in the `dap-ui-locals` view
- except objects where the `toString` representation listed in the node (header) is normally sufficient, like `String`s, i normally only want to see the string "foo" in the collapsed node header, I don't need to see the internal data structure of `java.lang.String`.

**Comment by yyoncho** [comment]
Expand at what level?

**Comment by skybert** [comment]
I've got this method where the debugger stops at the `return`:
```
  public URI toURI(final String pName, final List<?> pParts) {
    return getFoo(getBar(pName), pParts, false);
  }
```

The dap-ui-locals look like this:
```
[+] Local
  [-] pName="checksum" (id=200)
  [-] pParts=Arrays$ArrayList (id=201)
  [-] this=LockURIHandler (id=202)
```

What I want is to have it expand `pParts` which holds the interesting bits (`pName` is fine as it is since it's a `String` and `this` is not a local so that's fine too):

```
[+] Local
  [-] pName="checksum" (id=200)
  [+] pParts=Arrays$ArrayList (id=201)
    [-] MAX_ARRAY_SIZE=2147483639
    [-] serialVersionUID=-2764017481108945198
    [+] a=Serializable[3] (id=204)
      [-] 0="container" (id=206)
      [-] 1=Integer (id=207)
      [-] 2="���V=6}���[4f" (id=208)
    [-] modCount=0
  [-] this=LockURIHandler (id=202)
```

IDEA does some prettying up with how it represents lists and arrays, it doesn't display the internal array structure (`Serializable[3]`) but that's ok the way it is. It's this auto expansion of interesting bits which is what I want:

- expand lists
- expand arrays
- expand objects (except `String`, `Integer` and so on, I `java.lang.*` I suppose)

**Comment by yyoncho** [comment]
Yeah, make sense. We first need to test with the latest java adapter since this might have been fixed on the server. You could use tree-mode-expand-level and pass the levels that you want to expand but this wont cover the string/Integer thing which would require changes to dap-mode. I am planning to redo the controls using treemacs as tree renderer and I may include the option to pass string formatter.

**Comment by yyoncho** [comment]
Played a bit with the code and you could remove the children of String/Integer/Boolean via following function:

```
(defun dap-ui--render-variable (debug-session variable)
  "Render VARIABLE for DEBUG-SESSION."
  (-let* (((&hash "variablesReference" variables-reference
                  "value" value
                  "name" name
                  "type" type
                  "indexedVariables" indexed-variables) variable)
          (has-children? (and variables-reference (not (zerop variables-reference))
                              (not (-contains? '("String" "Integer" "Boolean") type))))
          (face (if has-children? 'dap-ui-locals-variable-face 'dap-ui-locals-variable-leaf-face)))
    `(tree-widget
      :node (push-button :format "%[%t%]\n"
                         :tag ,(format "%s=%s" name value)
                         :button-face ,face)
      :open nil
      :indexed-variables ,indexed-variables
      :variables-reference ,variables-reference
      :dynargs ,(when has-children?
                  (apply-partially 'dap-ui--load-variables debug-session))
      ,@dap-ui-icons-variable)))
```

I hope this will improve your experience until the full fix is in.

**Comment by skybert** [comment]
Hi @yyoncho , thanks for your reply and suggestions. I've replaced the `dap-ui--render-variable` function, but I see no difference in behaviour. How do I put `tree-mode-expand-level` to use to see the desired effect?

**Comment by yyoncho** [comment]
The change will disable the option to expand the String/Boolean, etc types. Then you could go to the root of the locals list and you could do M-2 M-x tree-mode-expand-level where 2 is the number of levels which will be expanded.

**Comment by lane-s** [comment]
How difficult would it be to have the locals tree persist between steps? For example, if I expanded some tree and then ran `dap-next`, would it be possible to leave that tree expanded if the variable is still in scope?

**Comment by yyoncho** [comment]
I am planning to rewrite the tree view controls to use treemacs as a treeview renderer. It has this functionality and it will work out of the box.
