### ISSUE TITLE
"No Content-Length header" thrown after dap-debug

### ISSUE THREAD

**Issue by Deanseo** [emacs-lsp/dap-mode#471]
When calling `dap-debug`, I get no debug session with the following error: 

> "No Content-Length header"

This error seems to be generated in a *Lisp* level in `dap-mode.el:598`.

I am using `lldb-vscode` and this exact issue happens on both **MacOS Catalina** and **RHEL7** so I am suspecting that I've probably configured something wrong myself but with that single error message like that I hardly can get any hints regarding what I possibly screwed up.

I did the configuration given this [link](https://github.com/llvm/llvm-project/blob/d480f968ad8b56d3ee4a6b6df5532d485b0ad01e/lldb/tools/lldb-vscode/README.md).

`lldb` is installed on both OS and I have no problem in debugging with the bare `lldb` in terminal, which I normally do.

On RHEL7, I completely re-built `llvm` with all its subsequent projects such as `compiler-rt` and `libcxxabi` and installed it but the result is the same.

Any hint for a workaround would be appreciated.

**Comment by yyoncho** [comment]
Can you trace function `dap--parser-read`  via M-x trace-function and post outcome?

**Comment by Deanseo** [comment]
@yyoncho The result goes as follows:

> ======================================================================
> 1 -> (dap--parser-read #s(dap--parser nil nil nil nil nil nil 0 nil) "Stop hook #1 added.
> Content-Length: 1153
> 
> {\"body\":{\"exceptionBreakpointFilters\":[{\"default\":false,\"filter\":\"cpp_catch\",\"label\":\"C++ Catch\"},{\"default\":false,\"filter\":\"cpp_throw\",\"label\":\"C++ Throw\"},{\"default\":false,\"filter\":\"objc_catch\",\"label\":\"Objective C Catch\"},{\"default\":false,\"filter\":\"objc_throw\",\"label\":\"Objective C Throw\"},{\"default\":false,\"filter\":\"swift_catch\",\"label\":\"Swift Catch\"},{\"default\":false,\"filter\":\"swift_throw\",\"label\":\"Swift Throw\"}],\"supportTerminateDebuggee\":true,\"supportsCompletionsRequest\":false,\"supportsConditionalBreakpoints\":true,\"supportsConfigurationDoneRequest\":true,\"supportsDelayedStackTraceLoading\":true,\"supportsEvaluateForHovers\":true,\"supportsExceptionInfoRequest\":true,\"supportsExceptionOptions\":true,\"supportsFunctionBreakpoints\":true,\"supportsGotoTargetsRequest\":false,\"supportsHitConditionalBreakpoints\":true,\"supportsLoadedSourcesRequest\":false,\"supportsModulesRequest\":false,\"supportsRestartFrame\":false,\"supportsRestartRequest\":false,\"supportsSetVariable\":true,\"supportsStepBack\":false,\"supportsStepInTargetsRequest\":false,\"supportsValueFormattingOptions\":true},\"command\":\"initialize\",\"request_seq\":1,\"seq\":0,\"success\":true,\"type\":\"response\"}")
> 1 <- dap--parser-read: !non-local\ exit!

Please don't mind asking me to provide more information on this since I'm desperate to fix this issue. :)

**Comment by yyoncho** [comment]
This is the issue - `Stop hook #1 added.` we are failing to parse that. I will post a workaround for now.

**Comment by yyoncho** [comment]
Putting:

```
  (setq out (s-replace-regexp "Stop hook #[[:digit:]]+ added." 
                              ""
                              out))
```
As a first line in should be sufficient to fix the issue.

**Comment by Deanseo** [comment]
@yyoncho 

Ohhhhhhh, okay. I get it.

So the problem is that I have many tweaks in `~/.lldbinit` with a hook installed:

```
target stop-hook add
# some commands invoked every breakpoint
DONE

```
which prints:

> Stop hook #1 added

which can't be parsed by `dap--parser-read`.

**Comment by yyoncho** [comment]
So the issues are two: the debug adapter should not let that go to the stdout and the other issue is that dap-mode parser is not robust enough. FTR lsp-mode parser will handle that well, porting lsp-mode parser here we will be able to handle that message even with the garbage in the stdout.

**Comment by Deanseo** [comment]
I am closing this issue since we figured out the root cause and the workarounds are provided accordingly.

Fundamentally, we could resolve this issue by having `lldb-vscode` not let messages generated by installed hooks go to `stdout` and/or having `dap-mode`'s parser handle it more tight as mentioned by @yyoncho.

**Comment by Deanseo** [comment]
I am closing this issue since we figured out the root cause and the workarounds are provided accordingly.

Fundamentally, we could resolve this issue by having lldb-vscode not let messages generated by installed hooks go to stdout and/or having dap-mode's parser handle it more tight as mentioned by @yyoncho.
