### ISSUE TITLE
codelldb : support externalConsole

### ISSUE THREAD

**Issue by rileyrg** [emacs-lsp/dap-mode#478]
Would it be possible for codelldb to support externalConsole?

```
(dap-register-debug-template
           "Udemy codelldb"
           (list :type "codelldb"
                 :request "launch"
                 :name "Udemy codelldb"
                 :externalConsole "true"
                 :program "${workspaceFolder}/mainDebug"
                 :cwd "${workspaceFolder}"))
```

works fine with cppdbg:

```
          (dap-register-debug-template
           "gdb"
           (list :type "cppdbg"
                 :request "launch"
                 :name "gdb"
                 :MIMode "gdb"
                 :externalConsole "true"
                 :program "${workspaceFolder}/mainDebug"
                 :cwd "${workspaceFolder}"))
```

**Comment by yyoncho** [comment]
external console is implemented on the adapter side by sending event to dap-mode.

**Comment by rileyrg** [comment]
I can't pretend to even begin to understand what that means. It's not so important.

**Comment by yyoncho** [comment]
It works like that:
dap-mode: I want to run the program in the external terminal
debug adapter: Ok, I support that - here is what you have to start and I will automatically attach to it
dap-mode: starting the process in the external terminal

**Comment by rileyrg** [comment]
So it's a missing feature from https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb I guess you're saying. ok, thank. I tried lldb again (https://emacs-lsp.github.io/dap-mode/page/configuration/#lldb) . Spent a couple of hours carefully following the instructions, copying necessary .so files and got nowhere I'm afraid :( . I'll revert to gdb again. Cheers. Closing.
