### ISSUE TITLE
PHP: dap-php-setup Broken

### ISSUE THREAD

**Issue by Nazar65** [emacs-lsp/dap-mode#482]
Hello, I got well to use the dap-mode.
Thank you for your development.

When I ran dap-php-setup, the following message was displayed in the Messages buffer and the extension could not be installed.

```
Contacting host: marketplace.visualstudio.com:443
Wrote /tmp/ext8DxeSR.zip
[/tmp/ext8DxeSR.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/ext8DxeSR.zip or
        /tmp/ext8DxeSR.zip.zip, and cannot find /tmp/ext8DxeSR.zip.ZIP, period.
dap-php: Downloading done!

```

**Comment by yyoncho** [comment]
this happens if you run the command multiple times which triggers marketplace DOS protection

**Comment by Nazar65** [comment]
@yyoncho thanks, so i need to wait a little bit ?

**Comment by yyoncho** [comment]
Or you could download the package and unzip it according to `dap-php-debug-program`

**Comment by Nazar65** [comment]
@yyoncho but with that link it gives me an `vsix `file, not a zip ->  https://marketplace.visualstudio.com/_apis/public/gallery/publishers/felixfbecker/vsextensions/php-debug/1.16.0/vspackage

**Comment by yyoncho** [comment]
vsix is zip archive.

**Comment by Nazar65** [comment]
@yyoncho thanks a lot now it;s ok, with manually unzip and move that files :+1:

**Comment by johnhamelink** [comment]
Thanks for the advice in this thread, just to confirm for others who might be reading, the destination for the `vsix` package is in `dap-php-debug-path`

**Comment by zilti** [comment]
Why is this ticket closed? This feature is still broken, and it is not due to any DOS protection.
