### ISSUE TITLE
&"warning: GDB: Failed to set controlling terminal: Operation not permitted\n"

### ISSUE THREAD

**Issue by erusyd** [emacs-lsp/dap-mode#493]
I write a simple hello world test program main.c, when M-x dap-debug, I have the following layout:
![image](https://user-images.githubusercontent.com/1529102/126588208-c466727c-0748-4604-b397-fc09165cdd26.png)
Inside the red rectangular, we can see **&"warning: GDB: Failed to set controlling terminal: Operation not permitted\n"**.
How to get rid of this warning? Or can we remove the buffer inside red rectangular?

**Comment by yyoncho** [comment]
try with dap-auto-show-output

**Comment by erusyd** [comment]
> try with dap-auto-show-output

I tried with
(setq dap-auto-show-output nil)

the bottom buffer disappers, but the buffer inside red rectangular is still there.
![image](https://user-images.githubusercontent.com/1529102/126594046-3224b5f8-2c74-41a7-af79-26f63ad37f41.png)

**Comment by erusyd** [comment]
My launch.json is
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/a.out",
            "args": ["-q"],
            "stopAtEntry": true,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb"
        }
    ]
}
