### ISSUE TITLE
Display the `dap-ui-mode` menu only for sepecific major modes.

### ISSUE THREAD

**Issue by hongyi-zhao** [emacs-lsp/dap-mode#523]
The following is my `dap-mode` configuration:
```emacs-lisp
(use-package dap-mode
  :after lsp-mode
  :config
  (setq dap-auto-configure-features '(sessions locals breakpoints expressions repl controls tooltip)
           dap-python-debugger 'debugpy)
  (require 'dap-python))
```
If I first open a python file, and then open a LaTeX file in Emacs, the above configuration will still display the dap-ui-mode menu, as shown below:

![image](https://user-images.githubusercontent.com/11155854/136389747-1eefd5dd-7c60-425b-9950-10f2a818f269.png)

So, how to display the `dap-ui-mode` menu only for specific major modes?

**Comment by yyoncho** [comment]
> So, how to display the `dap-ui-mode` menu only for specific major modes?

There are no specific major modes. Debug commands are global.
