### ISSUE TITLE
Enable the regexp search support for `dap-mode`, say, in its `Locals` buffer.

### ISSUE THREAD

**Issue by hongyi-zhao** [emacs-lsp/dap-mode#525]
How to enable the regexp search support for `dap-mode`, say, in its `Locals` buffer with [`swiper`](https://github.com/abo-abo/swiper), as shown below?

![image](https://user-images.githubusercontent.com/11155854/136699111-75f8fc83-f540-47cd-b3bd-d1266383e104.png)

NB. See the relevant issue [here](https://github.com/abo-abo/swiper/issues/2474#issuecomment-939489017).

**Comment by yyoncho** [comment]
dap-mode buffers are regular buffers. Ask your question in the swipers repo.

**Comment by hongyi-zhao** [comment]
It seems that the regexp support has already been enabled, but I don't know how to match the little leading arrow shown on the `Locals` buffer:
![image](https://user-images.githubusercontent.com/11155854/136700485-46b6be87-0790-469f-8f61-ad0575aa783e.png)

**Comment by basil-conto** [comment]
> I don't know how to match the little leading arrows signs shown on the beginning of each line in the `Locals` buffer

`C-x 8 RET black right pointing triangle RET` etc.?

**Comment by hongyi-zhao** [comment]
> C-x 8 RET black right pointing triangle RET

So strange expression. How did you come up with such an odd pattern?

**Comment by basil-conto** [comment]
> > C-x 8 RET black right pointing triangle RET
> 
> So strange expression. How did you come up with such an odd pattern?

It's a well-known and widely used way of inserting single non-ASCII characters. See [`(info "(emacs) Inserting Text")`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Inserting-Text.html) and [`(info "(emacs) Special Isearch")`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Special-Isearch.html).

**Comment by hongyi-zhao** [comment]
Thank you for your explanation. I checked with your pattern, and the results are as follows: 

![image](https://user-images.githubusercontent.com/11155854/161977599-01da8f93-e827-4edf-88d2-f90cdd3818fc.png)
