### ISSUE TITLE
Dap mode do not recongnize test and cannot run dap-debug on java maven project main class

### ISSUE THREAD

**Issue by anquegi** [emacs-lsp/dap-mode#531]
I'm using emacs 29.0.50 with doom version "Doom core	v3.0.0-alpha     HEAD -> develop 0869d2848 2021-10-21 12:27:42 +0200" on OSX

I have the following project: 
[javawithmath.zip](https://github.com/emacs-lsp/dap-mode/files/7431333/javawithmath.zip)

The LSP works pretty well on java files buffers, but when I try to run dap-debug it doesn't work:

On test classes, after running dap-java-run-test-class, I get this: 
```
-*- mode: dap-server-log; default-directory: "~/learn/java/javawithmath/" -*-
Debug Adapter started at Thu Oct 28 07:44:43

java -jar /Users/toni/.doom-emacs.d/.local/etc/lsp/eclipse.jdt.ls/test-runner/junit-platform-console-standalone.jar -cp $JUNIT_CLASS_PATH -c toni.learn.javawithmath.AppShould -n ".*(Test|IT).*"

Thanks for using JUnit! Support its development at https://junit.org/sponsoring

╷
├─ JUnit Jupiter ✔
└─ JUnit Vintage ✔

Test run finished after 39 ms
[         2 containers found      ]
[         0 containers skipped    ]
[         2 containers started    ]
[         0 containers aborted    ]
[         2 containers successful ]
[         0 containers failed     ]
[         0 tests found           ]
[         0 tests skipped         ]
[         0 tests started         ]
[         0 tests aborted         ]
[         0 tests successful      ]
[         0 tests failed          ]

That seems not true since the class is:

```
public class AppShould {

  @Test
  void add_two_numbers() {
    assertThat(1 + 1, is(equalTo(2)));
    assertThat(1 + 1, is(equalTo(4)));
  }
}
```

Debug Adapter finished at Thu Oct 28 07:44:44, which is not true after that I read #17 and set this variables:

(setq dap-java-test-additional-args '("-n" "\".*(Test|IT).*\""))
(setq dap-print-io t)
(setq lsp-print-io t)

And also when thry to run dap-debug on main class I get this:

```
-*- mode: dap-server-log; default-directory: "~/learn/java/javawithmath/src/main/java/toni/learn/javawithmath/" -*-
Debug Adapter started at Thu Oct 28 07:52:43

java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=50199,quiet=y -cp $CLASSPATH_ARGS toni.learn.javawithmath.App
Debugger failed to attach: handshake failed - connection prematurally closed
Sintaxis: java [opciones] <clase principal> [argumentos...]
           (para ejecutar una clase)
   o  java [opciones] -jar <archivo jar> [argumentos...]
           (para ejecutar un archivo jar)
   o  java [opciones] -m <módulo>[/<clase principal>] [argumentos...]
       java [opciones] --module <módulo>[/<clase principal>] [argumentos...]
           (para ejecutar la clase principal en un módulo)

 Argumentos que siguen la clase principal, -jar <archivo jar>, -m o --module
 <módulo>/<clase principal> se transfieren como argumentos a una clase principal.

 donde las opciones incluyen:

    -cp <ruta de búsqueda de clase de directorios y archivos zip/jar>
    -classpath <ruta de búsqueda de clase de directorios y archivos zip/jar>
    --class-path <ruta de búsqueda de clase de directorios y archivos zip/jar>
                  Una lista separada por el carácter :, archivos JAR
                  y archivos ZIP para buscar archivos de clases.
    -p <ruta módulo>
    --module-path <ruta módulo>...
                  Una lista de directorios separada por el carácter :, cada directorio
                  es un directorio de módulos.
    --upgrade-module-path <ruta módulo>...
                  Una lista de directorios separada por el carácter :, cada directorio
                  es un directorio de módulos que sustituye a
                  los módulos actualizables en la imagen de tiempo de ejecución
    --add-modules <nombre módulo>[,<nombre módulo>...]
                  módulos de raíz que resolver, además del módulo inicial.
                  <nombre módulo> también puede ser ALL-DEFAULT, ALL-SYSTEM,
                  ALL-MODULE-PATH.
    --list-modules
                  mostrar módulos observables y salir
    -d <nombre de módulo>
    --describe-module <nombre módulo>
                  describir un módulo y salir
    --dry-run     crear VM y cargar la clase principal pero sin ejecutar el método principal.
                  La opción --dry-run puede ser útil para validar
                  las opciones de línea de comandos, como la configuración del sistema de módulos.
    --validate-modules
                  validar todos los módulos y salir
                  La opción --validate-modules puede ser útil para encontrar
                  conflictos y otros errores con módulos en la ruta de módulos.
    -D<nombre>=<valor>
                  definir una propiedad de sistema
    -verbose:[class|module|gc|jni]
                  activar la salida en modo verbose
    -version      imprimir versión de producto en el flujo de errores y salir
    --version     imprimir versión de producto en el flujo de salida y salir
    -showversion  imprimir versión de producto en el flujo de errores y continuar
    --show-version
                  -showversion  imprimir versión de producto en el flujo de salida y continuar
    --show-module-resolution
                  mostrar la salida de resolución de módulo durante el inicio
    -? -h -help
                  imprimir este mensaje de ayuda en el flujo de errores
    --help        imprimir este mensaje de ayuda en el flujo de salida
    -X            imprimir ayuda de opciones adicionales en el flujo de errores
    --help-extra  imprimir ayuda de opciones adicionales en el flujo de salida
    -ea[:<nombre paquete>...|:<nombre clase>]
    -enableassertions[:<nombre paquete>...|:<nombre clase>]
                  activar afirmaciones con una granularidad especificada
    -da[:<nombre paquete>...|:<nombre clase>]
    -disableassertions[:<nombre paquete>...|:<nombre clase>]
                  desactivar afirmaciones con una granularidad especificada
    -esa | -enablesystemassertions
                  activar afirmaciones del sistema
    -dsa | -disablesystemassertions
                  desactivar afirmaciones del sistema
    -agentlib:<nombre bib>[=<opciones>]
                  cargar biblioteca de agente nativo <nombre bib>, por ejemplo, -agentlib:jdwp
                  ver también -agentlib:jdwp=help
    -agentpath:<nombre ruta>[=<opciones>]
                  cargar biblioteca de agente nativo por nombre completo de ruta
    -javaagent:<ruta jar>[=<opciones>]
                  cargar agente de lenguaje de programación Java, ver java.lang.instrument
    -splash:<ruta imagen>
       mostrar pantalla de presentación con imagen especificada
                  Las imágenes a escala HiDPI están soportadas y se usan automáticamente
                  si están disponibles. El nombre de archivo de la imagen sin escala, por ejemplo, image.ext,
                  siempre debe transmitirse como el argumento para la opción -splash.
                  La imagen a escala más adecuada que se haya proporcionado se escogerá
                  automáticamente.
                  Consulte la documentación de la API de la pantalla de presentación para obtener más información.
    @argument files
                  uno o más archivos de argumentos que contienen opciones
    -disable-@files
                  evitar una mayor expansión del archivo de argumentos
Para especificar un argumento para una opción larga, puede usar --<nombre>=<valor> o
--<nombre> <valor>.

Debug Adapter exited abnormally with code 1 at Thu Oct 28 07:52:45

and whe I run dap-java-debug, it really hangs like this:

<img width="1680" alt="Captura de pantalla 2021-10-28 a las 7 54 54" src="https://user-images.githubusercontent.com/2518346/139195743-59280c18-f10c-4b4f-9236-66b9de09c8cc.png">

```
LSP :: Currently active thread is not stopped. Use `dap-switch-thread' or select stopped thread from sessions view. [3 times]
Quit [2 times]
```

getting this error on lsp-log buffer
```
28 oct. 2021 7:54:28 >> workspace/executeCommand vscode.java.resolveMainClass
28 oct. 2021 7:54:29 >> workspace/executeCommand vscode.java.resolveClasspath
28 oct. 2021 7:54:29 >> workspace/executeCommand vscode.java.startDebugSession
28 oct. 2021 7:54:29 Dispatch debug protocol error: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected STRING but was BEGIN_ARRAY at path $.args
java.lang.IllegalStateException: Expected STRING but was BEGIN_ARRAY at path $.args
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected STRING but was BEGIN_ARRAY at path $.args
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.Gson.fromJson(Gson.java:975)
	at com.microsoft.java.debug.core.protocol.JsonUtils.fromJson(JsonUtils.java:34)
	at com.microsoft.java.debug.core.adapter.DebugAdapter.dispatchRequest(DebugAdapter.java:78)
	at com.microsoft.java.debug.core.adapter.ProtocolServer.dispatchRequest(ProtocolServer.java:118)
	at com.microsoft.java.debug.core.protocol.AbstractProtocolServer.lambda$new$0(AbstractProtocolServer.java:78)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: Expected STRING but was BEGIN_ARRAY at path $.args
	at com.google.gson.internal.bind.JsonTreeReader.nextString(JsonTreeReader.java:181)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	... 17 more

28 oct. 2021 7:54:30 >> document/codeAction

```

[lsp-log.txt](https://github.com/emacs-lsp/dap-mode/files/7431517/lsp-log.txt)
[lsp-log-2.txt](https://github.com/emacs-lsp/dap-mode/files/7431536/lsp-log-2.txt)

**Comment by gagbo** [comment]
Is it this commit ? https://github.com/emacs-lsp/lsp-java/commit/2b789750b272c85e838b9fc4e3d4f1d2eff34b5b

**Comment by yyoncho** [comment]
This one - https://github.com/emacs-lsp/lsp-java/commit/b3f2081158284c77665a0dd5e9f815535ff080b3

**Comment by gagbo** [comment]
Or maybe this one ? https://github.com/emacs-lsp/lsp-java/commit/b3f2081158284c77665a0dd5e9f815535ff080b3

It's kind of annoying to have to find the exact commits each time, but as the maintenance load rises and the issues keep piling up, being able to have a somewhat conservative bump strategy for unmaintained modules helps avoiding bursts of issues.

Saw the new comment as I was typing, thanks

**Comment by anquegi** [comment]
Should I open another issue for the first error mentioned in my comment:

The LSP works pretty well on java files buffers, but when I try to run dap-debug it doesn't work:

On test classes, after running dap-java-run-test-class, I get this:

-*- mode: dap-server-log; default-directory: "~/learn/java/javawithmath/" -*-
Debug Adapter started at Thu Oct 28 07:44:43

java -jar /Users/toni/.doom-emacs.d/.local/etc/lsp/eclipse.jdt.ls/test-runner/junit-platform-console-standalone.jar -cp $JUNIT_CLASS_PATH -c toni.learn.javawithmath.AppShould -n ".*(Test|IT).*"

```
Thanks for using JUnit! Support its development at https://junit.org/sponsoring

╷
├─ JUnit Jupiter ✔
└─ JUnit Vintage ✔
```

**Comment by yyoncho** [comment]
@anquegi I forgot about that - can you open another one in lsp-java? Also, can you test with hello world app like this: https://github.com/emacs-lsp/lsp-mode/tree/master/test/fixtures/org-mode/java-project

**Comment by gagbo** [comment]
Also @anquegi, before testing can you :

- add this to your packages.el :
```lisp
;; Create ~/.config/doom/packages.el if it doesn't exist
(unpin! lsp-java)
```
- Run `doom sync`
- Try to reproduce the bug. At that point there are 2 outcomes 
  + Bug still happens : open an issue to `lsp-java`
  + Bug doesn't happen : open an issue to `doom-emacs`
  
In both cases you should describe the bug, and for `doom-emacs` case, the `doom/info` and the fact that unpinning the package solved the bug

**Comment by anquegi** [comment]
Hello @gagbo , I already tested with this unpin: 

(unpin! lsp-mode lsp-java dap-mode)

It worked well
