### ISSUE TITLE
dap-go-setup fails silently on rate limit

### ISSUE THREAD

**Issue by RoryCrispin** [emacs-lsp/dap-mode#537]
When being rate-limited by Microsoft the function 'dap-go-setup' fails silently, actually reporting success.

I believe it fails to unzip the archive as the web request is returned with:
Steps to reproduce:
either connect from a location where you are rete-limited, or setup a web server which delivers this response:
` < HTTP 200`
`{"$id":"1","innerException":null,"message":"Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on why your request was blocked, see the topic \"Rate limits\" on the Microsoft Web site (https://go.microsoft.com/fwlink/?LinkId=823950).","typeName":"Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, Microsoft.TeamFoundation.Framework.Server","typeKey":"RequestBlockedException","errorCode":0,"eventId":3000}`
and point the download url at said server. 
Run `dap-go-setup` 
observe that it reports success, despite setup having failed

**Comment by yyoncho** [comment]
This is a well-known issue - the workaround that we are implementing is to download the vsix file and commit it in https://github.com/emacs-lsp/lsp-server-binaries

**Comment by RoryCrispin** [comment]
Sure,
Happy for the ticket to be closed if it's of no use to you
