### ISSUE TITLE
add functions for going up/down the stack

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/dap-mode#54]

**Comment by prittjam** [comment]
has anyone addressed this, I was just about to suggest the same.

**Comment by yyoncho** [comment]
No, not it is still open. If you want to give it a try you may take a look at `dap-switch-stack-frame` and/or ping me here or in gitter.

**Comment by prittjam** [comment]
Unfortunately, me elisp is barely existent; otherwise I would give it a go.
