### ISSUE TITLE
[c#] debugging NUnit test

### ISSUE THREAD

**Issue by serezlan** [emacs-lsp/dap-mode#542]
Hi,

I need to debug my unit test. So far I can debug console with netcoredbg but still no luck with my test unit.

Steps to reproduce:

- Create new nunit project 
- Run "dap-debug" and select "dotnet core (launch)"
- Select bin/Debug/netcorexx/MyClass.Test.dll

Expected behavior:

- several buffer appear with information about local var, etc

Actual Behavior:

- Nothing. 

System:

- emacs 27.2
- Debian 10

[dap.log](https://github.com/emacs-lsp/dap-mode/files/7639558/dap.log)

**Comment by yyoncho** [comment]
fixed in https://github.com/emacs-lsp/dap-mode/pull/564
