### ISSUE TITLE
cpptools debugger not stopping at breakpoints

### ISSUE THREAD

**Issue by lucasmyers97** [emacs-lsp/dap-mode#546]
When I run `dap-debug` with `cpptools::Run Configuration` the debugger just runs through the program.
The small, clickable menu at the top has all of the arrows whited out and then disappears after the program is finished running.
For context, a piece of example code is:
``` cpp
// debug_test.cpp

#include <iostream>

int main()
{
    std::cout << "Before breakpoint\n";
    std::cout << "At breakpoint\n";
    std::cout <<"After breakpoint\n";

    return 0;
}
```
with the debug configuration file looking like
``` lisp
(dap-register-debug-template
  "cpptools::Run Configuration"
  (list :type "cppdbg"
        :request "launch"
        :name "cpptools::Run Configuration"
        :MIMode "gdb"
        :program "/home/lucas/debug_test"
        :cwd "/home/lucas/"))
```
I add breakpoints in the usual way with `SPC d b a` at a particular point.
Any tips on how to fix this?

**Comment by yyoncho** [comment]
Set dap-print-io to t and then upload the content of messages buffer

**Comment by lucasmyers97** [comment]
Here I went to the source file, updated the debug template to point to the binary, added a breakpoint on the "At breakpoint" line, and then tried to run the debugger.
I've attached the messages file:

[debug_messages.txt](https://github.com/emacs-lsp/dap-mode/files/7803780/debug_messages.txt)
.

**Comment by yyoncho** [comment]
How do you build the binary?

**Comment by lucasmyers97** [comment]
For this one I just did `g++ debug_text.cpp -o debug_test`, but I have an actual project (whose files have somehow gotten mixed up in the debugger call, and which can be seen in the messages buffer) which I build with cmake.

**Comment by yyoncho** [comment]
@lucasmyers97 you have to compile with `-g` flag to generate debug symbols.

**Comment by lucasmyers97** [comment]
Whoops, that's my bad! Everything works fine when I set the project to debug mode. Thanks for the help!
