### ISSUE TITLE
dap-python configured args are not passed to the target program

### ISSUE THREAD

**Issue by f279801** [emacs-lsp/dap-mode#55]
(compile (format "%s -m ptvsd --wait --host %s --port %s %s" python-executable host debug-port buffer-file-name))

Maybe we can add another argument to the python command and passing the fetched args from the configuration.

    (compile (format "%s -m ptvsd --wait --host %s --port %s %s %s" python-executable host debug-port buffer-file-name (plist-get conf :args))

/Tai

**Comment by yyoncho** [comment]
Make sense, willing to provide a PR?

**Comment by f279801** [comment]
Sure, I'll.

/Tai

**Comment by yyoncho** [comment]
Fixed with https://github.com/emacs-lsp/dap-mode/pull/56
