### ISSUE TITLE
emacs can not input anything when debug flutter app

### ISSUE THREAD

**Issue by xhcoding** [emacs-lsp/dap-mode#551]
When I debug flutter app on Windows, emacs can not input anything and dap always pending

<img width="960" alt="企业微信截图_16430122926197" src="https://user-images.githubusercontent.com/30917129/150746198-372c0094-bb79-4acd-b554-9b9daac5fde2.png">

dap io:
[dap-print-io.txt](https://github.com/emacs-lsp/dap-mode/files/7923807/dap-print-io.txt)

**Comment by yyoncho** [comment]
cc @ericdallo

**Comment by xhcoding** [comment]
I found `exposeUrlResponse` request no response
```
Sending:
{
  "command": "exposeUrlResponse",
  "arguments": {
    "originalUrl": "ws://127.0.0.1:60872/$debug",
    "exposedUrl": "ws://127.0.0.1:60872/$debug"
  },
  "type": "request",
  "seq": 3
}
```
lsp-dart-dart send `exposeUrlResponse` request with `dap-request` :  https://github.com/emacs-lsp/lsp-dart/blob/d20fda0477da5740c916614dc6e07deefc8b5835/lsp-dart-dap.el#L332

but  debug server don't send response: https://github.com/Dart-Code/Dart-Code/blob/b0dab817e6cbe7915354c14fb759d8143fef07c7/src/debug/dart_debug_impl.ts#L1710

I don't know which project should fix it
 
 cc @ericdallo

**Comment by xhcoding** [comment]
I used a workaround to solve the problem

**Comment by ericdallo** [comment]
Maybe debugger server didn't manage to expose the URL and just didn't respond?
