### ISSUE TITLE
[Question] What are the configurations for C#?

### ISSUE THREAD

**Issue by NovaViper** [emacs-lsp/dap-mode#555]
Hey guys, I have LSP and Omnisharp setup on my computer but im having the hardest time trying to setup the debugger, and I heard there's a mode for netcoredbg but there aren't any guides anywhere.. does anyone have a working configuration for C# in dap-mode? I'm using Doom Emacs

**Comment by yyoncho** [comment]
Maybe @s-kostyaev / @sebasmonia can help here?

**Comment by sebasmonia** [comment]
Hi @NovaViper!

The short way to try to get you up and running:
1. In your config, `(require 'dap-netcore)`.
2. You can then M-x `dap-debug` and then either launch an application, or attach to an already running process
    - If you chose to attach, you can find the process id using `proced` :)
    - Also, you can use `System.Diagnostics.Debugger.Launch()` or `System.Diagnostics.Debugger.Break()` in your code, to break at that point after attaching.  

There are several things that can go wrong with this, some pointers
* If auto-installing the debugger fails, head to https://github.com/Samsung/netcoredbg/releases/ and download it yourself. Customize `dap-netcore-install-dir` with the directory were you dropped the executable. Try to run it once from your console to make sure it runs...
* Web applications are _very hard_ to launch with debugger, so try attaching and then adding the aforementioned `Break()` as an alternative.
* If dap-mode kicks off but you see no variables, locals, etc. try M-x `dap-switch-thread`. Maybe more than once, just in case :)

:crossed_fingers: this gets you up and running, please report back!
There are a few issues in this repo if you search by "netcoredbg". I used them to refresh my memory, in case you still have trouble and I take too long to reply, take a peek in those.

**Comment by NovaViper** [comment]
Hey @sebasmonia! I have dap-mode and dap-netcore already enabled in my config, but the main issue is actually trying to get it to debug. Whenever I debug, I get this error
```
Debug session process exited with status: exited abnormally with code 127
```

I have my example cs file in the project and I just have that file along with the .project file and made the directory a git repo. Is there something else I'm missing?
[example.txt](https://github.com/emacs-lsp/dap-mode/files/7965452/example.txt)

**Comment by s-kostyaev** [comment]
@NovaViper are there any logs in dap buffers in this case?

**Comment by yyoncho** [comment]
@NovaViper check stderr buffer in particular

**Comment by NovaViper** [comment]
AH I found it

```
/usr/bin/emacs: /usr/bin/netcoredbg/netcoredbg/netcoredbg: Not a directory

Process NetCoreDbg::Launch stderr finished
```

**Comment by NovaViper** [comment]
Ah.. so I downloaded netcoredbg from the [AUR repo](https://aur.archlinux.org/packages/netcoredbg) but I can't figure where the install is... other than the one it creates as it downloads and builds the package

**Comment by sebasmonia** [comment]
It might be worth considering manually downloading the release from their page. The AUR page mentions the same challenges we had with the release URL changing.

**Comment by NovaViper** [comment]
The issue isn't the package not install, it installs perfectly fine and I can even run it; the issue is tellling dap-debugger where it is (and not preappend a directory to it). I found that the AUR installs the package and places the executable in `/usr/bin` but the trouble now is telling dap-mode to select the directory. I tell it to look for it in `/usr/bin` but it then goes and adds `/netcoredbg/netcoredbg`, which will of course cause it to error out.

```
❯ yay -Ql netcoredbg
netcoredbg /usr/
netcoredbg /usr/bin/
netcoredbg /usr/bin/ManagedPart.dll
netcoredbg /usr/bin/Microsoft.CodeAnalysis.CSharp.Scripting.dll
netcoredbg /usr/bin/Microsoft.CodeAnalysis.CSharp.dll
netcoredbg /usr/bin/Microsoft.CodeAnalysis.Scripting.dll
netcoredbg /usr/bin/Microsoft.CodeAnalysis.dll
netcoredbg /usr/bin/libdbgshim.so
netcoredbg /usr/bin/netcoredbg
netcoredbg /usr/share/
netcoredbg /usr/share/licenses/
netcoredbg /usr/share/licenses/netcoredbg/
netcoredbg /usr/share/licenses/netcoredbg/LICENSE
```

**Comment by NovaViper** [comment]
I finally managed to figure out how to install the package into the preappended path but now I get this this when I try to run my cs file

```
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-/home/novaviper/Documents/Projects/C# test/example.cs does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

**Comment by sebasmonia** [comment]
I just looked at the code for dap-netcore.

Try redefining [dap-netcore--debugger-cmd](https://github.com/emacs-lsp/dap-mode/blob/76cad34de8984f57c2b1e374e9c985cc7ec8dad0/dap-netcore.el#L94):
```
(defun dap-netcore--debugger-cmd ()
  "The location of the netcoredbg executable."
  (let ((file-ext (pcase system-type
                    (`windows-nt ".exe")
                    (_ ""))))
    (expand-file-name (concat "netcoredbg" file-ext) dap-netcore-install-dir "netcoredbg")))
```
Not a definitive solution, but something to test and see if it gets things working.

**Comment by NovaViper** [comment]
> 

Uh.. how do I specify the executable for Linux, and how do I make an advice to override the function?

**Comment by sebasmonia** [comment]
If you put that function I shared above in your init file _after_ loading dap-netcore, it will replace the definition currently in the package.

One more way to do it, why not symlink your netcoredbg binary to /netcoredbg/netcoredbg?

**Comment by NovaViper** [comment]
symlinking is almost impossible since the AUR installs everything directly into /usr/bin, which makes trying to find all of the files near impossible <_>

Installing it into /usr/bin/netcoredbg seemed to have at least let me run it but then I run into this error
```
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-/home/novaviper/Documents/Projects/C# test/example.cs does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

**Comment by NovaViper** [comment]
@sebasmonia Sadly, it still didn't work, kept getting that error I posted earlier D:

BUT I do have another idea.. heard about a program called Mono, maybe I can use that? Im not real sure how to integrate it into dap-mode however

**Comment by sebasmonia** [comment]
You probably already have Mono installed :)
Mono has no a debugger AFAIK, just runtime and a few other tools. If it does have a debugger, I have no idea if it works with .NET Core.

I am a bit lost on what problem you are having now, but I you suggest to just download the compiled release from their page and drop it in a location that works, it would be a good test that everything else is in place.

**Comment by NovaViper** [comment]
Welp, I just tried compiling it manually and I get this error
```
❯ make
Consolidate compiler generated dependencies of target linenoise
[  5%] Built target linenoise
Consolidate compiler generated dependencies of target example
[  7%] Built target example
Consolidate compiler generated dependencies of target corguids
[ 26%] Built target corguids
[ 26%] Built target buildinfo
Consolidate compiler generated dependencies of target netcoredbg
[ 28%] Building CXX object src/CMakeFiles/netcoredbg.dir/debugger/frames.cpp.o
/home/novaviper/.local/share/netcoredbg/src/debugger/frames.cpp:169:33: error: no member named 'numeric_limits' in namespace 'std'
        uint64_t pEndVal = std::numeric_limits<uint64_t>::max();
                           ~~~~~^
/home/novaviper/.local/share/netcoredbg/src/debugger/frames.cpp:169:48: error: unexpected type name 'uint64_t': expected expression
        uint64_t pEndVal = std::numeric_limits<uint64_t>::max();
                                               ^
/home/novaviper/.local/share/netcoredbg/src/debugger/frames.cpp:169:59: error: no member named 'max' in the global namespace
        uint64_t pEndVal = std::numeric_limits<uint64_t>::max();
                                                        ~~^
/home/novaviper/.local/share/netcoredbg/src/debugger/frames.cpp:215:29: error: no member named 'numeric_limits' in namespace 'std'
    uint64_t pEndVal = std::numeric_limits<uint64_t>::max();
                       ~~~~~^
/home/novaviper/.local/share/netcoredbg/src/debugger/frames.cpp:215:44: error: unexpected type name 'uint64_t': expected expression
    uint64_t pEndVal = std::numeric_limits<uint64_t>::max();
                                           ^
/home/novaviper/.local/share/netcoredbg/src/debugger/frames.cpp:215:55: error: no member named 'max' in the global namespace
    uint64_t pEndVal = std::numeric_limits<uint64_t>::max();
                                                    ~~^
6 errors generated.
make[2]: *** [src/CMakeFiles/netcoredbg.dir/build.make:260: src/CMakeFiles/netcoredbg.dir/debugger/frames.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:229: src/CMakeFiles/netcoredbg.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

```

**Comment by NovaViper** [comment]
Annnnnnd the precompiled versions from the github throws that same mysterious executable error
```
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-/home/novaviper/Documents/Projects/C#/Lab2/ileary1Lab02Q1 does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

**Comment by NovaViper** [comment]
OH wait.. I think I found something, so apparently the global net tools need to be installed... but which ones do I need to install for C#?

https://docs.microsoft.com/en-us/dotnet/core/tools/troubleshoot-usage-issues#net-tool-installation-fails

**Comment by sebasmonia** [comment]
This path with the - looks suspicious: `dotnet-/home/novaviper/Documents/Projects/C#/Lab2/ileary1Lab02Q1`
I think your dotnet installation has some sort of problem?

**Comment by NovaViper** [comment]
> This path with the - looks suspicious: `dotnet-/home/novaviper/Documents/Projects/C#/Lab2/ileary1Lab02Q1` I think your dotnet installation has some sort of problem?

I have no idea... This is the first time I've ever had to use dotnet for something so I honestly have no idea what to even look for in terms of troubleshooting <_>

I do get this error too
```
user-error: Cannot complete at point
Quit [2 times]
No message handler for process
No message handler for module [40 times]
Debug session process exited with status: killed
```

And when I run `dotnet run --project ~/Documents/Projects/C\#/Lab2/` I get this error: `Couldn't find a project to run. Ensure a project exists in /home/novaviper/Documents/Projects/C#/Lab2/, or pass the path to the project using --project.
`

**Comment by sebasmonia** [comment]
Everything in the System.* namespace, most of the times comes bundled.
I think you need to make sure you can `dotnet build` & `dotnet run` something before trying to debugger again!

Try removing what you have now and install according to https://dotnet.microsoft.com/en-us/download.
You mentioned the AUR before, there's some tips at https://wiki.archlinux.org/title/.NET that might be useful.

**Comment by NovaViper** [comment]
OH! I managed to get `dotnet run` and `dotnet build` to build my example lab assignment project (the file I was using originally didn't have neither a solution file or a project file, the example project does however have both because I originally made it inside of Visual Studio 😓 ).. But I still can't get Emacs to run it, same errors <_>

Even using the `dotnet-runtime` and `dotnet-sdk` packages from ArchLinux. I followed the tips that's on the wiki too to get the global tools path declared and all aswell.

**Comment by sebasmonia** [comment]
Did you manage to get this working?

If `dotnet run` and `build` work in the terminal, but not in Emacs, maybe there's some configuration issue? You can share your current config just in case.

**Comment by NovaViper** [comment]
I haven't unfortunately :(

Here's my org config for emacs:
[config.txt](https://github.com/emacs-lsp/dap-mode/files/8018114/config.txt)

**Comment by sebasmonia** [comment]
I'm sorry, not familiar with Doom Emacs. The dap-mode config seems OK.
I still find it odd how the path is reported in those errors above, but that might be just the way the message is displayed.
Completely lost on where to go from here.

**Comment by NovaViper** [comment]
> I'm sorry, not familiar with Doom Emacs. The dap-mode config seems OK. I still find it odd how the path is reported in those errors above, but that might be just the way the message is displayed. Completely lost on where to go from here.

Im going to try and see if maybe I can load it from a stock Emacs config.. do you happen to have a config that you for dap mode on hand?

**Comment by sebasmonia** [comment]
My setup uses [use-package](https://github.com/jwiegley/use-package#use-package), here is the dap config:

```

(use-package dap-mode
  :commands (dap-debug dap-breakpoints-add)
  :init
  (dap-mode 1)
  (dap-ui-mode 1)
  (dap-auto-configure-mode)
  (require 'dap-python)
  (require 'dap-pwsh)
  (require 'dap-netcore)
  (defvar hoagie-dap-run-keymap (define-prefix-command 'hoagie-dap-run-keymap))
  (defvar hoagie-dap-bpoints-keymap (define-prefix-command 'hoagie-dap-bpoints-keymap))
  (global-set-key (kbd "<f5>") hoagie-dap-run-keymap)
  (global-set-key (kbd "<f9>") hoagie-dap-bpoints-keymap)
  :bind
  (:map hoagie-dap-run-keymap
        ("<f5>" . dap-debug)
        ("<f6>" . dap-next)
        ("<f7>" . dap-step-in)
        ("<f8>" . dap-step-out)
        ("<f9>" . dap-continue)
        ("<f1>" . dap-eval-thing-at-point)
        ("C-<f1>" . dap-eval)
        ("<f2>" . dap-ui-expressions)
        ("C-<f2>" . dap-ui-expressions-add)
        ("M-<f2>" . dap-ui-expressions-remove)
        ("<f3>" . dap-ui-repl)
        ("C-c" . dap-disconnect)) ;; "Stop"
  (:map hoagie-dap-bpoints-keymap
        ("<f10>" . dap-ui-breakpoints-list)
        ("<f9>" . dap-breakpoint-toggle) ;; f9 twice -> toggle
        ("<f11>" . dap-breakpoint-log-message)
        ("<f12>" . dap-breakpoint-condition))
  :custom
  (dap-netcore-install-dir "/home/hoagie/.omnisharp/netcoredbg/1.2.0-825/"))
```

I haven't used dap in a long time but I remember I hated the bindings and was planning to revamp them :)

**Comment by NovaViper** [comment]
@sebasmonia Hey! I just ran it with your configurations and sadly I'm still getting that same error (even tried on a clean Emacs install) 😭

**Comment by sebasmonia** [comment]
You can try using the `csproj` file to launch the debugger.
Another thing you can do is add a call to `System.Diagnostics.Debugger.Break()`, run the program, and then use the Attach option for the program's process id.

**Comment by NovaViper** [comment]
Uh.. how do I add a call to the function?

**Comment by sebasmonia** [comment]
Take a look at https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.debugger.break?view=net-5.0#system-diagnostics-debugger-break

For console programs, just asking for some user input is another good way to stop the process to attach the debugger.

**Comment by NovaViper** [comment]
> Take a look at https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.debugger.break?view=net-5.0#system-diagnostics-debugger-break
> 
> For console programs, just asking for some user input is another good way to stop the process to attach the debugger.

Uh... I put it in but I don't see anything happening
```
using System;

namespace Lab1
{
    internal class Program
    {
        static void Main(string[] args)
        {
            System.Diagnostics.Debugger.Break();
            Console.ReadLine();
            double Y = 12.3;
            double Z = 4.0;
            int A = 13;
            double X = Y / 4 + Z * 7 % A / 4;


            Console.WriteLine(Convert.ToString(X));
            Console.WriteLine("Press enter to exit...");
        }
    }
}
```

**Comment by sebasmonia** [comment]
while it is waiting for input in the first ReadLine() try to attach the debugger to the process id (find it via M-x proced, or your tool of choice)

**Comment by NovaViper** [comment]
Oki, it lets me attach it but I can't like do anything like step back and break. Basically it doesn't allow me to interact with it at all (other than show that when the process end), I still have to d anything within the terminal shell :(

**Comment by s-kostyaev** [comment]
@NovaViper personally I don't use csharp, but I so some test to help you. Steps to debug your code:

1. Create new project with `dotnet new console`
2. Insert your code into `Program.cs`
3. Build project with `dotnet build`
4. Add breakpoint with `M-x` `dap-breakpoint-add`
5. Start debugging with `M-x` `dap-debug`
6. Select `.Net Core Launch (Console)`
7. Select builded dll, *not an executable binary!!*
8. Play around with debugger
9. Profit
![output-2022-02-16-02:30:56](https://user-images.githubusercontent.com/8576745/154137152-ad1fd52c-30ef-4cae-bd95-069b68c0128e.gif)

**Comment by s-kostyaev** [comment]
Not sure how to work with attach. If I remember correctly, it works only runned with `dotnet run`. Correct me if I'm wrong.

P.S. I use linux as my environment.

**Comment by NovaViper** [comment]
@s-kostyaev Omg that's it! Now it runs inside Emacs!! 😄

**Comment by s-kostyaev** [comment]
Cool! I had the same problems with fsharp debugging. And some others that I have fixed with PR :smiley:

**Comment by NovaViper** [comment]
@s-kostyaev Hey, is there a way to run the dotnet commands inside Emacs? Would be cool if there's a way to run them in a little command

**Comment by NovaViper** [comment]
Oo, is there also way to have the 

> @NovaViper Something like this - https://github.com/julienXX/dotnet.el ?

Perfect! 😄 

Oo, also I noticed that I can't type in the terminal that Emacs/Doom Emacs makes when I enter debug mode, how do I make that interactive?

**Comment by s-kostyaev** [comment]
> Oo, also I noticed that I can't type in the terminal that Emacs/Doom Emacs makes when I enter debug mode, how do I make that interactive?

For me `M-x` `dap-ui-repl` already interactive. Not sure what's wrong with yours.

**Comment by s-kostyaev** [comment]
According to [documentation](https://emacs-lsp.github.io/dap-mode/page/features/#compiling-the-project-before-debugging) you can also configure your project to auto-build before debugging.

**Comment by NovaViper** [comment]
> > Oo, also I noticed that I can't type in the terminal that Emacs/Doom Emacs makes when I enter debug mode, how do I make that interactive?
> 
> For me `M-x` `dap-ui-repl` already interactive. Not sure what's wrong with yours.

Ah yeah, the `dap-ui-repl` is interactive, but oddly when I run the debugger I can't type anything in it, stays in vim mode. Which makes me wonder if it's something Doom Emacs.. since I have evil-mode enabled for that. How would I go about making dap-mode use that repl ui?

**Comment by sebasmonia** [comment]
Thank you so much @s-kostyaev , since I always attach to WebAPI projects, I didn't know that you had to point to the DLL for `Launch`.

**Comment by NovaViper** [comment]
Ah, so I found #169 for the CLI debug issue. Sadly it looks like REPL only works with breakpoints and not the standard terminal interaction (for whenever I need to type input for the program). 🤔  Now I just need to figure out how to do that; but definitely thanks for helping with getting C# working in Emacs! @s-kostyaev

**Comment by NovaViper** [comment]
Oo so quick update, I did figure out how to make dap-mode automatically compile the program and select the .dll file for it! Sharing for reference if anyone else also wants to do this
```
(dap-register-debug-template "NetCoreDdg Launch"
  (list :type "coreclr"
        :request "launch"
        :mode "launch"
        :name "NetCoreDbg Launch"
  	:dap-compilation "dotnet build"
	:program "${workspaceFolder}/bin/Debug/net6.0/${workspaceFolderBasename}.dll"))
```

**Comment by s-kostyaev** [comment]
> Oo so quick update, I did figure out how to make dap-mode automatically compile the program and select the .dll file for it! Sharing for reference if anyone else also wants to do this
> 
> ```
> (dap-register-debug-template "NetCoreDdg Launch"
>   (list :type "coreclr"
>         :request "launch"
>         :mode "launch"
>         :name "NetCoreDbg Launch"
>   	:dap-compilation "dotnet build"
> 	:program "${workspaceFolder}/bin/Debug/net6.0/${workspaceFolderBasename}.dll"))
> ```

 @NovaViper Looks like you can improve dap-mode by PR :smiley:

**Comment by s-kostyaev** [comment]
@yyoncho can `:program` inside `dap-register-debug-template` be dynamic and project specific? Looks like "net6.0" shouldn't be hardcoded but should be calculated like:
```elisp
(save-mark-and-excursion
  (find-file (concat
	      (if (project-current)
		  (project-root (project-current))
		default-directory)
	      "*.*proj")
	     t)
  (let ((res (if (libxml-available-p)
		 (libxml-parse-xml-region (point-min) (point-max))
	       (xml-parse-region (point-min) (point-max)))))
    (kill-buffer)
    (dom-text (dom-by-tag res 'TargetFramework))))
    ```

**Comment by yyoncho** [comment]
Yes, check how adapters are using dap--put-if-absent

**Comment by yyoncho** [comment]
@s-kostyaev FWIW it is good practice to check what the corresponding vscode adapter is doing.
