### ISSUE TITLE
dap-debug-edit-template seems broken with python

### ISSUE THREAD

**Issue by f279801** [emacs-lsp/dap-mode#57]
With dap-debug-edit-template, my understanding is that we adapt the configuration, evaluate the new value then the debug session will be started.
But since all the new value is modified in a new opened buffer, buffer-file-name seems no longer valid?

Or we have another proper WoW for dap-debug-edit-template?
/Tai

**Comment by yyoncho** [comment]
Can you help with testing the following configuration for python:


```
(defun dap-python--populate-start-file-args (conf)
  "Populate CONF with the required arguments."
  (let* ((host "localhost")
         (debug-port (dap--find-available-port host dap-python-default-debug-port))
         (python-executable dap-python-executable)
         (python-args (or (plist-get conf :args) "")))

    (dap--put-if-absent conf :program-to-start
                        (format "%s -m ptvsd --wait --host %s --port %s %s %s"
                                python-executable host debug-port buffer-file-name python-args))
    (plist-put conf :debugServer debug-port)
    (plist-put conf :port debug-port)
    (plist-put conf :wait-for-port t)
    (plist-put conf :hostName host)
    (plist-put conf :host host)
    conf))
```

**Comment by f279801** [comment]
Hi @yyoncho ,
It works but I have another idea as below, It'll refactor the way how edit-template works currently but to me it helps to provide a clearer wow for this stuff:
- Add one more parameter to python configuration, i.e: `:target nill`
- dap-python--populate-start-file-args will do similar stuff as your current fix. But before that it will also try to figure out the real target by checking for nil or empty :target and set it to buffer-file-name if it is the case. Otherwise, real target will be the configured one. After this it will build and append program-to-start into the configuration and return this back to the caller. By this we will not compile the command but signal the caller to do it for us by setting up the program-to-start.
- dap-debug-edit-template its turn will export the configuration to DAP Templates buffer. But instead of providing the dap-debug command, we just provide the dap-register-debug-template command. This ties what the function really does and its name. Also it provides the abilities for user to both overwritting the current configuration (by keeping the same name) and creating a new one (by change the name and/or other paramter) before evaluating. It is also really nice if dap-debug-edit-template would filter out the program-to-start from what it prints to DAP Template (it will be rebuilt later on when dap-debug is executed).
- After finishing edit the debug template, the normal dap-debug can be ran again with the same procedure (of course with new configuration/or more template).

How do you think about that proposal? If you are OK with that, I can also help to provide a PR in case you want.

/Tai

**Comment by yyoncho** [comment]
So, this is one of the things that I am thinking about recently. The problem is that in some of the cases you want the template to be prepopulated by the populate function(in dap java there is just too much stuff to populate it manually). I am thinking about having a prefix arg which switches the behaviour (e. g. with C-u M-x dap-debug-edit-template to return the template after it has been populated, without C-u return the template itself).

**Comment by f279801** [comment]
Yes, it makes sense that we should have two behaviours.
Are you also OK if the dap-debug-edit-template just work with template definition/overwritting and not prepare the run command? I'm more preferred this behavior but it then will make some non backward compatible changes unfortunately. Other solution is to have a new command, e.g: dap-debug-edit-<run/debug>-configuration...

**Comment by yyoncho** [comment]
> Are you also OK if the dap-debug-edit-template just work with template definition/overwritting and not prepare the run command? I'm more preferred this behavior but it then will make some non backward compatible changes unfortunately.

This makes more sense since the prepare behaviour is less common. I doubt that anyone will be affected by the new behaviours since dap-java teplates even now does not work without doing something like `(with-current-buffer "App.java" (dap-debug (...)))` since the template could be started only from file with started language server.

**Comment by f279801** [comment]
Yeah, maybe it's safer to create a new command for that purpose.

**Comment by yyoncho** [comment]
Just to clarify - I prefer to make it work as you have suggested. I do not like the idea of having more commands since it is getting more complicated.

> Are you also OK if the dap-debug-edit-template just work with template definition/overwritting and not prepare the run command?
