### ISSUE TITLE
dap-php-setup does nothing

### ISSUE THREAD

**Issue by programmador** [emacs-lsp/dap-mode#570]
The commands tells "dap-php: Downloading done!" but the folder `.emacs.d/.extension/vscode/felixfbecker.php-debug/` is being created empty. Manually downloading vsix, renaming it to zip and unpacking to the abovementioned folder helps.

**Comment by yyoncho** [comment]
We already have this reported. If you run the command multiple times it will trigger DDOS protection of market place. We are still working on a solution.
