### ISSUE TITLE
Displaying Breakpoints in Terminal Mode (-nw)

### ISSUE THREAD

**Issue by Xaldew** [emacs-lsp/dap-mode#579]
Hello,

I just started using `dap-mode` and am generally finding it very useful, however I can't seem to be able to get Breakpoints to be displayed when running Emacs inside a terminal (as in, running without an X environment).

If I understand things correctly, the breakpoints are displayed in the window fringe or margin and thus will not show up in a terminal environment, but maybe there is already some other way to display them?

Alternatively, maybe it would be a good idea to create another minor-mode that can display the breakpoints using an overlay for the first couple of characters on every line as a workaround?

**Comment by yyoncho** [comment]
use dap-ui-verified-breakpoint-face and related.
