### ISSUE TITLE
question: how can I debug go code in GOMOD/src Directory

### ISSUE THREAD

**Issue by aggronmagi** [emacs-lsp/dap-mode#588]
I came across a project code directory that contained "src". like "xxx.com/src/x1".

now I got error: $GOPATH/go.mod exists but should not

How do I debug code without modifying the "src" directory?

**Comment by s-kostyaev** [comment]
I think the problem isn't about src directory. Do you have file `$GOPATH/go.mod`? Or if `$GOPATH` not set `$HOME/go/go.mod`

**Comment by s-kostyaev** [comment]
You can try replace directive and use code outside GOMOD/src

**Comment by aggronmagi** [comment]
$GOPATH and $HOME/go do not have go.mod.

Now I don't have permission to modify GOMOD/src.

After I try to modify the local src directory and replace the package name, dap debug can be debugged normally. 

```
➜  tx git:(master) ✗ tree . 
.
├── go.mod
├── src
│   └── main.go
└── xx
    └── main.go
```
main.go 
``` go
package main

import "fmt"

func main(){
  fmt.Println("hello world")
}
```

I can debug xx/main.go, but debugging src/main.go prompts 
`$GOPATH/go.mod exists but should not`

**Comment by aggronmagi** [comment]
I modify .extension/vscode/golang.go/extension/dist/debugAdapter.js and then I can debug src/main.go.

``` js
function getInferredGopath(folderPath) {
    return; // fix this bug.
    if (!folderPath) {
        return;
    }
    const dirs = folderPath.toLowerCase().split(path.sep);
    // find src directory closest to given folder path
    const srcIdx = dirs.lastIndexOf('src');
    if (srcIdx > 0) {
        return folderPath.substr(0, dirs.slice(0, srcIdx).join(path.sep).length);
    }
}
```
