### ISSUE TITLE
Support lldb debugger

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/dap-mode#6]
Via https://github.com/vadimcn/vscode-lldb

**Comment by danielmartin** [comment]
I've added initial support in https://github.com/yyoncho/dap-mode/pull/25

Tested some C, C++ and Swift code and it works well.

**Comment by yyoncho** [comment]
Thanks for the contribution! I will list you in the credit section. Do you think that 
we should support this as as well : https.com/vadimcn/vscode-lldb? Also, will this support Rust as well(I am not very familiar with how lldb works)?

**Comment by danielmartin** [comment]
We can support that as well. Is there any noticeable difference between the two? I chose `lldb-vscode` mostly because it's part of the official LLDB repository, so I assume it'll be better supported in the long term.

About Rust, I don't use it either, but I think that the basic features should work. From what I see, right now they only have a wrapper with some Python formatters (https://github.com/rust-lang/rust/blob/master/src/etc/rust-lldb), so if LLDB is using those formatters before communicating with the adapter, everything should work more or less out of the box, or with minor changes.

But needs someone to test it.

**Comment by SuperPrower** [comment]
Just curious, is there are real need for vscode extension? Can't it be done directly with LLDB?

**Comment by danielmartin** [comment]
> Just curious, is there are real need for vscode extension? Can't it be done directly with LLDB?

You need a debug adapter so that Emacs and LLDB can communicate. Despite the name, `lldb-vscode` is not tied to VS Code and can be used from any text editor that implements the protocol.

**Comment by yyoncho** [comment]
https://github.com/WebFreak001/code-debug supports both gdb and lldb in case someone is interested.

**Comment by SuperPrower** [comment]
> You need a debug adapter so that Emacs and LLDB can communicate.

Theoretically, can't you write one in elisp? There are implementations in JS family of languages, so I guess it really can't be any more slower.

> Despite the name, `lldb-vscode` is not tied to VS Code and can be used from any text editor that implements the protocol.

I see, I'll give it a try then. Thanks.

**Comment by yyoncho** [comment]
@SuperPrower 

> Theoretically, can't you write one in elisp? There are implementations in JS family of languages, so I guess it really can't be any more slower.

Yes, you can. The performance here is not an issue, it is more of a standardized protocol decoupled from the implementation.

**Comment by yyoncho** [comment]
> https://github.com/WebFreak001/code-debug supports both gdb and lldb in case someone is interested.

I am working on that.

**Comment by yyoncho** [comment]
The integration with GBD and LLDB is in. 

@brotzeit you might be interested in integration this module in rustic and eventually add rust specific functionalities like "Debug Tests", "Debug Test at point" and so on. (Sorry for spam if you are not interested). 

![emacs myoncho_108](https://user-images.githubusercontent.com/13259670/53662929-efdec780-3c6c-11e9-8708-b43e55928641.png)

**Comment by LinArcX** [comment]
@yyoncho  How can we also use this feature?
I follow the instructions here:
https://github.com/llvm-mirror/lldb/tree/master/tools/lldb-vscode
But it's very complicated and i don't know what should i do.

**Comment by yyoncho** [comment]
@LinArcX can you share what are you doing? As a side note, you may use native debug it is easier to setup and it will work as long as you have gdb/lldb on your machine.

**Comment by brotzeit** [comment]
> @brotzeit you might be interested in integration this module in rustic and eventually add rust specific functionalities like "Debug Tests", "Debug Test at point" and so on. (Sorry for spam if you are not interested).

Oh, I completely missed this =)
Sounds interesting. I was looking for the rust file in this repo ;)

**Comment by yyoncho** [comment]
@brotzeit FYI dap-lldb.el and dap-gdb-lldb.el support Rust. dap-gdb-lldb does not seem to be "complete" since it does not support debugging multiple threads and does not set breakpoints unless the thread is stopped. https://github.com/vadimcn/vscode-lldb seems to be most complete but last time I checked it I was unable to figure it out. It seems like it adds a lot of stuff over the standard dap protocol. dap-lldb.el uses `lldb-vscode` which comes from lldb team and probably will be the way to go in the long term. We could implement stuff like https://marketplace.visualstudio.com/items?itemName=hdevalke.rust-test-lens which I am in the process of implementing for java. (as a side note, RLS supports test lenses - https://twitter.com/yonchovski/status/1139785948466561024 )

**Comment by brotzeit** [comment]
Sounds like a lot of work.

**Comment by yyoncho** [comment]
Yes. At least we have a lot of the infrastructure in place and it is much easier to implement most of the features on the emacs side compared to the effort that is needed on vscode side. Also, it is much easier to change the core(e. g. lsp-mode.el) than to do the same when you are writing vscode plugin. As a result, a lot of extension API just does not make sense but it is what vscode needs to make the stuff work. IMO the work on the language-specific protocol extensions is much more than the work on the core itself.

**Comment by iRi-E** [comment]
I'm testing CodeLLDB integration.
I wrote dap-codelldb.el and several changes in dap-mode.el.

![Testing dap-codelldb.el](https://user-images.githubusercontent.com/227146/68029835-6d2a7280-fcfb-11e9-97df-00b7ce1a926c.png)

**Comment by danielmartin** [comment]
Thanks. How does CodeLLDB compare to `dap-lldb.el` or `dap-gdb-lldb.el`? What do their DAP additions offer? There's many adapters for LLDB now and users will be confused when they need to choose one if we don't provide some general guidance.

**Comment by benbovy** [comment]
> How does CodeLLDB compare to dap-lldb.el or dap-gdb-lldb.el ?

Some feedback on using these different solutions from a rather inexperienced (I'm only getting started with dap/lsp), MacOS user: 

- `dap-lldb.el` : right now the installation is a bit painful. I manually downloaded `package.json` from [lldb-vscode](https://github.com/llvm-mirror/lldb/tree/master/tools/lldb-vscode), run `npm install`, and then I had to figure out how I could reuse a `lldb` binary distribution. Xcode command line tools doesn't ship `lldb-vscode`, but it's available in the homebrew `llvm` package. So I symlinked the `bin` and `lib` directories from `/usr/local/opt/llvm` into the vscode extension directory and in the end it worked fine. Maybe I can manually compile from scratch the whole thing, but that's not more straighforward.

-  `dap-gdb-lldb.el` : Installation is also not straightforward (at least in MacOS). I actually gave up trying to make it work (from both emacs and vscode). I first tried `gdb`, which can be installed using homebrew, but it is not codesigned in recent MacOS version. I'm not familiar with this, but the process seem a bit tedious. Then I tried `lldb`, which works fine when run from the command-line (both homebrew and xcode installed binaries). The xcode installation doesn't provide `lldb-mi`, though, but homebrew does. Still, when run from `dap-mode` I get the error `process launch failed: unable to locate debugserver`. I'm sure I miss something but I don't know what (`debugserver` and all `lldb*` binaries are in PATH).

- CodeLLDB: I only tried it from vscode, but as it ships its own lldb binaries, the installation is easy.

**Comment by goncalvesnelson** [comment]
@benbovy @danielmartin Can you guys share your debug-template configuration because I haven't been successful in running `dap-lldb.el` trying to attach to a running program. I did the same as @benbovy, manually downloaded the package.json, symlinked the `bin` and `lib` directories from the homebrew `llvm` package and ran `npm install`.  When I run the  `dap-debug` command I get the following message `No message handler for process` and it appears [I'm not alone](https://emacs.stackexchange.com/questions/53427/how-to-debug-c-dap-mode-lldb-or-gdb). If I list all the sessions using `M-x dap-ui-sessions` I can see the attach session and it is marked as `running` but it doesn't stop on any of the breakpoints I have set. 
This is the debug template I'm using 
```elisp
(dap-register-debug-template "mysqlshrec::attach_new"
                             (list :type "lldb"
                                   :cwd "/Users/nelson/development/git/repos/ngshell/bld/"
                                   :request "attach"
                                   :program "/Users/nelson/development/git/repos/ngshell/bld/bin/mysqlshrec"
                                   :name "mysqlshrec::attach_new"
                                   :waitFor t))
```
Thank you in advance.

**Comment by rbugajewski** [comment]
I’ve issues configuring a debug template for C++ (LLDB) on macOS. I tried a lot of different permutations and I just can’t get it running. I always get the following error messages:

```
dap--send-message: Process PeanutButterJellyBean not running
Debug session process exited with status: exited abnormally with code 127
```

I’ve modified the template according to the documentation:

```
(dap-register-debug-template "PeanutButterJellyBean"
  (list :type "lldb"
        :cwd "/tmp/PeanutButterJellyBean/build"
        :request "launch"
        :name "PeanutButterJellyBean"
        :program "/tmp/PeanutButterJellyBean/build/PeanutButterJellyBean"))
```

I also tried to run the process manually and then attach to it, but I always get the same messages.

I’m currently trying `(require 'dap-gdb-lldb)`, because the other integrations lead to nowhere. I can confirm that there was something downloaded to the `.extension/vscode` folder inside `.emacs.d`.

Any ideas what’s wrong with the template / setup?

**Comment by yyoncho** [comment]
what do you have in the stderr buffer? Also, try running the adapter outside of emacs.

**Comment by rbugajewski** [comment]
> what do you have in the stderr buffer?

It’s empty.

> Also, try running the adapter outside of emacs.

How do I do that? I could only find information about running it from `VSCode`, but I don’t use this editor. As far as I’ve researched this use case wouldn’t give me much insight as the plugin locations for VSCode and this extension are different.

I’ve also already manually compiled `lldb-mi` and moved it to `/usr/local/bin/lldb-mi`.

**Comment by yyoncho** [comment]
Try to run `dap-gdb-lldb-debug-program`

**Comment by rbugajewski** [comment]
The only command I’ve available after `(require 'dap-gdb-lldb)` that starts with dap-gdb is `dap-gdb-lldb-setup` (which I already executed and I think it correctly downloaded the extension).

**Comment by yyoncho** [comment]
No, `dap-gdb-lldb-debug-program` is variable holding what dap-mode will run when you start debugging. You have to try to run that command in the terminal to see what will happen.

**Comment by rbugajewski** [comment]
@yyoncho Thanks for your help, now I understand. I think this was the main issue.

It looks like the automatic setup would’ve assumed that I want to use `gdb` and `dap-gdb-lldb-debug-program` was set to `~/.emacs.d/.extension/vscode/webfreak.debug/extension/out/src/gdb.js`. I changed this to `~/.emacs.d/.extension/vscode/webfreak.debug/extension/out/src/lldb.js` and now I already get some output from the application I want to debug.

So now I see that the current debug session is running, I also see output from the application, and I can also see a breakpoint with `dap-ui-breakpoints`. But now the application doesn’t pause on the breakpoints I set?

**Comment by rbugajewski** [comment]
> dap-gdb-lldb does not seem to be "complete" since it does not support debugging multiple threads and does not set breakpoints unless the thread is stopped.

I’ve just carefully reread this thread and it looks like this is the issue I currently observe. I guess it’s time to try out another backend.

**Comment by rbugajewski** [comment]
I managed to get `dap-lldb` running, but I’m not sure if I ran into errors or if this is the current state of LLDB integration. In comparison to `dap-gdb-lldb` that seems to have issues with multi-threaded applications (breakpoints don’t pause execution reliably), but activates the breakpoints (they turn black after I run `dap-debug`), `dap-lldb` doesn’t activate breakpoints at all. I can manually pause threads, though.

Both integrations look like they would need some more work & love to properly work, or is it just a wrong impression I have and I need to fix my setup? Did anybody get LLDB C++ to reliably work on macOS with one of the adapters?

**Comment by yyoncho** [comment]
@rbugajewski afaics the issues are with the adapter itself, not with the dap-mode itself. AFAIK the vscode-lldb and the MS gdb adapter (from vscode-cpp) are more mature but we havent implemented the integration - these IMO should be used for debugging anything non-trivial. I have used the gdb one for debugging emacs and apart from the aforementioned limitations, it worked fine. I guess @danielmartin can provide info for lldb-vscode.

**Comment by danielmartin** [comment]
I use `lldb-vscode` with no troubles, but I haven't debugged something very sophisticated yet. Could you create an issue with specific steps to reproduce (could you provide a small sample project?) so we can investigate if the problem is in `dap-mode` or in the debug adapter?

**Comment by rbugajewski** [comment]
I tried various configurations in the recent weeks and also updated the dependencies, unfortunately to no avail. As an example project you can create a default Drogon project (see https://github.com/an-tao/drogon). You can find installation instructions at https://doxiz.com/drogon/master/installation/

It’s enough to create a new project (`drogon_ctl create project dap_debug_test`) with an empty controller (`drogon_ctl create controller TestCtrl`). Then just add one line to the handler (like `LOG_ERROR << "Break here";`) and add a breakpoint at this line. The default number of threads should be fine, but you can also experiment with this in `config.json` by changing the number of threads. Breakpoints stay gray, and when you break manually the threads show up just fine:

<img width="224" alt="Screen Shot 2020-04-09 at 11 42 10 AM" src="https://user-images.githubusercontent.com/24480/78881483-2c2b4c80-7a57-11ea-989f-fecd2638350c.png">

**Comment by zeroDivisible** [comment]
Would anybody have a step by step guide describing the preferred (or at least good enough) way to setup Emacs to debug Rust?

I tried following what @benbovy detailed in his comment above, but I've been struggling with the details. As much as I don't have issues compiling what's needed for i.e. `dap-lldb.el`, I'm not sure how to configure Emacs to use the package I created.

I'm using Spacemacs, not sure if this changes things much.

**Comment by yyoncho** [comment]
@zeroDivisible I will come back with a complete guide and even with integration via RA code lenses once I finish https://github.com/emacs-lsp/lsp-mode/issues/655 and once @adam-r-kowalski adds vscode-cpp support. I think that this is the best option for cpp/rust/etc out there.

**Comment by colormotor** [comment]
Any news on this front? I've been trying to get lldb to work on OSX, but no success. 
dap-gdb-lldb runs, but it ignores breakpoints. 
And I was not able to compile lldb-vscode, since there does not seem to be any specific instructions on  how to compile the binary. 
@danielmartin @benbovy Would you mind sharing details on how you did that?

**Comment by benbovy** [comment]
Sorry @colormotor I haven't used much dap-mode + lldb since then so I'm afraid I can't provide you with more details than  what's in https://github.com/emacs-lsp/dap-mode/issues/6#issuecomment-554348002.

**Comment by adam-r-kowalski** [comment]
I recommend grabbing the extension from vscode, installilng it from their store. The point your dap configuration to use that binary.

Unfortunately I have been pulled in a different direction at work so I will not have time to work on this for a while. It ended up being a bigger project then I thought, trying to support all native targets that I used (C++, Zig, Nasm, Rust) in a generic way, so I tended to just modify the configuration per project.

**Comment by colormotor** [comment]
Hi @adam-r-kowalski, thanks, I did as suggested and found the pre-compiled binaries in a VSCode [extension](https://marketplace.visualstudio.com/items?itemName=lanza.lldb-vscode). 

Calling `lldb-vscode` from command-line seems to execute the program but it does not start the usual lldb prompt (not sure if this is normal behaviour). However starting the debug session from emacs gives a throws a `(wrong-type-argument stringp null)` error with the backtrace copied below. Sorry if my questions are a bit naive, but I am still trying to get to grips with Elisp, so I was not able to step examine the variables at each stack frame yet. But I imagine the error may be due to the `nil` following the path to the lldb-vscode executable? 

Any clues on this, or suggestions/opinions on the (current) best route to debug C++ with lldb/emacs would be highly welcome:) 

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  #<subr make-process>(:name "Attach lldb" :connection-type pipe :coding no-conversion :command ("/Users/colormotor/.vscode/extensions/llvm-org.lldb-vscode-0.1.0/bin/lldb-vscode" nil) :stderr "*Attach lldb stderr*" :noquery t)
  apply(#<subr make-process> (:name "Attach lldb" :connection-type pipe :coding no-conversion :command ("/Users/colormotor/.vscode/extensions/llvm-org.lldb-vscode-0.1.0/bin/lldb-vscode" nil) :stderr "*Attach lldb stderr*" :noquery t))
  make-process--with-editor-process-filter(#<subr make-process> :name "Attach lldb" :connection-type pipe :coding no-conversion :command ("/Users/colormotor/.vscode/extensions/llvm-org.lldb-vscode-0.1.0/bin/lldb-vscode" nil) :stderr "*Attach lldb stderr*" :noquery t)
  apply(make-process--with-editor-process-filter #<subr make-process> (:name "Attach lldb" :connection-type pipe :coding no-conversion :command ("/Users/colormotor/.vscode/extensions/llvm-org.lldb-vscode-0.1.0/bin/lldb-vscode" nil) :stderr "*Attach lldb stderr*" :noquery t))
  make-process(:name "Attach lldb" :connection-type pipe :coding no-conversion :command ("/Users/colormotor/.vscode/extensions/llvm-org.lldb-vscode-0.1.0/bin/lldb-vscode" nil) :stderr "*Attach lldb stderr*" :noquery t)
  dap--create-session((:name "Attach lldb" :type "lldb" :request "launch" :cwd "/Users/colormotor/develop/autograff/strokestyles_system/apps/strokestyles_testbed/bin" :target "/Users/colormotor/develop/autograff/strokestyles_system/apps/strokestyles_testbed/bin/strokestyles_testbed" :dap-server-path ("/Users/colormotor/.vscode/extensions/llvm-org.lldb-vscode-0.1.0/bin/lldb-vscode" nil) :program "/Users/colormotor/develop/autograff/strokestyles_system/apps/strokestyles_testbed/src/main.cpp"))
  dap-start-debugging((:name "Attach lldb" :type "lldb" :request "launch" :cwd "${workspaceFolder}/bin" :target "${workspaceFolder}/bin/strokestyles_testbed" :dap-server-path ("/Users/colormotor/.vscode/extensions/llvm-org.lldb-vscode-0.1.0/bin/lldb-vscode") :program "/Users/colormotor/develop/autograff/strokestyles_system/apps/strokestyles_testbed/src/main.cpp"))
  dap-debug((:name "Attach lldb" :type "lldb" :request "launch" :cwd "${workspaceFolder}/bin" :target "${workspaceFolder}/bin/strokestyles_testbed" :dap-server-path ("/Users/colormotor/.vscode/extensions/llvm-org.lldb-vscode-0.1.0/bin/lldb-vscode") :program "/Users/colormotor/develop/autograff/strokestyles_system/apps/strokestyles_testbed/src/main.cpp"))
  funcall-interactively(dap-debug (:name "Attach lldb" :type "lldb" :request "launch" :cwd "${workspaceFolder}/bin" :target "${workspaceFolder}/bin/strokestyles_testbed" :dap-server-path ("/Users/colormotor/.vscode/extensions/llvm-org.lldb-vscode-0.1.0/bin/lldb-vscode") :program "/Users/colormotor/develop/autograff/strokestyles_system/apps/strokestyles_testbed/src/main.cpp"))
  call-interactively(dap-debug record nil)
  command-execute(dap-debug record)
  counsel-M-x-action("dap-debug")
  ivy-call()
  ivy-read("M-x " ("toggle-debug-on-error" "dap-debug" "lsp-workspace-folders-remove" "debug" "lsp-workspace-folders-add" "lsp-describe-session" "realgud--lldb" "jupyter-send-cell" "swiper" "latex-word-count-master" "ispell-continue" "org-babel-execute-buffer" "windresize" "jupyter-repl-associate-buffer" "org-latex-preview" "dap-switch-thread" "ispell-buffer" "org-babel-tangle-file" "projectile-compile-project" "jupyter-repl-associate-buffer-side" "dap-mode" "ielm" "pdf-tools-install" "delete-selection-mode" "eval-buffer" "jupyter-run-repl" "org-babel-tangle" "projectile-run-project" "helm-bibtex-with-local-bibliography" "describe-key" "lldb" "artist-mode" "magit" "doom/reload" "dap-ui-select-stack-frame" "figlet" "dap-hydra" "flyspell-mode" "dap-gdb-lldb-setup" "jupyter-org-interrupt-kernel" "dap-ui-repl" "dap-stop-thread" "+literate/reload" "lsp-find-definition" "dap-ui-mode" "helm-bibtex" "dap-disconnect" "+debugger/start" "gdb-many-windows" "org-table-shrink" ...) :predicate #f(compiled-function (x) #<bytecode 0x46873109>) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)
```

**Comment by yyoncho** [comment]
I will start working on integrating cpptools.

**Comment by IllustratedMan-code** [comment]
Hi there. I have run into a strange issue. I have the debugger working on spacemacs but I can't seem to run it (on purpose) to compile and debug a program with breakpoints. The executable (that I can debug) seems to randomly appear. The question I am asking is how do I compile (with breakpoints?). I just tried to run it on the most basic hello world program in c++. I run dap-debug on the c++ file and usually get nothing. sometimes an executable will appear ? Just using default config. Thanks

**Comment by rbugajewski** [comment]
> I have the debugger working on spacemacs but I can't seem to run it (on purpose) to compile and debug a program with breakpoints. 

@IllustratedMan-code Does your application use threads?

**Comment by IllustratedMan-code** [comment]
@rbugajewski, it does not. Here is my code: 

```
#include <iostream>
#include <cmath>

int main(){

    int testint = 1000;

    std::cout << "bonjour friend";
    std::cout << "after break";
    for (int i=0; i<5; i++){
      std::cout << "does the break work?";
    }
    testint = 5;
    std::cout << "again";


}

```
I have breakpoints at 9, 11, and 13 if that matters. The debugger functionality definitely works as once the executable exists I can use breakpoints and watch variables. I found that I can create an executable sometimes with the GDBserver connect configuration (I think), but it doesn't work very often. Once the executable exists I can run the default lldb configuration on it and it works. There seems to be a compile and debug option that just changed this morning from clang++ to g++ but they both fire the same error "Have you loaded the 'cppdbg' specific dap package?" I am new to this configuration stuff but I think that it has something to do with that. Does the default lldb config have compile abilites and if not, how do I add them?

**Comment by kentbull** [comment]
> @zeroDivisible I will come back with a complete guide and even with integration via RA code lenses...and once @adam-r-kowalski adds vscode-cpp support. I think that this is the best option for cpp/rust/etc out there.

@yyoncho Care to share your config?

**Comment by yyoncho** [comment]
> @yyoncho Care to share your config?

I am using spacemacs, what are you interested in?

**Comment by rbugajewski** [comment]
> I am using spacemacs, what are you interested in?

Something along the lines of a working configuration example to resolve this issue?

**Comment by yyoncho** [comment]
@rbugajewski https://emacs-lsp.github.io/lsp-mode/tutorials/CPP-guide/ has a working gdb configuration, I think that the only thing that you have to change in it is MIMode to lldb.

**Comment by yyoncho** [comment]
@rbugajewski also, for some languages like rust, there are interactive commands to start debugging.

**Comment by kentbull** [comment]
@rbugajewski @IllustratedMan-code @colormotor @goncalvesnelson I got this to work with the following launch.json and cmake config. The key bit I was missing was instructing CMake to build an executable with debug symbols. Of course you can debug only when you compile with debug symbols! I spent so much time on this >,<
I'm glad I learned so much!

For your information:
launch.json
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug HelloC Latest-1",
      "type": "cppdbg",
      "request": "launch",
      "program": "${workspaceFolder}/_build/HelloC",
      "args": [""],
      "stopAtEntry": false,
      "cwd": "${workspaceFolder}",
      "environment": [],
      "externalConsole": false,
      "MIMode": "lldb",
      "miDebuggerPath": "/usr/local/bin/lldb-mi"
    }
  ]
}
```
CMakeLists.txt
```
cmake_minimum_required (VERSION 3.10)

project (HelloC VERSION 1.1)

# configure_file(HelloCConfig.h.in HelloCConfig.h)

# target_include_directories(HelloC PUBLIC "${PROJECT_BINARY_DIR}")

set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Werror -std=c++14")
set (SRC_FILES
  ${PROJECT_SOURCE_DIR}/src/main.cpp
  ${PROJECT_SOURCE_DIR}/src/log.cpp
  ${PROJECT_SOURCE_DIR}/src/Math.cpp)

set (CMAKE_BUILD_TYPE Debug) # <-------- key bit right here

add_executable (HelloC ${SRC_FILES})
# include_directories(${PROJECT_SOURCE_DIR})
# add_executable(HelloC main.cpp log.cpp)

```
Ping me if you want some assistance with your config. I feel like I want to do a blog post on this now and to start from scratch since no guide out there seems to be straightforward enough and many guides assume you have things set up already.

**Comment by rbugajewski** [comment]
@yyoncho @kentbull Thanks so much! I’ll try these configurations in my spare time and see if something has changed for my multi-threaded project of yesteryear 🙂

**Comment by yyoncho** [comment]
@kentbull 

> I feel like I want to do a blog post on this now and to start from scratch since no guide out there seems to be straightforward enough and many guides assume you have things set up already.

FYI we are doing a series of tutorials in lsp-mode doc site - like this: https://emacs-lsp.github.io/lsp-mode/tutorials/debugging-clojure-script/ .  If you decide to write a blog what do you think about the following: create a post in your blog, then do that same post as lsp-mode tutorial and have a link at the beginning of the tutorial, something like: "This tutorial was originally posted by <> at <>" with links to your blog.

**Comment by kentbull** [comment]
@yyoncho That's great news! I will post my own experiences with your tutorials if you'd like. I'm coming up to speed on ClojureScript myself.

And I like giving credit where credit is due. I'll link to your blog post from mine.

**Comment by Mrzrb** [comment]
Hi @colormotor . Have you solve this problem ? I met this same issue.

**Comment by brotzeit** [comment]
https://github.com/emacs-lsp/dap-mode/issues/366#issue-704987502 maybe ?

**Comment by Mrzrb** [comment]
@colormotor I solved this problem in my case. I am also on  M1 mbp.

![image](https://user-images.githubusercontent.com/13942650/155866036-43adce67-bb11-4adc-924e-5f2e5eb7aa1f.png)

This is because config file issue. When i change `(setq dap-lldb-debug-program "/opt/homebrew/opt/llvm/bin/lldb-vscode")` to `(setq dap-lldb-debug-program `(, "/opt/homebrew/opt/llvm/bin/lldb-vscode"))`

This Issue disappeared.

**Comment by colormotor** [comment]
@Mrzrb Thx! Works for me too if I use the homebrew version of lldb-vscode. My (latest) issue turned out to be that I was using the version shipped with the Lanza VSCode plugin.
