### ISSUE TITLE
[dap-go] how to debug specify test function

### ISSUE THREAD

**Issue by edenzhong7** [emacs-lsp/dap-mode#604]
It seems that debug go test function will run all tests in current package, could I only debug single one test function like vscode? I saw that vscode launchs test bin with extra parameters ` -test.run ^TestLogger$ `.

**Comment by edenzhong7** [comment]
another question is how to show the doc of var or function in posframe instead of minibuffer, currently only can see the function signature without doc

**Comment by yyoncho** [comment]
@s-kostyaev is using go, so he might be interested in implementing this feature. As for the second question, you may use lsp-ui mouse hover or set lsp-ui-doc-show-with-cursor to t. Refer to https://emacs-lsp.github.io/lsp-mode/tutorials/how-to-turn-off/

**Comment by edenzhong7** [comment]
> @s-kostyaev is using go, so he might be interested in implementing this feature. As for the second question, you may use lsp-ui mouse hover or set lsp-ui-doc-show-with-cursor to t. Refer to https://emacs-lsp.github.io/lsp-mode/tutorials/how-to-turn-off/

thanks a lot, let me take a try

**Comment by s-kostyaev** [comment]
Implemented. See docs - https://emacs-lsp.github.io/dap-mode/page/configuration/#go

**Comment by kprav33n** [comment]
I see that this has been implemented only in `dap-dlv-go`. Is it possible to get the same behavior in `dap-go`?

**Comment by s-kostyaev** [comment]
> I see that this has been implemented only in `dap-dlv-go`. Is it possible to get the same behavior in `dap-go`? The original issue was for `dap-go`.

I think it is possible. But `dap-go` doesn't work for me. So I can't check if new code will work.

**Comment by yyoncho** [comment]
@kprav33n consider migrating to `dap-dlv-go`. dap-go will be deprecated at some point.
