### ISSUE TITLE
Add ability to use "substitutePath" with go debugger.

### ISSUE THREAD

**Issue by s-kostyaev** [emacs-lsp/dap-mode#607]
This can be very useful if your build environment differs from your development environment or if you use `-trimpath` build flag. Ideally it should be useful for interactive usage. Not sure how to implement it. Ideas are welcome.

**Comment by s-kostyaev** [comment]
Looks like for now the best option is `M-x` `dap-debug-edit-template` and then make something like:
```elisp
(dap-register-debug-template
 "Launch Executable sub"
 (list :type "go"
       :request "launch"
       :name "Launch Executable sub"
       :mode "exec"
       :program nil
       :args nil
       :env nil
       :substitutePath (list (ht ("from" "/home/user/projects/tribonacci") ("to" "github.com/s-kostyaev/tribonacci")))))
```
and use this edited template.

**Comment by s-kostyaev** [comment]
Maybe anyone can generate better option. If no we can add it to docs.

**Comment by yyoncho** [comment]
@s-kostyaev 

`:substitutePath` - I think this should be vector otherwise it will break for emacs 27+

**Comment by s-kostyaev** [comment]
@yyoncho will see. But it works for me on Emacs 29

**Comment by yyoncho** [comment]
@s-kostyaev is your emacs compiled with native json serialization support?

**Comment by s-kostyaev** [comment]
I should check it

**Comment by s-kostyaev** [comment]
> @s-kostyaev is your emacs compiled with native json serialization support?

@yyoncho yes
