### ISSUE TITLE
Mouse cursor jumps after clicking on any dap-ui control button

### ISSUE THREAD

**Issue by rhstanton** [emacs-lsp/dap-mode#609]
I'm running dap-mode to debug Python code in Emacs 28.1 under macOS 12.3.1. It runs fine, and I can debug just fine, except for one small thing. When I click on any of the control buttons to continue, step forward, etc., the action is taken just fine, but then the mouse cursor jumps to a point just below and to the left of the leftmost control (the same spot regardless of which button I click on), so to press a button again, I have to move the mouse. This is a minor issue, but I'm pretty sure the mouse shouldn't be jumping!

**Comment by yyoncho** [comment]
They have changed posframe package, setting posframe-mouse-banish-function  to nil should work (or setting it to 'ignore).

**Comment by rhstanton** [comment]
That works. Thanks!
