### ISSUE TITLE
:cwd does not work for dap-python

### ISSUE THREAD

**Issue by f279801** [emacs-lsp/dap-mode#61]
The compile command is currently being executed inside the dap-python--populate-start-file-args directly, which does not process the :cwd. We should only build up the program-to-start and let the dap-debug process it as usual.

**Comment by yyoncho** [comment]
I guess the fix will be what you have suggested in https://github.com/emacs-lsp/dap-mode/issues/57 .

**Comment by f279801** [comment]
Yes, if we're keeping the same idea of the current fix for that issue. It'll fix both.

**Comment by yyoncho** [comment]
Ok, I will assign both issues to you. Thank you.
