### ISSUE TITLE
dap-netcore launch option causing error when running dotnet

### ISSUE THREAD

**Issue by samwdp** [emacs-lsp/dap-mode#627]
When attempting to run the launch though dap debug there seems to be a problem with the way the dotnet run command for the dll is being built. For some reason there is a `-` after dotnet but even without that there needs to be a space after the dotnet and the location of the dll. Is this something that is a problem with the code or or the debug template?
```Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-w:/personal/csharp/src/FluentUri/bin/Debug/FluentUri.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.```

**Comment by samwdp** [comment]
sure. 
csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Fluent.Uri.Standard\Fluent.Uri.Standard.csproj" />
    <ProjectReference Include="..\..\src\Fluent.Uri.Core\Fluent.Uri.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

</Project>
```

I also get a *.*proj file created for some reason 
![image](https://user-images.githubusercontent.com/7193913/168873646-7d7d9ed3-ae3f-4be7-bad3-d6b7d0d45bef.png)

**Comment by s-kostyaev** [comment]
Could you also eval `(lsp-workspace-root)` in this buffer?

**Comment by samwdp** [comment]
hmm, is this because I am using an sln file?

**Comment by s-kostyaev** [comment]
> hmm, is this because I am using an sln file?

Maybe. I'm not sure yet.

**Comment by s-kostyaev** [comment]
Also is file `w:/personal/csharp/src/FluentUri/bin/Debug/FluentUri.dll` exists?

**Comment by samwdp** [comment]
Lsp workspace root: `"w:/personal/csharp/src/FluentUri"`
debugger command: `"c:/Users/samwd/.emacs.d/.cache/lsp/netcoredbg/netcoredbg/netcoredbg.exe"`

**Comment by samwdp** [comment]
that workspace root is incorrect the full path would be `W:\personal\csharp\src\FluentUri\examples\FluentUri.Example\bin\Debug\net5.0\FluentUri.Example.dll`

The source code is https://github.com/samwdp/FluentUri

**Comment by samwdp** [comment]
and i am trying to run the console application in the examples folder

**Comment by samwdp** [comment]
is my application just is a strange shape that the code to get the location to the dll cannot cope

**Comment by s-kostyaev** [comment]
You can now run your application in another terminal manually and attach to it from dap. And I should think how to extract this location from project automatically. Don't close this issue.

**Comment by samwdp** [comment]
I have been able to run it from a console and attach fine. Its just letting dap build and attatch that is the problem. It seems to me that this is assuming the .csproj is located in the same level as the lsp-workspace-root when in reality multi project applications will never do that. This is also broken if you split src and test projects into respective folder etc

**Comment by s-kostyaev** [comment]
Is where any good solution to automatically detect dll location?

**Comment by s-kostyaev** [comment]
I can provide manual selection of `.dll` as option. But this was reason of lots of misunderstanding

**Comment by s-kostyaev** [comment]
> I have been able to run it from a console and attach fine, this is just not a good option for running console application as they will more than likely finish execution before you can attach a debugger. Its just letting dap build and attatch that is the problem. It seems to me that this is assuming the .csproj is located in the same level as the lsp-workspace-root when in reality multi project applications will never do that. This is also broken if you split src and test projects into respective folder etc

It will work fine if emacs will get every project from multi-project solution as another project. Could you try this setup?

**Comment by s-kostyaev** [comment]
@samwdp please try to debug with attached pull request

**Comment by samwdp** [comment]
@s-kostyaev so this is a step closer but still getting this
```
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-w:/personal/csharp/src/FluentUri/examples/FluentUri.Example/bin/Debug/net5.0/FluentUri.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```
The path is correct but the dll is wrong. when running from the Fluent.Example project the dll should be FluentUri.Example.dll

**Comment by s-kostyaev** [comment]
@samwdp fix force pushed

**Comment by samwdp** [comment]
![image](https://user-images.githubusercontent.com/7193913/168893521-d347263b-01b7-45e2-9d57-84ec7a98eac9.png)
I am now having other issues with LSP for some reason not respecting .git as the root of the project, instead, going up one more directrory. But not for the project that I have been using for testing this

**Comment by samwdp** [comment]
but I can fix that by adding the folder to the workspace root and then the debugging works correctly

**Comment by samwdp** [comment]
Well done 😊

**Comment by s-kostyaev** [comment]
> ![image](https://user-images.githubusercontent.com/7193913/168893521-d347263b-01b7-45e2-9d57-84ec7a98eac9.png) I am now having other issues with LSP for some reason not respecting .git as the root of the project, instead, going up one more directrory. But not for the project that I have been using for testing this

I think it is not lsp work. It is work of projectile or project.el. And this should be addressed in another issue.

**Comment by s-kostyaev** [comment]
> Well done 😊

Thank you for report 🙂

**Comment by yyoncho** [comment]
@s-kostyaev your emacs looks very nice.

**Comment by s-kostyaev** [comment]
> @s-kostyaev your emacs looks very nice.

In this thread there are no my screencasts. It's @samwdp :smiley:

**Comment by samwdp** [comment]
@yyoncho thanks. It's a modified gruvbox. Based on the included one in doom-themes. You can find it in my emacs config repo
