### ISSUE TITLE
Breakpoints completely ignored

### ISSUE THREAD

**Issue by triccare** [emacs-lsp/dap-mode#634]
Hopefully a simple thing. For Python, running under dap-mode, breakpoints, either set through dap-mode, or explicitly using the `breakpoint` statement, are ignored, and the script runs through to completion.

The odd thing is that the only thing that occurred recently is an upgrade from macOS Catalina to Monterey.
Some rudimentary info is below; tell me how and more details can be provided.

Details:

- emacs 28.1
- spacemacs dev using dap layer
- debugpy configured
- macos monterey

**Comment by d-miketa** [comment]
I have exactly the same issue on Doom Emacs with natively compiled 28.1.

**Comment by yyoncho** [comment]
can you try this: https://github.com/emacs-lsp/dap-mode/issues/636#issuecomment-1158896842
