### ISSUE TITLE
debugpy Default Config returns Invalid Message

### ISSUE THREAD

**Issue by christmoore** [emacs-lsp/dap-mode#642]
Latest `dap-mode` (Melpa 20220712.919) with debugpy 1.6.2 is returning the following on `dap-debug`, choosing default templates returns:
```
Warning (emacs): Initialize request failed: Invalid message: "program" must be str
```
for `buffer` and `pointer` templates, and:
```
Warning (emacs): Initialize request failed: Invalid message: "cwd" must be str
```

for `file`.

I'm not sure if this is a configuration issue on my end, but here is relevant config:
```
(use-package dap-mode
  :straight t
  :custom
  (dap-auto-configure-features '(sessions locals controls tooltip))
  (dap-python-debugger 'debugpy)
  :config
  (require 'dap-python))
```
stepping through edebugger shows `launch-args` evaluating with:
```
Result: (:type "python" :module "pytest" :request "launch" :name "Python :: Run pytest (buffer)" :args ("/Users/chrismoore/Projects/...") :dap-server-path ("/Users/chrismoore/.asdf/shims/python" "-m" "debugpy.adapter"))
```

Are default templates not expected to work? I see the project still defaults to `ptvsd` (which runs as expected)

**Comment by christmoore** [comment]
Looks like this arose from https://github.com/emacs-lsp/dap-mode/pull/559 in [this block](https://github.com/emacs-lsp/dap-mode/pull/559/files#diff-1ff6fc9a338b1b10cb54aa92fb6544090886f0a0348abe6e345d2df902918223R1725-R1744).

I know very little of elisp or how to properly debug, but I assume `cwd` and `program` are receiving `nil` in some way. Hopefully this points someone in the right direction.

**Comment by ForecastHealth** [comment]
Wanted to say that this is happening to me as well.

**Comment by christmoore** [comment]
> thank you for the info, its very strange (at least) that cwd and program receive nils

This was an absolute guess, as I don't have enough Elisp experience to confirm whether that is the case. However, from following discussions within https://github.com/emacs-lsp/dap-mode/issues/306, `nil` is an issue for `debugpy`, and work was done to make sure they don't get passed down the chain to ensure support.

> To be clear, is ptvsd working as expected with up-to-date dap-mode?

Right - just removing ` dap-python-debugger 'debugpy)`, thereby reverting to `ptvsd`, allows this to work as expected. I'm on latest master `dap-mode`.

> Are you reverting only one block (you mentioned) or a full PR to make everything work?

Reverting the one block, so it's definitely isolated to there.

> @christmoore , and one more thing, are you using containers or just plain same-machine configuration?

Plain same-machine configuration

**Comment by factyy** [comment]
@christmoore , may I ask you to replace the following block:
https://github.com/emacs-lsp/dap-mode/blob/31f92f678cc0c2404bb2a9e6af7113dc73f11d27/dap-mode.el#L1741-L1742

with this one:
```elisp
(if cwd
    (plist-put translated-launch-args :cwd (funcall (dap--debug-session-local-to-remote-path-fn debug-session) cwd)))
(if program
    (plist-put translated-launch-args :program (funcall (dap--debug-session-local-to-remote-path-fn debug-session) program)))
```
and write back has it solved the issue.

@yyoncho , am I right that `cwd` and `program` were never meant to be `nil`s: they are either missing from `launch-args` completely or have meaningful values?

**Comment by JosephFerano** [comment]
@factyy

I am experiencing the same issue but with netcoredbg and C#/F#, I get a slightly different error;

```
Warning (emacs): Initialize request failed: can't parse: [json.exception.type_error.302] type must be string, but is null Disable showing Disable logging
```

This is what is being sent

```
Sending: 
{
  "command": "launch",
  "arguments": {
    "type": "coreclr",
    "request": "launch",
    "mode": "launch",
    "name": "NetCoreDbg::Launch<2>",
    "program": "/home/joe/Development/test-csharp/bin/Debug/net6.0/test-csharp.dll",
    "cwd": null
  },
  "type": "request",
  "seq": 3
}
```
And then this is what is received
```
Received:
{
  "command": "launch",
  "message": "can't parse: [json.exception.type_error.302] type must be string, but is null",
  "request_seq": 3,
  "seq": "5",
  "success": null,
  "type": "response"
}
```

Good news is that it is resolved with the last snippet of code you included.

**Comment by cpackard** [comment]
@factyy I just tried your `(if cwd ...)` [fix](https://github.com/emacs-lsp/dap-mode/issues/642#issuecomment-1189112541) and that got the default `dap-python` debug templates working again for me with `debugpy` - thanks for sharing!

**Comment by factyy** [comment]
@cpackard @JosephFerano thx! I'll open a PR with this fix: looks like not all debug providers / templates provide valid `cwd` & `program` values..
