### ISSUE TITLE
Add support for python attach request

### ISSUE THREAD

**Issue by f279801** [emacs-lsp/dap-mode#67]

**Comment by f279801** [comment]
As suggestion from @yyoncho at #64, I'm looking on how to support attach request for python debugging.

**Comment by nbfalcon** [comment]
For anyone stumbling on this: dap-mode now supports debugpy, which can be configured using the following snippet:
```emacs-lisp
(setq dap-python-debugger 'debugpy)
```
The latter supports attach requests. (See the MS VSCode docs for details)

**Comment by matt-continuousdelta** [comment]
There are more recent comments at https://github.com/emacs-lsp/dap-mode/issues/406#issuecomment-727628950 and https://github.com/emacs-lsp/dap-mode/issues/438#issuecomment-782611203 indicating that attach requests don’t work with debugpy as of 2021-02-20.

**Comment by matt-continuousdelta** [comment]
I spent some time debugging and opened a draft PR #451.

**Comment by aiguofer** [comment]
@matt-continuousdelta did #451 solve this issue? Maybe it can be marked as done?
