### ISSUE TITLE
Invalid Function Error

### ISSUE THREAD

**Issue by bridgesense** [emacs-lsp/dap-mode#676]
I've noticed that dap-mode is no longer working with treemacs again.  I'm getting an error when dap-mode tries to open a treemacs window using dap-php:

```
error in process filter: lsp-treemacs--generic-icon: Invalid function: (icon (plist-get item :icon))
error in process filter: Invalid function: (icon (plist-get item :icon))
```

Not sure how long this has been broken, but I skated back to a backup I made before Sept 24 updates and everything works again.

**Comment by bridgesense** [comment]
I'm no longer getting this error. Considering no one has touched this, it my be best to close it?

**Comment by bridgesense** [comment]
No longer reproducible.

**Comment by yyoncho** [comment]
This was fixed in lsp-treemacs
