### ISSUE TITLE
DAP current line red cursor is not showing

### ISSUE THREAD

**Issue by richard-themedium** [emacs-lsp/dap-mode#678]
Could not find the red cursor of DAP mode

I just wrote test code (golang)

And run dap (Go Dlv Test Current Function Configuration)

I caught cursor of the breakpoint with dap-mode obviously

But I couldn't see the red cursor.

- OS: OSX 12.4 (arm64)
- go version: 1.19
- dlv version: 1.9.1
- emacs version: 29.0.50
- dap version: 20220921.941
- dap configuration
```emacs-lisp

(use-package dap-mode
  :ensure t
  :config
  (require 'dap-ui)
  (require 'dap-lldb)
  (require 'dap-node)
  (require 'dap-dlv-go)
  (require 'dap-gdb-lldb)
  
  (dap-mode 1)
  (dap-ui-mode 1)
  (tooltip-mode 1)
  (dap-tooltip-mode 1)
  (dap-ui-controls-mode 1)
  
  (setq left-fringe-width 16)
  (set-fringe-style (quote (12 . 8)))
  (setq dap-print-io t)
  (setq dap-mouse-popup-timeout 1)
  (setq dap-ui-variable-length 100)
  (setq dap-tooltip-mouse-motions-active t)
  
  (setq dap-auto-configure-features '(locals expressions breakpoints tooltip))
  )

```

<img width="764" alt="image" src="https://user-images.githubusercontent.com/108319636/195348223-76cc0e9d-6000-4a65-b9b6-28f6fef73638.png">

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/108319636/195348577-bc857668-e906-4ef5-8971-e1a8fd420865.png">

Already printed start to console
current cursor is next line of "log.Println("start")"
I pressed '(dap-next) just one time
but I can't find the red cursor
(Additionally, I cant see local variables of Locals buffer)

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/108319636/195349209-4b273a0f-cb66-4f36-af5c-6aa685cc433e.png">

**Comment by richard-themedium** [comment]
All is ok after update packages today. 

Close this issue

**Comment by yyoncho** [comment]
Yeah, it was fixed in dap-mode but it was reported on multiple places.
