### ISSUE TITLE
Can't get dap-python to work

### ISSUE THREAD

**Issue by Szkered** [emacs-lsp/dap-mode#68]
How do I get dap-mode to work for python? Once I launch `dap-debug` it hangs at the compilation buffer I see this warning `Invalid function: with-connection-local-variables`. I'm using Emacs 27 compiled from source and spacemacs dev branch. `lsp` was added through spacemacs layers, and I have `ptvsd` installed.

**Comment by yyoncho** [comment]
I was getting the same error at some point but it was fixed when I recompiled to the latest Emacs 27 version. Now I have exactly the same setup (emacs 27 + spacemacs dev) and it works. For reference, I am synched to 

> b619777dd6 * origin/master Allow a CC Mode derived mode to have strings delimited by single quotes.

(just to be sure, you may do `git clean -xfd` before recompiling to enforce clean build).

**Comment by yssource** [comment]
dap-python works for me very well with the latest Emacs 27. But, I hope spacemacs would integrate dap-python with its python layer as soon as possible.

**Comment by yssource** [comment]
oh, dap-hydra helps me a lot.

**Comment by yyoncho** [comment]
> dap-python works for me very well with the latest Emacs 27. But, I hope spacemacs would integrate dap-python with its python layer as soon as possible.

It will happen at some time but you could use it even now with the following code (add `dap` to your layers list):

```
(spacemacs/set-leader-keys-for-major-mode 'python-mode "db" nil)
(spacemacs/dap-bind-keys-for-mode 'python-mode)
```

**Comment by Szkered** [comment]
Cool, this works for me and it turns out that I didn’t do `git clean -xfd`. Btw, any idea on debugging multiprocessing python with dap?

**Comment by yyoncho** [comment]
@Szkered sorry I have no clue. I guess someone with better python understanding might research whether the python debug adapter supports that. If it doesn't I think that there is one more python debug adapter and we might try with it as well. dap-mode itself supports multithread debugging.

**Comment by yyoncho** [comment]
@yssource https://github.com/syl20bnr/spacemacs/pull/12177
