### ISSUE TITLE
has dap-php been abandoned?

### ISSUE THREAD

**Issue by bridgesense** [emacs-lsp/dap-mode#689]
dap-php mode isn't working for me at all now. It used to, intermittently between treemacs updates at least.

dap-php doesn't even try to talk to xdebug. It's not even throwing any errors. I abort dap-mode and I have to physically kill the dap-ui buffer to run dap-php again.  It doesn't matter anyway, as it doesn't appear to be even accessing the plugin.

I was curious if this had something to do with a new release for the visual studio plugin. So I made the mistake of deleting the plugin and tried to reinstall it with dap-php-setup. That doesn't work at all -- it hasn't for a long time and there has been no actionable response that issue either: [see issue #598](https://github.com/emacs-lsp/dap-mode/issues/598)

Has dap-php mode been abandoned?

**Comment by bridgesense** [comment]
I should clarify "not working". Stepping appears to be working. It's just the local variable display that is broken.

I'm running spacemacs which happens to run on a rolling release of Melpa.  Maybe, that's my issue. I'll try tapping into stable.  Hopefully, others have had some success there.

**Comment by bridgesense** [comment]
I loaded a new version of spacemacs, modified the core-configuration-layer.el to use melpa stable over the current version.  That had no effect.  Evidently, the melpa stable branch version of treemacs isn't compatible with the stable release of dap-php either.

I noticed some references to alternatives to treemacs in lsp-mode.  Is there an alternative to using treemacs?

**Comment by bridgesense** [comment]
Just out of desperation here... could the native emacs [tree-widget](https://github.com/emacs-mirror/emacs/blob/master/lisp/tree-widget.el) replace treemacs?

**Comment by yyoncho** [comment]
> Just out of desperation here... could the native emacs [tree-widget](https://github.com/emacs-mirror/emacs/blob/master/lisp/tree-widget.el) replace treemacs?

It was using treewidget and we moved to treemacs because treewidget is deadly slow, does not support async, etc.

**Comment by yyoncho** [comment]
> I was curious if this had something to do with a new release for the visual studio plugin. So I made the mistake of deleting the plugin and tried to reinstall it with dap-php-setup. That doesn't work at all -- it hasn't for a long time and there has been no actionable response that issue either: [see issue #598](https://github.com/emacs-lsp/dap-mode/issues/598)

This issue is well known, and for now we have a workarround - to download the extension and put it in GH and download it from gh. The problem is caused by vscode rate limitters. The other option on your side is to download the extension and extract it manually.


> I'm running spacemacs which happens to run on a rolling release of Melpa. Maybe, that's my issue. I'll try tapping into stable. Hopefully, others have had some success there.

Try deleting the melpa dir and install all packages again after a restart. Make sure that you are using melpa versions. There were breaking changes in treemacs but now it should be working.

**Comment by bridgesense** [comment]
> This issue is well known, and for now we have a workarround - to download the extension and put it in GH and download it from gh. The problem is caused by vscode rate limitters. The other option on your side is to download the extension and extract it manually.

I had a backup on another drive. Thanks for the clarification.

> Try deleting the melpa dir and install all packages again after a restart. Make sure that you are using melpa versions. There were breaking changes in treemacs but now it should be working.

I dumped Spacemacs, and installed a clean version of emacs28. I reloaded a stock .emacs config with some of the necessary base packages.  Everything works except the variable display. No variables are displayed, even after stepping through a couple of lines.

It looks like I have the latest code from melpa.  The dapui has been restored.

I might mess around around with your commit at [a62281ccbd8143a9cc552d2f07738a60d1de208f](https://github.com/emacs-lsp/dap-mode/commit/a62281ccbd8143a9cc552d2f07738a60d1de208f) just for kicks, and see what it would take to revert back to tree-widgets.

**Comment by yyoncho** [comment]
Can you provide the corresponding log, in particular the requests related to variables. Set dap-print-io to t and look in the messages buffer. Going to tree-widgets is not an option and the issue is most likely not related to treemacs.

**Comment by bridgesense** [comment]
I'm an idiot. I was hitting return to expand the variables.  I needed to hit the tab key.  They are all there. :(

Thanks, for your patience.

**Comment by yyoncho** [comment]
FWIW you can use the mouse as well. dap-mode/lsp-mode can be used/discovered using the mouse.
