### ISSUE TITLE
Interactive input to cli golang

### ISSUE THREAD

**Issue by JensAc** [emacs-lsp/dap-mode#691]
I have a problem debugging a golang cli. When I start debugging by `dap-debug` the debugger runs fine. However, my program prompts for user input, but the buffer does not allow for input at the moment. Is this generally possible?

**Comment by yyoncho** [comment]
It is possible, but it is case by case. do you have vterm installed?

**Comment by JensAc** [comment]
Thanks for the prompt response :slightly_smiling_face: Yes, vterm is installed.

**Comment by s-kostyaev** [comment]
Easy workaround is to use attach to already running in external terminal process. For better solution I should dig deeper.

**Comment by JensAc** [comment]
Ok, I see. Then starting debugging is a two step process. Not actually what I was looking for, but I am fine with that solution.

**Comment by s-kostyaev** [comment]
@JensAc You can try it now: `M-x` `dap-dlv-go-debug-in-vterm`
Or if you need to add arguments to your command `C-u` `M-x` `dap-dlv-go-debug-in-vterm`

**Comment by JensAc** [comment]
Hi @s-kostyaev, works perfectly fine for me. Thank you very much :+1:
