### ISSUE TITLE
dap-dlv-go: Support debugging specific sub tests in Go

### ISSUE THREAD

**Issue by kavirajk** [emacs-lsp/dap-mode#692]
Currently we could debug a single test (dap-mode figure out test function name via `dap-dlv-go--extract-current--method-or-function-name` [here](https://github.com/emacs-lsp/dap-mode/blob/master/dap-dlv-go.el#L111) and pass it as argument to `-test.run` [here](https://github.com/emacs-lsp/dap-mode/blob/master/dap-dlv-go.el#L91).)

Would be nice to have some ways to debug Go sub tests instead of running a full test. 

Current workaround is to comment every other sub tests. But doesn't scale well for Go test with more than modest amount of sub tests.

**Comment by yyoncho** [comment]
cc @s-kostyaev

**Comment by s-kostyaev** [comment]
Will see what we can do
