### ISSUE TITLE
Unable to set breakpoints when debugging Java on Windows

### ISSUE THREAD

**Issue by efbrasil** [emacs-lsp/dap-mode#695]
**Describe the bug**

I'm unable to set breakpoints in Java source code when running dap-mode / lsp-java on Windows. As far as I can tell, this behaviour was introduced by dap-mode's commit 5e449c864107e08353fd21c44897c4d480190d94. Prior to that commit, the `path` parameter in the `setBreakpoints` message was `(if (eq system-type 'windows-nt) (s-replace "/" "\\" file-name) file-name)`, where `file-name` is the full path of the file with `/` as the directory separator instead of `\\`.

After that commit, the `path` parameter in the `setBreakpoint` request became `(--> debug-session dap--debug-session-local-to-remote-path-fn (funcall it file-name))`, where `local-to-remote-path-fn` is a function in `dap--debug-session`. If not defined elsewhere, that function defaults fo `dap--local-to-remote-path-identical`, which doesn't replace the `/`. by `\\`s.

The debug server handler for the `setBreakpoints` request is able to receive a file path or a URI. To distinguish one from the other, `com.microsoft.java.debug.core.adapter.AdapterUtils.isUri()` will try to `new URI(path)` and, if no exceptions are raised, it will treat `path` as an URI.

Now when dap-mode sends a path with `/`s instead of `\\`, a path like `c:/users/myuser/app.java` will be reconized as an URI, since `java.net.URI` considers any string with the syntax `[scheme:]scheme-specific-part[#fragment]` to be an URI. In the given example, the path will be treated as an URI with the scheme `c` and specific part `/users/myuser/app.java`. Later, when the debug server tries to open the file referenced by that URI it fails, since it doesn't know how to locate an URI of the `c` scheme (`file:/c:/users/myuser/app.java` would be a valid URI to that file).

Note that a `local-file-path` still gets defined as the path with `\\`s instead of `/`s, however that variable isn't used anywhere.

**To Reproduce**

Open any `.java` file on Windows, set a breakpoint and start debugging. The process won't stop at the breakpoint. Setting `dap-print-io` to `t`, shows that the response to the `setBreakpoints` request says that the breakpoint was not verified.

**Expected behavior**

Emacs should send a path to the `setBreakpoint` request that de debug server can understand.

**Comment by yyoncho** [comment]
https://github.com/emacs-lsp/dap-mode/pull/688

**Comment by efbrasil** [comment]
You're correct, it's the same bug and the proposed patch fixes it. Thanks!
