### ISSUE TITLE
Persistently amend current debug templates or register own

### ISSUE THREAD

**Issue by ondrej-ivanko** [emacs-lsp/dap-mode#717]
Hi,

the debugger works mostly very well for me. I have a question - is it possible to persistently change current debugging templates provided by dap-mode layer. It's tiresome to change it everytime I shutdown Emacs. Or maybe register my own. There doesn't seem to be a way to do that.

If possible, please can you share configuration for it in .spacemacs file.

Thank you.

**Comment by yyoncho** [comment]
You may use json (the vscode format) and keep the configuration in launch.json.
You may persist it in elisp file or in your `.spacemacs` and load it.
