### ISSUE TITLE
Strange ui behaviour

### ISSUE THREAD

**Issue by lane-s** [emacs-lsp/dap-mode#72]
dap-mode seems really awesome, but I'm getting some strange behavior with the ui when using it with `dap-gdb-lldb`. I navigate to a buffer with a breakpoint and run `dap-debug` and select the LLDB run configuration and my executable. The debugger connects, but then an empty buffer with the name `??` pops up in place of the .cpp file I was viewing. I can manually call `dap-ui-repl` to get the debugger repl, but when I step through the code (i.e. using `n`), the repl buffer switches to the file being debugged with the arrow pointing to the current line. This is quite annoying because then I have to switch back to the repl buffer to continue stepping.

**Comment by yyoncho** [comment]
which version of dap-mode do you use? 
Do you have: https://github.com/emacs-lsp/dap-mode/commit/7a5d3f3dd87d97bdb6a710886f177de559a2ab67 ? Also, can you provide detailed steps to reproduce, ideally with some minimal cpp file which I can compile and test against?

**Comment by lane-s** [comment]
I think part of the issue is I'm not sure exactly what the intended behavior is. Is running `dap-debug` supposed to open any ui windows besides the `*out*` buffer, or is all that supposed to be done manually?

Regarding the issue with the '??' buffer, after trying to come up with a minimal example, I've found that the issue was occurring when calling functions from another library. My guess is that somehow lldb was pausing while executing code from that library, and since I don't have the source code in my project it obviously can't be displayed. Oddly, when I step into the part of my code that calls the library, I can step over it without ever encountering the issue. Maybe it's possible to have a more informative message in the `??` buffer? When I first encountered it, I had no idea that I could even continue stepping through the code. Do you know if that's part of `dap-mode`, or is it part of Native Debug?

**Comment by yyoncho** [comment]
> I think part of the issue is I'm not sure exactly what the intended behavior is. Is running dap-debug supposed to open any ui windows besides the *out* buffer, or is all that supposed to be done manually?

dap-mode opens only \*out\* buffer by default.

> Maybe it's possible to have a more informative message in the ?? buffer?

I think this is dap-mode bug which is caused by debug adapter stopping in file that is not present. Can you set dap-print-io to t and inspect messages buffer and look for such file name?

**Comment by lane-s** [comment]
Ok, yeah I think that's right.

Here's the relevant output:
```
Received:
{
  "body": {
    "stackFrames": [
      {
        "name": "_dyld_debugger_notification@0x0000000100019afa",
        "column": 0,
        "line": -1,
        "source": {
          "sourceReference": 0,
          "path": "??",
          "name": "??"
        },
        "id": 1
      },
      {
        "name": "gdb_image_notifier(dyld_image_mode, unsigned int, dyld_image_info const*)@0x0000000100018fef",
        "column": 0,
        "line": -1,
        "source": {
          "sourceReference": 0,
          "path": "??",
          "name": "??"
        },
        "id": 257
      },
      {
        "name": "notifyGDB(dyld_image_states, unsigned int, dyld_image_info const*)@0x0000000100018c84",
        "column": 0,
        "line": -1,
        "source": {
          "sourceReference": 0,
          "path": "??",
          "name": "??"
        },
        "id": 513
      },
      {
        "name": "dyld::notifyBatchPartial(dyld_image_states, bool, char const* (*)(dyld_image_states, unsigned int, dyld_image_info const*), bool, bool)@0x000000010000d429",
        "column": 0,
        "line": -1,
        "source": {
          "sourceReference": 0,
          "path": "??",
          "name": "??"
        },
        "id": 769
      },
      {
        "name": "ImageLoader::link(ImageLoader::LinkContext const&, bool, bool, bool, ImageLoader::RPathChain const&, char const*)@0x000000010001ac12",
        "column": 0,
        "line": -1,
        "source": {
          "sourceReference": 0,
          "path": "??",
          "name": "??"
        },
        "id": 1025
      },
      {
        "name": "free@0x00007fff67a0019a",
        "column": 0,
        "line": -1,
        "source": {
          "sourceReference": 0,
          "path": "??",
          "name": "??"
        },
        "id": 1281
      }
    ]
  },
  "success": true,
  "command": "stackTrace",
  "request_seq": 10,
  "type": "response",
  "seq": 19
}

```
