### ISSUE TITLE
Sending commands to GDB when debugging C++

### ISSUE THREAD

**Issue by jmcarcell** [emacs-lsp/dap-mode#725]
Is there any way of sending commands to GDB directly when debugging C++? There are some commands for which I can't find them through the dap interface like `finish`

**Comment by yyoncho** [comment]
M-x dap-ui-repl (I think that some of the adapters required prefixing with ` or something).

**Comment by jmcarcell** [comment]
Hmm I tried several combinations but nothing seems to work:
```
>> help
{"token":28,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[]}}
>> `finish
Undefined command: "".  Try "help". (from interpreter-exec --thread 1 --frame 0 console "`finish")
>> `help`
Undefined command: "".  Try "help". (from interpreter-exec --thread 1 --frame 0 console "`help`")
>> ```help```
Undefined command: "".  Try "help". (from interpreter-exec --thread 1 --frame 0 console "```help```")
>> 
```
It seems it doesn't take it for some reason, when it's `HELP` instead of `help` or any command in caps it appears after `Undefined command`

**Comment by jmcarcell** [comment]
That was using the default configuration for GDB and some commands do work like `next` `step` but not all of them. Using `cpptools` instead indeed it works when prefixing a ` before the command:
```
>> `print a
$2 = 3

```
So I'll stick to this one

**Comment by yyoncho** [comment]
Then we can close it?

**Comment by jmcarcell** [comment]
Yes, thanks for the help!
