### ISSUE TITLE
dap-ui Locals buffer causes unresponsiveness when expanding trees

### ISSUE THREAD

**Issue by sambrenner** [emacs-lsp/dap-mode#728]
MacOS 13.3.1, using railwaycat/homebrew-emacsmacport 28.2.

With a clean install, having `~/.emacs.d/init.el` containing the following:

```elisp
(setenv "JAVA_HOME" "/Users/me/.sdkman/candidates/java/current")

;; lsp-java quick start from readme
(condition-case nil
    (require 'use-package)
  (file-error
   (require 'package)
   (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
   (package-initialize)
   (package-refresh-contents)
   (package-install 'use-package)
   (setq use-package-always-ensure t)
   (require 'use-package)))

(use-package projectile)
(use-package flycheck)
(use-package yasnippet :config (yas-global-mode))
(use-package lsp-mode :hook ((lsp-mode . lsp-enable-which-key-integration)))
(use-package hydra)
(use-package company)
(use-package lsp-ui)
(use-package which-key :config (which-key-mode))
(use-package lsp-java :config (add-hook 'java-mode-hook 'lsp))
(use-package dap-mode :after lsp-mode :config (dap-auto-configure-mode))
(use-package dap-java :ensure nil)
(use-package helm-lsp)
(use-package helm
  :config (helm-mode))
(use-package lsp-treemacs)
```

And with a test java project `~/java-test/src/com/test/Test.java` containing the following:

```java
package com.test;

import java.util.List;

public class Test {
  public static void main(String[] args) {
    String a = "abc";
    String b = "def";
    List<String> c = List.of(a, b);
    System.out.println(c.toString());
  }
}
```

Place a breakpoint on line 10 of `Test.java` (the `println` line) and run `dap-java-debug`. When `dap-ui` appears, expanding the list `c` in the Locals buffer will cause emacs to become unresponsive and hang indefinitely. Expanding the `value` of one of the strings will cause the same behavior.

I've left it going for about 10 minutes now with `toggle-debug-on-error` and nothing has come up yet, I will add a further comment if that changes.

Mashing `C-g` will bring emacs back to responsiveness, with some residual lag.

Happy to follow up with any other required info. Thank you!

**Comment by yyoncho** [comment]
can you test with the latest lsp-treemacs?

**Comment by yyoncho** [comment]
> can you test with the latest lsp-treemacs?

Ignore, I was able to reproduce

**Comment by sambrenner** [comment]
Works for me now. Thank you!

**Comment by gnuemacscoin** [comment]
With this patch in place, the locals buffer now erroneously omits the last element of any java array. Removing the `1-`es in
``` elisp
                (append (when (and indexed-variables (< 0 indexed-variables))
                          (list :start 0
                                :filter "indexed"
                                :count (1- (min indexed-variables dap-ui-default-fetch-count))))
                        (when (and named-variables (< 0 named-variables))
                          (list :start 0
                                :filter "named"
                                :count (1- (min named-variables dap-ui-default-fetch-count))))))
```
fixes it for me.
