### ISSUE TITLE
locals ui treemacs is infinitely expanding on stack frame switch (python)

### ISSUE THREAD

**Issue by zackattackz** [emacs-lsp/dap-mode#740]
Hello,

I am having an issue where when I switch stack frames the locals tree is attempting to infinitely expand. This causes emacs to hang for a few seconds, and then it gives up after a certain point. It can be circumvented by collapsing the locals tree before switching stack frames, but this is very tedious.

In the message buffer, this error appears: [Treemacs] This function cannot expand a node of type 'nil'. Current node type is treemacs-lsp-treemacs-generic-node-closed [8 times]

Here are some screenshots illustrating the issue

Initial locals
![image](https://github.com/emacs-lsp/dap-mode/assets/39349995/f1db2726-cc0e-40d4-a6c6-d69b9744d0dd)

locals after a stack frame switch
![image](https://github.com/emacs-lsp/dap-mode/assets/39349995/335a12ad-aaab-4155-a88d-f6629f492a2b)
(this continues for a very long time)

EDIT:
This is python code by the way

**Comment by zackattackz** [comment]
Have made a temporary workaround in my init.el
```
(advice-add 'dap-ui-locals--refresh :before (lambda ()
                                              (let ((window (get-buffer-window)))
                                                (dap-ui-locals)
                                                (select-window window))))
```

This just restarts the locals buffer before it refreshes.

Still hangs a little bit though, and I still get the "This function cannot expand" error.

**Comment by yyoncho** [comment]
can you give me a little bit more detailed steps to reproduce? E. g. sample hello world cpp program what to expand and when to run dap-next.

**Comment by zackattackz** [comment]
Yes apologies for the lack of info. The issue is occurring when I'm debugging my work's software, which is quite complex. So I am unsure of the best way to reproduce, but I will attempt to make a python program to share to reproduce the issue. It may take me a while though, free time permitting.

**Comment by yyoncho** [comment]
https://github.com/Alexander-Miller/treemacs/issues/1034 fixed with this.

**Comment by zackattackz** [comment]
Thank you I'll test later. Apologies I never got around with a test case. Still I appreciate it.

**Comment by yyoncho** [comment]
No worries, I hit it too.
