### ISSUE TITLE
 How to specify the java version when I debug the program with dap-debug

### ISSUE THREAD

**Issue by LittleBlackTong** [emacs-lsp/dap-mode#742]
(use-package lsp-java 
  :ensure t
  :init 
  (setq lsp-java-java-path "/usr/local/Cellar/openjdk@17/17.0.7/libexec/openjdk.jdk/Contents/Home/bin/java")
  :config
  (setq lsp-java-configuration-runtimes '[(:name "JavaSE-1.8"
						                         :path "/usr/local/Cellar/openjdk@8/1.8.0+372/libexec/openjdk.jdk/Contents/Home/"
						                         :default t
						                         )
					                      (:name "JavaSE-17"
						                         :path "/usr/local/Cellar/openjdk@17/17.0.7/libexec/openjdk.jdk/Contents/Home/"
						                         )])
  (add-hook 'java-mode-hook 'lsp))

(require 'lsp-java-boot)
;; to enable the lenses
(add-hook 'lsp-mode-hook #'lsp-lens-mode)
(add-hook 'java-mode-hook #'lsp-java-boot-lens-mode)

(setq lsp-inhibit-message t)
(setq lsp-ui-sideline-update-mode 'point)

(setq dap-java-java-command "/usr/local/Cellar/openjdk@8/1.8.0+372/libexec/openjdk.jdk/Contents/Home/bin/java")
;;(setq dap-java-java-command "/usr/local/Cellar/openjdk@17/17.0.7/libexec/openjdk.jdk/Contents/Home/bin/java")

(setq lsp-java-import-maven-enabled 1)

(setq lsp-java-configuration-maven-user-settings "/Users/zhou/Documents/DevelopTool/maven/settings.xml")

(setq lsp-java-vmargs '(
			            "-XX:+UseParallelGC" 
			            "-XX:GCTimeRatio=4" 
			            "-XX:AdaptiveSizePolicyWeight=90" 
			            "-Dsun.zip.disableMemoryMapping=true" 
			            "-Xmx6G" 
			            "-Xms2G"
			            "-javaagent:/Users/zhou/Documents/DevelopTool/maven/repository/org/projectlombok/lombok/1.18.26/lombok-1.18.26.jar"
			            ))

;;(setq lsp-java-jdt-download-url  "https://download.eclipse.org/jdtls/milestones/0.57.0/jdt-language-server-0.57.0-202006172108.tar.gz")

(dap-register-debug-template ""
                             (list :type "java"
                                   :request "launch"
                                   :vmArgs "--add-opens java.base/java.lang=ALL-UNNAMED -Denv=qa"
                                   :args "-Denv=qa"
				                   :modulePaths (vector)
				                   :request "launch"
                                   :mainClass ""
                                   :port 8080
                                   :host "127.0.0.1"
                                   :env '(("WOAUTH_URL" . "m") ("APP_ID" . "rocll") ("HOSTNAME" . "qa"))
                                   ))

dap-java-java-command not working

**Comment by yyoncho** [comment]
closing this in favor of the one reported in the lsp-java repo.
