### ISSUE TITLE
dap-java should provide way to pass extra args to jvm

### ISSUE THREAD

**Issue by andreoss** [emacs-lsp/dap-mode#75]
`dap-java` should either honour `lsp-java-vmargs` or provide a way to pass jvm arguments
This feature is primarily needed for tools such as jacoco or jmockit

Ideally maven's `argLine` tags or gradle's `jvmArgs` should be respected in `dap-java-run-*` functions
Though it seems such feature cannot be directly implemented in `dap` but rather belongs to `lsp-java` or LSP server itself. I might be wrong

**Comment by yyoncho** [comment]
You could pass args even now by doing `dap-debug-edit-template`, then selecting java configuration and setting the :vmArgs . Full list of supported properties could be found here: https://github.com/Microsoft/vscode-java-debug . Currently, there is no template for JUnit test though.

**Comment by andreoss** [comment]
Should there be `dap-test-template-configurations` then? 
Thus `dap-java-run-test-method` could use one of registered configuration for java and junit?

**Comment by yyoncho** [comment]
> Should there be `dap-test-template-configurations` then?
> Thus `dap-java-run-test-method` could use one of registered configuration for java and junit?

Yes.

**Comment by rhinoman** [comment]
Was anyone able to get this to work?  Setting :vmArgs and :args both appear to have no effect.

**Comment by r-darwish** [comment]
`:vmArgs` seem to work for me

**Comment by yyoncho** [comment]
closing based on https://github.com/emacs-lsp/dap-mode/issues/75#issuecomment-538976668
