### ISSUE TITLE
dap-php-setup doesn't work

### ISSUE THREAD

**Issue by Kazimazi** [emacs-lsp/dap-mode#76]
I tried running it, in the *Messages* buffer I've got the following: 

> dap-php: felixfbecker.php-debug debug extension are not set. You can download it with M-x dap-php-setup
Contacting host: marketplace.visualstudio.com:443
uncompressing publicsuffix.txt.gz...done
Wrote /tmp/extcqZSxg.zip
helm-M-x: Wrong type argument: stringp, nil

**Comment by yyoncho** [comment]
Can you do toggle-debug-on-error and post the callstack?

**Comment by Kazimazi** [comment]
`Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  format(nil "/tmp/ext50ZSUT.zip" "/home/kazimazi/.emacs.d/.extension/vscode/felixfbecker.php-debug")
  dap-utils--get-extension("https://marketplace.visualstudio.com/_apis/public/gallery/publishers/felixfbecker/vsextensions/php-debug/latest/vspackage" "/home/kazimazi/.emacs.d/.extension/vscode/felixfbecker.php-debug")
  dap-utils-get-vscode-extension("felixfbecker" "php-debug" nil "/home/kazimazi/.emacs.d/.extension/vscode/felixfbecker.php-debug")
  dap-php-setup(nil)
  funcall-interactively(dap-php-setup nil)
  call-interactively(dap-php-setup record nil)
  command-execute(dap-php-setup record)
  helm-M-x(nil #("dap-php-setup" 0 13 (match-part "dap-php-setup")))
  funcall-interactively(helm-M-x nil #("dap-php-setup" 0 13 (match-part "dap-php-setup")))
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
`

**Comment by yyoncho** [comment]
@Kazimazi I guess you are on windows? 

```
(defcustom dap-utils-unzip-script (cond ((executable-find "unzip") dap-utils--ext-unzip-script)
                                        ((executable-find "powershell") dap-utils--ext-pwsh-script)
                                        (t nil))
  "The script to unzip vscode extension package file."
  :group 'dap-utils
  :type 'string)
```

It seems like this piece of code does not work on your machine? Can you check why you do not have unzip/powershell on the path?

**Comment by Kazimazi** [comment]
I'm on a relatively fresh Arch Linux install.

**Comment by yyoncho** [comment]
can you ensure that unzip is on the path?

**Comment by Kazimazi** [comment]
I had to installed unzip. Now it works, thx for the help.
