### ISSUE TITLE
dap-cpptools is not available as a package to download

### ISSUE THREAD

**Issue by yogeshwani** [emacs-lsp/dap-mode#777]
Hi 

The following instruction to install dap-cpptools doesn't work. 

My Emacs version is: GNU Emacs 28.2 (build 2, x86_64-w64-mingw32) of 2022-09-13

`dap-mode provides installation commands for most of the debug adapters. In this tutorial we will use the [vscode-cpptools](https://github.com/microsoft/vscode-cpptools) debug adapter. To install the adapter do M-x dap-cpptools-setup.` 

Emacs says no such command. How to install this and are there any updated instructions for C/C++ debugging ?

Following is the screenshot for M-x dap-cp. 
![image](https://github.com/emacs-lsp/dap-mode/assets/1408901/191617a7-0f4d-4477-bd91-4bebc7d550d7)

Thanks and Regards,
Yogesh

**Comment by yyoncho** [comment]
add `(require 'dap-cpptools)` to your setup.

**Comment by yogeshwani** [comment]
Thanks a lot! That does work. Earlier, I was trying to use 

> (use-package dap-cpptools) 

and this didn't work. So I am bit confused because I was under the impression that use-package uses require under the hood ? Is this not true ? Can you please let me know why require works and use-package doesn't please ?

Thanks again for your response.

**Comment by yyoncho** [comment]
> and this didn't work. So I am bit confused because I was under the impression that use-package uses require under the hood ? Is this not true ? Can you please let me know why require works and use-package doesn't please ?

I am not very familiar with use-package but I believe that it is lazy, thus it is not executed.
