### ISSUE TITLE
Cannot navigate between stack frames in dap-ui-sessions: No buffer named /path/to/file

### ISSUE THREAD

**Issue by bastianbeischer** [emacs-lsp/dap-mode#784]
Commit [a31f2496605d076d50d49393116f77fbb29f2631](https://github.com/emacs-lsp/dap-mode/commit/a31f2496605d076d50d49393116f77fbb29f2631)

is broken:

Function `dap--buffers-w-breakpoints` does not return a list of buffers. The hash table keys of dap--buffers-w-breakpoints are not buffers but filenames.

If I revert the mentioned commit I can navigate between stack frames in dap-ui-sessions for example, with master I get "No buffer named /path/to/buffer" error instead.

**Comment by bastianbeischer** [comment]
I guess https://github.com/emacs-lsp/dap-mode/pull/768 should fix this

**Comment by jcs090218** [comment]
Closing this since #768 is merged.
