### ISSUE TITLE
dap-debug lsp-go fails with: Searching for program: No such file or directory, node

### ISSUE THREAD

**Issue by iris-garcia** [emacs-lsp/dap-mode#79]
First of all, thank you very much for this package.

This is the current configuration I have (it works perfectly fine with python for example):

```
(defun ig/go-mode-hook ()
      (add-to-list 'company-backends 'company-go)
      (setq tab-width 4)
      )
````
```
(use-package go-mode
  :ensure t
  :hook (
         (go-mode . ig/go-mode-hook)
         (go-mode . flycheck-mode))

  :config
  (require 'dap-go)
  (dap-go-setup)
  (setq gofmt-command "goimports")
  )
```

```
(use-package lsp-mode
      :hook (
             (python-mode . lsp)
             (go-mode . lsp))
      :config
      (require 'lsp-clients)
      ;; Disable flymake
      (setq lsp-prefer-flymake nil)
      (lsp-register-client
       (make-lsp-client :new-connection (lsp-stdio-connection "gopls")
                        :major-modes '(go-mode)
                        :server-id 'gopls)))
```

Trying to start a debug session (e.g. add a breakpoint then run `dap-debug`) gives the message:
**Searching for program: No such file or directory, node**

Maybe it is not a real issue of `dap-mode` but to be honest I can not figure out where the issue comes from.

**Comment by yyoncho** [comment]
Did you try to install node?

**Comment by iris-garcia** [comment]
Wow... I thought the keyword node was somewhere defined in the elisp code, didn't even think on nodejs as requirement (I guess it is needed in order to use the VSCode extension).

Now I get:
```
Debug session process exited with status: exited abnormally with code 127
```
But I guess that is something failing in my GoLang code.

Thanks a lot @yyoncho .

**Comment by yyoncho** [comment]
> Note: Maybe is worth it to add `node` as a dependency for Go somewhere in the documentation?

Yes + better error messaging.
