### ISSUE TITLE
dap-lldb: depends on deprecated vscode extension

### ISSUE THREAD

**Issue by lsp-ableton** [emacs-lsp/dap-mode#799]
The vscode extension has been renamed from `lldb-vscode` to `lldb-dap`. Thus `dap-lldb-debug-program` will no longer point to the right extension. 

I tried changing everything to point to the new extension, but it doesn't work, and I can't figure out why so far. The new `lldb-dap` extension no longer contains a binary AFAICT, so installed it with `brew install llvm`, and I point `dap-mode` to `/opt/homebrew/opt/llvm/bin/lldb-dap`. I can successfuly start it from the command line.

The error is `wrong type argument: stringp, nil` to `make-process` in `dap--create-session` (this is on Emacs 29.1).

If I remove the `:stderr` argument to `make-process`, the wrong argument type error no longer happens, but I'm not sure why. Then there is another error in `dap--send-message`
```
Output file descriptor of LLDB::Debug is closed
```
The status of the process at that point is `run`

**Comment by lsp-ableton** [comment]
If I remove the `:stderr` argument to `make-process`, the wrong argument type error no longer happens, but I'm not sure why. 

Then there is another error in `dap--send-message`
```
Output file descriptor of LLDB::Debug is closed
```

**Comment by vibrys** [comment]
did you try to customize `dap-lldb-debug-program` to point to `lldb-dap`?

**Comment by eu-ch** [comment]
I confirm changing `dap-lldb-debug-program` to `lldb-dap` doesn't solve the problem. The following still applies to me:

> The error is wrong type argument: stringp, nil to make-process in dap--create-session (this is on Emacs 29.1).

**Comment by eu-ch** [comment]
I confirm this `lldb-dap` works after setting `dap-lldb-debug-program` on Linux. I had the same problem as the OP, and the mistake was in setting the variable to a string, not to a list. This is how I got it working:
```elisp
(use-package dap-mode
  :custom
  ;; This doesn't work
  ;; (dap-lldb-debug-program "lldb-dap")
  (dap-lldb-debug-program `("lldb-dap")))
```

**Comment by lsp-ableton** [comment]
> I confirm this lldb-vscode works after setting dap-lldb-debug-program on Linux. I had the same problem as the OP, and the mistake was in setting the variable to a string, not to a list. This is how I got it working:

That was my mistake. Thanks for your help!
