### ISSUE TITLE
repl replaced by source file when stepping

### ISSUE THREAD

**Issue by prittjam** [emacs-lsp/dap-mode#89]
When I'm stepping through python code, the repl gets replaced with the source file being debugged. This is annoying since I would like to evaluate the state of the program at the REPL. Do you have some suggestions for changing this behavior?

**Comment by yyoncho** [comment]
Is this python repl or dap repl? Dap mode place the cursor at the breakpoint once it is hit, is this what you want to change?

**Comment by prittjam** [comment]
I call M-x dap-ui-repl to open it, so I assume it is a dap repl. I have a split frame with 2 buffers. The source with the break point is on the right and the repl is on the left. When I step, the REPL gets replaced by the source buffer, so the source buffer is shown twice.

**Comment by yyoncho** [comment]
I am not on my PC to try it but this might fix that : https://emacs.stackexchange.com/questions/2189/how-can-i-prevent-a-command-from-using-specific-windows

**Comment by prittjam** [comment]
Hi. Thanks for the tip. That sort of works. The REPL is not replaced, but it splits the window in 2 and opens another view of the source file.

**Comment by yyoncho** [comment]
After  3440ea5 it should work in combination with making the repl buffer dedicated. You could use dap-ui-repl-mode-hook to make that automatic.
