### ISSUE TITLE
How to debug python for "console_scripts" with extra arguments?

### ISSUE THREAD

**Issue by yssource** [emacs-lsp/dap-mode#92]
I know it is ok to debug using `dap-debug-edit-template`.
But, I don't know how to debug the "console_scripts".
For exmaple. After installing my setup.py, I can invoke the command `hello -m "world!"`.
I'd like to know how to debug it with dap-mode.

``` python
from setuptools import setup

setup(
    name="hello",
    packages=["hello"],
    entry_points = {
        "console_scripts": [
            "hello = hello.main:main",
        ]
    }
)
```
Thanks.

**Comment by yssource** [comment]
a workaround for me. Setting `target-module` to the real entry_point for entry_point, my here is `hello.main:main`, which points to file `/tmp/hello/hello/main.py`
- `M-x dap-debug-edit-template`
``` elisp
(dap-register-debug-template "hello"
  (list :type "python"
        :args '-m "world!"'
        :cwd "/tmp/hello"
        :target-module "/tmp/hello/hello/main.py"
        :request "launch"
        :name "hello"))
```
- `M-x eval-buffer` DAP-Templates
- `M-x dap-debug`

**Comment by yyoncho** [comment]
Do you think that registering another default template will make it easier for the users? If yes, feel free to provide a PR.
