### ISSUE TITLE
dap-debug-edit-template broken with python?

### ISSUE THREAD

**Issue by prittjam** [emacs-lsp/dap-mode#95]
I am trying to debug a python script. I am unable to edit a template; it just seems non-existent. The minibuffer asks to select a template, but there are none available and there is no way to create a new one. I am using the Microsoft python language server.

**Comment by yyoncho** [comment]
You have required dap-python you are probably using the default completing-read interface where you should press tab to see all the options.

**Comment by prittjam** [comment]
Thanks for the fast response. I really appreciate it. It was simple. I required only dap-mode, not dap-python.

**Comment by yyoncho** [comment]
Do we need to close the issue now?
