### ISSUE TITLE
Support ms-python

### ISSUE THREAD

**Issue by seagle0128** [emacs-lsp/dap-mode#98]
Microsoft provides a better LSP and DAP for Python.

https://marketplace.visualstudio.com/items?itemName=ms-python.python

Is it possible to support it in `dap-python` like `dap-go`?

**Comment by yyoncho** [comment]
we are using the same debug adapter, here it is what vscode runs:

```
cd /home/kyoncho/.tmp/lsp-typescript-demo ; env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /usr/bin/python3 /home/kyoncho/.vscode/extensions/ms-python.python-2019.5.18875/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 44261 /home/kyoncho/.tmp//sss.py 
```

**Comment by seagle0128** [comment]
Okay. I understand now. I am closing it.
