### ISSUE TITLE
debug flask app 

### ISSUE THREAD

**Issue by nthainguyen** [emacs-lsp/dap-mode#99]
I cannot config dap-mode to work with flask.
is there a template to debug flask app with dap-mode?

**Comment by yyoncho** [comment]
Marking as closed. @nthainguyen reopen if the link provided above is not enough to solve your issue.

**Comment by f4nyc** [comment]
Hi, @nthainguyen ,have you handled this ?
I try to translate the guide to dap-mode template
```elisp
(dap-register-debug-template "Python :: Flask"
  (list :type "python"
        :env '(("FLASK_APP" . "GetFalconMsgByFlask.py") ("FLASK_ENV" . "development") ("FLASK_DEBUG" . "0"))
        :args "run --no-debugger --no-reload"
        :cwd nil
        :target-module nil
        :module "flask"
        :jinja  t
        :request "launch"
        :name "Python :: Flask"))
```
but it doesn't seem to work, dap-debug  just hit breakpoint only once before `app.run`
@yyoncho  I will  appreciate it  if you could  help.

**Comment by yyoncho** [comment]
@f4nyc can you help by providing sample project + setup instructions and eventually vscode debug configuration (if you have such)?

**Comment by f4nyc** [comment]
It's just a single file GetFalconMsgByFlask.py  working with pipenv.
My vscode debug configuration which works normally is
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Flask",
            "type": "python",
            "request": "launch",
            "module": "flask",
            "env": {
                "FLASK_APP": "GetFalconMsgByFlask",
                "FLASK_ENV": "development",
                "FLASK_DEBUG": "0"
            },
            "args": [
                "run",
                "--no-debugger",
                "--no-reload"
            ],
            "jinja": true
        }
    ]
}
```
And i got `~/.local/share/virtualenvs/src-nmOAoBs2/bin/python -m ptvsd --wait --host localhost --port 32000 GetFalconMsgByFlask.py run --no-debugger --no-reload` from emacs.

 I am pretty confused about the module and target-module.

**Comment by nthainguyen** [comment]
I haven't worked with flask for a while and I forgot to document the config. But here is what I remember. You don't have to translate the configuration perfectly from vscode. Just focus on the args so that the resulting command run by dap mode looks similar to the vscode one.

If you can post the command that dap mode run when you start debugging with your config, I may be able to help you out.

**Comment by f4nyc** [comment]
I notice that dap-python.el only defined 
```elisp
(dap--put-if-absent conf :program-to-start
                        (format "%s -m ptvsd --wait --host %s --port %s %s %s"
                                python-executable host debug-port python-target-module python-args))
```
So I  add "-m flask" to args, and it works !
But it's soooooo weird , maybe we could edit dap-python.el to support module config？

**Comment by yyoncho** [comment]
> I notice that dap-python.el only defined
> 
> ```emacs-lisp
> (dap--put-if-absent conf :program-to-start
>                         (format "%s -m ptvsd --wait --host %s --port %s %s %s"
>                                 python-executable host debug-port python-target-module python-args))
> ```
> 
> So I add "-m flask" to args, and it works !
> But it's soooooo weird , maybe we could edit dap-python.el to support module config？

when you add `:module "flask"` it should result into the same command, no?

`:target-module` is kept for backward compatibility reasons.

**Comment by f4nyc** [comment]
I wonder if module command is not supported by dap-python, because only several commands are handled.
```lisp
  (let* ((host "localhost")
         (debug-port (dap--find-available-port host dap-python-default-debug-port))
         (python-executable (dap-python--pyenv-executable-find dap-python-executable))
         (python-args (or (plist-get conf :args) ""))
         (python-target-module (or (plist-get conf :target-module) buffer-file-name)))

    (dap--put-if-absent conf :program-to-start
                        (format "%s -m ptvsd --wait --host %s --port %s %s %s"
                                python-executable host debug-port python-target-module python-args))
```
I'm pretty sure that ` :module "flask"` doesn't work while `args "-m flask"` does.

**Comment by yyoncho** [comment]
@f4nyc are you using the latest dap-python.el? Here it is how the code looks like right now:

```
    (dap--put-if-absent conf :program-to-start
                        (format "%s -m ptvsd --wait --host %s --port %s %s %s %s"
                                python-executable
                                host
                                debug-port
                                (if module (concat "-m " module) "")
                                program
                                python-args))
```

**Comment by f4nyc** [comment]
Opps!  I just migrated to spacemacs months ago. Thanks a lot!

**Comment by parsoj** [comment]
@yyoncho - I was working on getting flask working as well - following the guide you linked to above. 

I made some tweaks to get it working for myself - and wanted to write what I found:
this is my debug template:
```
(dap-register-debug template "Test"
 (list
  :name "Python: Flask"
  :type "python"
  :request "launch"
  :module "flask"
  :cwd nil
  :env '(
	 ("FLASK_APP" . "app.py")
	 ("FLASK_ENV" . "development")
	 ("FLASK_DEBUG": "0")
	 )
  :args (concat
	 "run"
	 " --no-debugger"
	 " --no-reload"
	 )
  :jinja t
  ))
```
the current code generates this cli command:
```
/usr/local/bin/python3 -m ptvsd --wait --host localhost --port 32000 -m flask <path-to-current-buffer-file>  run --no-debugger --no-reload
```

however I needed to get it to look like this to make flask happy:
```
/usr/local/bin/python3 -m ptvsd --wait --host localhost --port 32000 -m flask run --no-debugger --no-reload
```
(i.e. I needed to explicitly remove the <path-to-current-buffer-file> part) 

making this change has it working for me: 
https://github.com/parsoj/dap-mode/commit/7e2672de2f5a1b766a336b3de507717371d4f379
However I'm not sure if this would be breaking alot of debug templates for people - since it will no longer use the current-buffer-file if you don't provide a "program" or "target-module" in the template

**Comment by parsoj** [comment]
I'm not sure what the most idiomatic way to implement the desired support for flask would be - either through a tweak to `dap-python.el`, or providing a new debug-provider entirely. LMK your thoughts, and I'd be happy to PR a change in the appropriate place to provide flask support :)

**Comment by yyoncho** [comment]
@parsoj what about changing the code to use `(buffer-file-name)` only if the template itself has `:program` key?
